

-- AlterTable
ALTER TABLE "User"
DROP COLUMN "onboardingSteps",
DROP COLUMN "tos",
ADD COLUMN     "blurLevel" INTEGER NOT NULL DEFAULT 0
ADD COLUMN     "browsingLevel" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "onboarding" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "showNsfw" SET NOT NULL,
ALTER COLUMN "blurNsfw" SET NOT NULL,
ALTER COLUMN "muted" SET NOT NULL,
ALTER COLUMN "muted" SET DEFAULT false;


DELETE FROM "TagEngagement" WHERE "tagId" = ANY('{"113976","113474","113645","113644","113660","113975"}');
