-- AlterEnum
ALTER TYPE "TagTarget" ADD VALUE 'Article';

-- AlterTable
ALTER TABLE "ImageRank" ALTER COLUMN "imageId" SET NOT NULL,
ALTER COLUMN "heartCountDayRank" SET NOT NULL,
ALTER COLUMN "heartCountDayRank" SET DEFAULT 0,
ALTER COLUMN "heartCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountWeekRank" SET NOT NULL,
ALTER COLUMN "heartCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "heartCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountMonthRank" SET NOT NULL,
ALTER COLUMN "heartCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "heartCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountYearRank" SET NOT NULL,
ALTER COLUMN "heartCountYearRank" SET DEFAULT 0,
ALTER COLUMN "heartCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "heartCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "heartCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountDayRank" SET NOT NULL,
ALTER COLUMN "likeCountDayRank" SET DEFAULT 0,
ALTER COLUMN "likeCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountWeekRank" SET NOT NULL,
ALTER COLUMN "likeCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "likeCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountMonthRank" SET NOT NULL,
ALTER COLUMN "likeCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "likeCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountYearRank" SET NOT NULL,
ALTER COLUMN "likeCountYearRank" SET DEFAULT 0,
ALTER COLUMN "likeCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "likeCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "likeCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountDayRank" SET NOT NULL,
ALTER COLUMN "dislikeCountDayRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountWeekRank" SET NOT NULL,
ALTER COLUMN "dislikeCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountMonthRank" SET NOT NULL,
ALTER COLUMN "dislikeCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountYearRank" SET NOT NULL,
ALTER COLUMN "dislikeCountYearRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "dislikeCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountDayRank" SET NOT NULL,
ALTER COLUMN "laughCountDayRank" SET DEFAULT 0,
ALTER COLUMN "laughCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountWeekRank" SET NOT NULL,
ALTER COLUMN "laughCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "laughCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountMonthRank" SET NOT NULL,
ALTER COLUMN "laughCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "laughCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountYearRank" SET NOT NULL,
ALTER COLUMN "laughCountYearRank" SET DEFAULT 0,
ALTER COLUMN "laughCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "laughCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "laughCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountDayRank" SET NOT NULL,
ALTER COLUMN "cryCountDayRank" SET DEFAULT 0,
ALTER COLUMN "cryCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountWeekRank" SET NOT NULL,
ALTER COLUMN "cryCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "cryCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountMonthRank" SET NOT NULL,
ALTER COLUMN "cryCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "cryCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountYearRank" SET NOT NULL,
ALTER COLUMN "cryCountYearRank" SET DEFAULT 0,
ALTER COLUMN "cryCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "cryCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "cryCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountDayRank" SET NOT NULL,
ALTER COLUMN "reactionCountDayRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountWeekRank" SET NOT NULL,
ALTER COLUMN "reactionCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountMonthRank" SET NOT NULL,
ALTER COLUMN "reactionCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountYearRank" SET NOT NULL,
ALTER COLUMN "reactionCountYearRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "reactionCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountDayRank" SET NOT NULL,
ALTER COLUMN "commentCountDayRank" SET DEFAULT 0,
ALTER COLUMN "commentCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountWeekRank" SET NOT NULL,
ALTER COLUMN "commentCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "commentCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountMonthRank" SET NOT NULL,
ALTER COLUMN "commentCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "commentCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountYearRank" SET NOT NULL,
ALTER COLUMN "commentCountYearRank" SET DEFAULT 0,
ALTER COLUMN "commentCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "commentCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "commentCountAllTimeRank" SET DATA TYPE INTEGER,
ADD CONSTRAINT "ImageRank_pkey" PRIMARY KEY ("imageId");

-- AlterTable
ALTER TABLE "ModelRank" DROP COLUMN "age_days",
ALTER COLUMN "modelId" SET NOT NULL,
ALTER COLUMN "downloadCountDay" SET NOT NULL,
ALTER COLUMN "downloadCountDay" SET DEFAULT 0,
ALTER COLUMN "ratingCountDay" SET NOT NULL,
ALTER COLUMN "ratingCountDay" SET DEFAULT 0,
ALTER COLUMN "favoriteCountDay" SET NOT NULL,
ALTER COLUMN "favoriteCountDay" SET DEFAULT 0,
ALTER COLUMN "commentCountDay" SET NOT NULL,
ALTER COLUMN "commentCountDay" SET DEFAULT 0,
ALTER COLUMN "ratingDay" SET NOT NULL,
ALTER COLUMN "ratingDay" SET DEFAULT 0,
ALTER COLUMN "downloadCountWeek" SET NOT NULL,
ALTER COLUMN "downloadCountWeek" SET DEFAULT 0,
ALTER COLUMN "ratingCountWeek" SET NOT NULL,
ALTER COLUMN "ratingCountWeek" SET DEFAULT 0,
ALTER COLUMN "favoriteCountWeek" SET NOT NULL,
ALTER COLUMN "favoriteCountWeek" SET DEFAULT 0,
ALTER COLUMN "commentCountWeek" SET NOT NULL,
ALTER COLUMN "commentCountWeek" SET DEFAULT 0,
ALTER COLUMN "ratingWeek" SET NOT NULL,
ALTER COLUMN "ratingWeek" SET DEFAULT 0,
ALTER COLUMN "downloadCountMonth" SET NOT NULL,
ALTER COLUMN "downloadCountMonth" SET DEFAULT 0,
ALTER COLUMN "ratingCountMonth" SET NOT NULL,
ALTER COLUMN "ratingCountMonth" SET DEFAULT 0,
ALTER COLUMN "favoriteCountMonth" SET NOT NULL,
ALTER COLUMN "favoriteCountMonth" SET DEFAULT 0,
ALTER COLUMN "commentCountMonth" SET NOT NULL,
ALTER COLUMN "commentCountMonth" SET DEFAULT 0,
ALTER COLUMN "ratingMonth" SET NOT NULL,
ALTER COLUMN "ratingMonth" SET DEFAULT 0,
ALTER COLUMN "downloadCountYear" SET NOT NULL,
ALTER COLUMN "downloadCountYear" SET DEFAULT 0,
ALTER COLUMN "ratingCountYear" SET NOT NULL,
ALTER COLUMN "ratingCountYear" SET DEFAULT 0,
ALTER COLUMN "favoriteCountYear" SET NOT NULL,
ALTER COLUMN "favoriteCountYear" SET DEFAULT 0,
ALTER COLUMN "commentCountYear" SET NOT NULL,
ALTER COLUMN "commentCountYear" SET DEFAULT 0,
ALTER COLUMN "ratingYear" SET NOT NULL,
ALTER COLUMN "ratingYear" SET DEFAULT 0,
ALTER COLUMN "downloadCountAllTime" SET NOT NULL,
ALTER COLUMN "downloadCountAllTime" SET DEFAULT 0,
ALTER COLUMN "ratingCountAllTime" SET NOT NULL,
ALTER COLUMN "ratingCountAllTime" SET DEFAULT 0,
ALTER COLUMN "favoriteCountAllTime" SET NOT NULL,
ALTER COLUMN "favoriteCountAllTime" SET DEFAULT 0,
ALTER COLUMN "commentCountAllTime" SET NOT NULL,
ALTER COLUMN "commentCountAllTime" SET DEFAULT 0,
ALTER COLUMN "ratingAllTime" SET NOT NULL,
ALTER COLUMN "ratingAllTime" SET DEFAULT 0,
ALTER COLUMN "downloadCountDayRank" SET NOT NULL,
ALTER COLUMN "downloadCountDayRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountDayRank" SET NOT NULL,
ALTER COLUMN "ratingCountDayRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountDayRank" SET NOT NULL,
ALTER COLUMN "favoriteCountDayRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountDayRank" SET NOT NULL,
ALTER COLUMN "commentCountDayRank" SET DEFAULT 0,
ALTER COLUMN "commentCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingDayRank" SET NOT NULL,
ALTER COLUMN "ratingDayRank" SET DEFAULT 0,
ALTER COLUMN "ratingDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountWeekRank" SET NOT NULL,
ALTER COLUMN "downloadCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountWeekRank" SET NOT NULL,
ALTER COLUMN "ratingCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountWeekRank" SET NOT NULL,
ALTER COLUMN "favoriteCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountWeekRank" SET NOT NULL,
ALTER COLUMN "commentCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "commentCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingWeekRank" SET NOT NULL,
ALTER COLUMN "ratingWeekRank" SET DEFAULT 0,
ALTER COLUMN "ratingWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountMonthRank" SET NOT NULL,
ALTER COLUMN "downloadCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountMonthRank" SET NOT NULL,
ALTER COLUMN "ratingCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountMonthRank" SET NOT NULL,
ALTER COLUMN "favoriteCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountMonthRank" SET NOT NULL,
ALTER COLUMN "commentCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "commentCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingMonthRank" SET NOT NULL,
ALTER COLUMN "ratingMonthRank" SET DEFAULT 0,
ALTER COLUMN "ratingMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountYearRank" SET NOT NULL,
ALTER COLUMN "downloadCountYearRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountYearRank" SET NOT NULL,
ALTER COLUMN "ratingCountYearRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountYearRank" SET NOT NULL,
ALTER COLUMN "favoriteCountYearRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountYearRank" SET NOT NULL,
ALTER COLUMN "commentCountYearRank" SET DEFAULT 0,
ALTER COLUMN "commentCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingYearRank" SET NOT NULL,
ALTER COLUMN "ratingYearRank" SET DEFAULT 0,
ALTER COLUMN "ratingYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "downloadCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "ratingCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "favoriteCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "commentCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "commentCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingAllTimeRank" SET NOT NULL,
ALTER COLUMN "ratingAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "ratingAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "newRank" SET NOT NULL,
ALTER COLUMN "newRank" SET DEFAULT 0,
ALTER COLUMN "newRank" SET DATA TYPE INTEGER,
ADD CONSTRAINT "ModelRank_pkey" PRIMARY KEY ("modelId");

-- AlterTable
ALTER TABLE "ModelVersionRank" ALTER COLUMN "modelVersionId" SET NOT NULL,
ALTER COLUMN "downloadCountDay" SET NOT NULL,
ALTER COLUMN "downloadCountDay" SET DEFAULT 0,
ALTER COLUMN "ratingCountDay" SET NOT NULL,
ALTER COLUMN "ratingCountDay" SET DEFAULT 0,
ALTER COLUMN "ratingDay" SET NOT NULL,
ALTER COLUMN "ratingDay" SET DEFAULT 0,
ALTER COLUMN "downloadCountWeek" SET NOT NULL,
ALTER COLUMN "downloadCountWeek" SET DEFAULT 0,
ALTER COLUMN "ratingCountWeek" SET NOT NULL,
ALTER COLUMN "ratingCountWeek" SET DEFAULT 0,
ALTER COLUMN "ratingWeek" SET NOT NULL,
ALTER COLUMN "ratingWeek" SET DEFAULT 0,
ALTER COLUMN "downloadCountMonth" SET NOT NULL,
ALTER COLUMN "downloadCountMonth" SET DEFAULT 0,
ALTER COLUMN "ratingCountMonth" SET NOT NULL,
ALTER COLUMN "ratingCountMonth" SET DEFAULT 0,
ALTER COLUMN "ratingMonth" SET NOT NULL,
ALTER COLUMN "ratingMonth" SET DEFAULT 0,
ALTER COLUMN "downloadCountYear" SET NOT NULL,
ALTER COLUMN "downloadCountYear" SET DEFAULT 0,
ALTER COLUMN "ratingCountYear" SET NOT NULL,
ALTER COLUMN "ratingCountYear" SET DEFAULT 0,
ALTER COLUMN "ratingYear" SET NOT NULL,
ALTER COLUMN "ratingYear" SET DEFAULT 0,
ALTER COLUMN "downloadCountAllTime" SET NOT NULL,
ALTER COLUMN "downloadCountAllTime" SET DEFAULT 0,
ALTER COLUMN "ratingCountAllTime" SET NOT NULL,
ALTER COLUMN "ratingCountAllTime" SET DEFAULT 0,
ALTER COLUMN "ratingAllTime" SET NOT NULL,
ALTER COLUMN "ratingAllTime" SET DEFAULT 0,
ALTER COLUMN "downloadCountDayRank" SET NOT NULL,
ALTER COLUMN "downloadCountDayRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountDayRank" SET NOT NULL,
ALTER COLUMN "ratingCountDayRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingDayRank" SET NOT NULL,
ALTER COLUMN "ratingDayRank" SET DEFAULT 0,
ALTER COLUMN "ratingDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountWeekRank" SET NOT NULL,
ALTER COLUMN "downloadCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountWeekRank" SET NOT NULL,
ALTER COLUMN "ratingCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingWeekRank" SET NOT NULL,
ALTER COLUMN "ratingWeekRank" SET DEFAULT 0,
ALTER COLUMN "ratingWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountMonthRank" SET NOT NULL,
ALTER COLUMN "downloadCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountMonthRank" SET NOT NULL,
ALTER COLUMN "ratingCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingMonthRank" SET NOT NULL,
ALTER COLUMN "ratingMonthRank" SET DEFAULT 0,
ALTER COLUMN "ratingMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountYearRank" SET NOT NULL,
ALTER COLUMN "downloadCountYearRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountYearRank" SET NOT NULL,
ALTER COLUMN "ratingCountYearRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingYearRank" SET NOT NULL,
ALTER COLUMN "ratingYearRank" SET DEFAULT 0,
ALTER COLUMN "ratingYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "downloadCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "ratingCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingAllTimeRank" SET NOT NULL,
ALTER COLUMN "ratingAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "ratingAllTimeRank" SET DATA TYPE INTEGER,
ADD CONSTRAINT "ModelVersionRank_pkey" PRIMARY KEY ("modelVersionId");

-- AlterTable
ALTER TABLE "PostRank" ALTER COLUMN "postId" SET NOT NULL,
ALTER COLUMN "heartCountDayRank" SET NOT NULL,
ALTER COLUMN "heartCountDayRank" SET DEFAULT 0,
ALTER COLUMN "heartCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountWeekRank" SET NOT NULL,
ALTER COLUMN "heartCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "heartCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountMonthRank" SET NOT NULL,
ALTER COLUMN "heartCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "heartCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountYearRank" SET NOT NULL,
ALTER COLUMN "heartCountYearRank" SET DEFAULT 0,
ALTER COLUMN "heartCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "heartCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "heartCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "heartCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountDayRank" SET NOT NULL,
ALTER COLUMN "likeCountDayRank" SET DEFAULT 0,
ALTER COLUMN "likeCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountWeekRank" SET NOT NULL,
ALTER COLUMN "likeCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "likeCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountMonthRank" SET NOT NULL,
ALTER COLUMN "likeCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "likeCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountYearRank" SET NOT NULL,
ALTER COLUMN "likeCountYearRank" SET DEFAULT 0,
ALTER COLUMN "likeCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "likeCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "likeCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "likeCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountDayRank" SET NOT NULL,
ALTER COLUMN "dislikeCountDayRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountWeekRank" SET NOT NULL,
ALTER COLUMN "dislikeCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountMonthRank" SET NOT NULL,
ALTER COLUMN "dislikeCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountYearRank" SET NOT NULL,
ALTER COLUMN "dislikeCountYearRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "dislikeCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "dislikeCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "dislikeCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountDayRank" SET NOT NULL,
ALTER COLUMN "laughCountDayRank" SET DEFAULT 0,
ALTER COLUMN "laughCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountWeekRank" SET NOT NULL,
ALTER COLUMN "laughCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "laughCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountMonthRank" SET NOT NULL,
ALTER COLUMN "laughCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "laughCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountYearRank" SET NOT NULL,
ALTER COLUMN "laughCountYearRank" SET DEFAULT 0,
ALTER COLUMN "laughCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "laughCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "laughCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "laughCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountDayRank" SET NOT NULL,
ALTER COLUMN "cryCountDayRank" SET DEFAULT 0,
ALTER COLUMN "cryCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountWeekRank" SET NOT NULL,
ALTER COLUMN "cryCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "cryCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountMonthRank" SET NOT NULL,
ALTER COLUMN "cryCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "cryCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountYearRank" SET NOT NULL,
ALTER COLUMN "cryCountYearRank" SET DEFAULT 0,
ALTER COLUMN "cryCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "cryCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "cryCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "cryCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountDayRank" SET NOT NULL,
ALTER COLUMN "reactionCountDayRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountWeekRank" SET NOT NULL,
ALTER COLUMN "reactionCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountMonthRank" SET NOT NULL,
ALTER COLUMN "reactionCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountYearRank" SET NOT NULL,
ALTER COLUMN "reactionCountYearRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "reactionCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "reactionCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "reactionCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountDayRank" SET NOT NULL,
ALTER COLUMN "commentCountDayRank" SET DEFAULT 0,
ALTER COLUMN "commentCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountWeekRank" SET NOT NULL,
ALTER COLUMN "commentCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "commentCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountMonthRank" SET NOT NULL,
ALTER COLUMN "commentCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "commentCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountYearRank" SET NOT NULL,
ALTER COLUMN "commentCountYearRank" SET DEFAULT 0,
ALTER COLUMN "commentCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "commentCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "commentCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "commentCountAllTimeRank" SET DATA TYPE INTEGER,
ADD CONSTRAINT "PostRank_pkey" PRIMARY KEY ("postId");

-- AlterTable
ALTER TABLE "TagRank" ALTER COLUMN "tagId" SET NOT NULL,
ALTER COLUMN "followerCountDayRank" SET NOT NULL,
ALTER COLUMN "followerCountDayRank" SET DEFAULT 0,
ALTER COLUMN "followerCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountWeekRank" SET NOT NULL,
ALTER COLUMN "followerCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "followerCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountMonthRank" SET NOT NULL,
ALTER COLUMN "followerCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "followerCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountYearRank" SET NOT NULL,
ALTER COLUMN "followerCountYearRank" SET DEFAULT 0,
ALTER COLUMN "followerCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "followerCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "followerCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "hiddenCountDayRank" SET NOT NULL,
ALTER COLUMN "hiddenCountDayRank" SET DEFAULT 0,
ALTER COLUMN "hiddenCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "hiddenCountWeekRank" SET NOT NULL,
ALTER COLUMN "hiddenCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "hiddenCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "hiddenCountMonthRank" SET NOT NULL,
ALTER COLUMN "hiddenCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "hiddenCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "hiddenCountYearRank" SET NOT NULL,
ALTER COLUMN "hiddenCountYearRank" SET DEFAULT 0,
ALTER COLUMN "hiddenCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "hiddenCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "hiddenCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "hiddenCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "modelCountDayRank" SET NOT NULL,
ALTER COLUMN "modelCountDayRank" SET DEFAULT 0,
ALTER COLUMN "modelCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "modelCountWeekRank" SET NOT NULL,
ALTER COLUMN "modelCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "modelCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "modelCountMonthRank" SET NOT NULL,
ALTER COLUMN "modelCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "modelCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "modelCountYearRank" SET NOT NULL,
ALTER COLUMN "modelCountYearRank" SET DEFAULT 0,
ALTER COLUMN "modelCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "modelCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "modelCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "modelCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "imageCountDayRank" SET NOT NULL,
ALTER COLUMN "imageCountDayRank" SET DEFAULT 0,
ALTER COLUMN "imageCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "imageCountWeekRank" SET NOT NULL,
ALTER COLUMN "imageCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "imageCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "imageCountMonthRank" SET NOT NULL,
ALTER COLUMN "imageCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "imageCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "imageCountYearRank" SET NOT NULL,
ALTER COLUMN "imageCountYearRank" SET DEFAULT 0,
ALTER COLUMN "imageCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "imageCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "imageCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "imageCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "postCountDayRank" SET NOT NULL,
ALTER COLUMN "postCountDayRank" SET DEFAULT 0,
ALTER COLUMN "postCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "postCountWeekRank" SET NOT NULL,
ALTER COLUMN "postCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "postCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "postCountMonthRank" SET NOT NULL,
ALTER COLUMN "postCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "postCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "postCountYearRank" SET NOT NULL,
ALTER COLUMN "postCountYearRank" SET DEFAULT 0,
ALTER COLUMN "postCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "postCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "postCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "postCountAllTimeRank" SET DATA TYPE INTEGER,
ADD CONSTRAINT "TagRank_pkey" PRIMARY KEY ("tagId");

-- AlterTable
ALTER TABLE "Thread" ADD COLUMN     "articleId" INTEGER;

-- AlterTable
ALTER TABLE "UserRank" ALTER COLUMN "userId" SET NOT NULL,
ALTER COLUMN "leaderboardRank" SET NOT NULL,
ALTER COLUMN "leaderboardRank" SET DEFAULT 0,
ALTER COLUMN "leaderboardRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountDayRank" SET NOT NULL,
ALTER COLUMN "downloadCountDayRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountDayRank" SET NOT NULL,
ALTER COLUMN "favoriteCountDayRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountDayRank" SET NOT NULL,
ALTER COLUMN "ratingCountDayRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingDayRank" SET NOT NULL,
ALTER COLUMN "ratingDayRank" SET DEFAULT 0,
ALTER COLUMN "ratingDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountDayRank" SET NOT NULL,
ALTER COLUMN "followerCountDayRank" SET DEFAULT 0,
ALTER COLUMN "followerCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountWeekRank" SET NOT NULL,
ALTER COLUMN "downloadCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountWeekRank" SET NOT NULL,
ALTER COLUMN "favoriteCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountWeekRank" SET NOT NULL,
ALTER COLUMN "ratingCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingWeekRank" SET NOT NULL,
ALTER COLUMN "ratingWeekRank" SET DEFAULT 0,
ALTER COLUMN "ratingWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountWeekRank" SET NOT NULL,
ALTER COLUMN "followerCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "followerCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountMonthRank" SET NOT NULL,
ALTER COLUMN "downloadCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountMonthRank" SET NOT NULL,
ALTER COLUMN "favoriteCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountMonthRank" SET NOT NULL,
ALTER COLUMN "ratingCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingMonthRank" SET NOT NULL,
ALTER COLUMN "ratingMonthRank" SET DEFAULT 0,
ALTER COLUMN "ratingMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountMonthRank" SET NOT NULL,
ALTER COLUMN "followerCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "followerCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountYearRank" SET NOT NULL,
ALTER COLUMN "downloadCountYearRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountYearRank" SET NOT NULL,
ALTER COLUMN "favoriteCountYearRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountYearRank" SET NOT NULL,
ALTER COLUMN "ratingCountYearRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingYearRank" SET NOT NULL,
ALTER COLUMN "ratingYearRank" SET DEFAULT 0,
ALTER COLUMN "ratingYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountYearRank" SET NOT NULL,
ALTER COLUMN "followerCountYearRank" SET DEFAULT 0,
ALTER COLUMN "followerCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "downloadCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "downloadCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "downloadCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "favoriteCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "favoriteCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "favoriteCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "ratingCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "ratingCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "ratingAllTimeRank" SET NOT NULL,
ALTER COLUMN "ratingAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "ratingAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "followerCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "followerCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "followerCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerCountDayRank" SET NOT NULL,
ALTER COLUMN "answerCountDayRank" SET DEFAULT 0,
ALTER COLUMN "answerCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerCountWeekRank" SET NOT NULL,
ALTER COLUMN "answerCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "answerCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerCountMonthRank" SET NOT NULL,
ALTER COLUMN "answerCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "answerCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerCountYearRank" SET NOT NULL,
ALTER COLUMN "answerCountYearRank" SET DEFAULT 0,
ALTER COLUMN "answerCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "answerCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "answerCountAllTimeRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerAcceptCountDayRank" SET NOT NULL,
ALTER COLUMN "answerAcceptCountDayRank" SET DEFAULT 0,
ALTER COLUMN "answerAcceptCountDayRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerAcceptCountWeekRank" SET NOT NULL,
ALTER COLUMN "answerAcceptCountWeekRank" SET DEFAULT 0,
ALTER COLUMN "answerAcceptCountWeekRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerAcceptCountMonthRank" SET NOT NULL,
ALTER COLUMN "answerAcceptCountMonthRank" SET DEFAULT 0,
ALTER COLUMN "answerAcceptCountMonthRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerAcceptCountYearRank" SET NOT NULL,
ALTER COLUMN "answerAcceptCountYearRank" SET DEFAULT 0,
ALTER COLUMN "answerAcceptCountYearRank" SET DATA TYPE INTEGER,
ALTER COLUMN "answerAcceptCountAllTimeRank" SET NOT NULL,
ALTER COLUMN "answerAcceptCountAllTimeRank" SET DEFAULT 0,
ALTER COLUMN "answerAcceptCountAllTimeRank" SET DATA TYPE INTEGER,
ADD CONSTRAINT "UserRank_pkey" PRIMARY KEY ("userId");

-- CreateTable
CREATE TABLE "ArticleReport" (
    "articleId" INTEGER NOT NULL,
    "reportId" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "TagsOnArticle" (
    "articleId" INTEGER NOT NULL,
    "tagId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TagsOnArticle_pkey" PRIMARY KEY ("tagId","articleId")
);

-- CreateTable
CREATE TABLE "ArticleReaction" (
    "id" SERIAL NOT NULL,
    "articleId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    "reaction" "ReviewReactions" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ArticleReaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Article" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),
    "nsfw" BOOLEAN NOT NULL DEFAULT false,
    "tosViolation" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "cover" TEXT NOT NULL,
    "publishedAt" TIMESTAMP(3),
    "userId" INTEGER NOT NULL,

    CONSTRAINT "Article_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ArticleReport_reportId_key" ON "ArticleReport"("reportId");

-- CreateIndex
CREATE INDEX "TagsOnArticle_articleId_idx" ON "TagsOnArticle" USING HASH ("articleId");

-- CreateIndex
CREATE UNIQUE INDEX "ArticleReaction_articleId_userId_reaction_key" ON "ArticleReaction"("articleId", "userId", "reaction");

-- CreateIndex
CREATE INDEX "ImageRank_imageId_idx" ON "ImageRank"("imageId");

-- CreateIndex
CREATE INDEX "ImageRank_reactionCountAllTimeRank_idx" ON "ImageRank"("reactionCountAllTimeRank");

-- CreateIndex
CREATE INDEX "ModelRank_modelId_idx" ON "ModelRank"("modelId");

-- CreateIndex
CREATE INDEX "ModelRank_ratingAllTimeRank_idx" ON "ModelRank"("ratingAllTimeRank");

-- CreateIndex
CREATE INDEX "PostRank_postId_idx" ON "PostRank"("postId");

-- CreateIndex
CREATE INDEX "PostRank_reactionCountAllTimeRank_idx" ON "PostRank"("reactionCountAllTimeRank");

-- CreateIndex
CREATE INDEX "TagRank_tagId_idx" ON "TagRank"("tagId");

-- CreateIndex
CREATE UNIQUE INDEX "Thread_articleId_key" ON "Thread"("articleId");

-- CreateIndex
CREATE INDEX "Thread_articleId_idx" ON "Thread" USING HASH ("articleId");

-- CreateIndex
CREATE INDEX "UserRank_userId_idx" ON "UserRank"("userId");

-- CreateIndex
CREATE INDEX "UserRank_leaderboardRank_idx" ON "UserRank"("leaderboardRank");

-- AddForeignKey
ALTER TABLE "ArticleReport" ADD CONSTRAINT "ArticleReport_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ArticleReport" ADD CONSTRAINT "ArticleReport_reportId_fkey" FOREIGN KEY ("reportId") REFERENCES "Report"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagsOnArticle" ADD CONSTRAINT "TagsOnArticle_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagsOnArticle" ADD CONSTRAINT "TagsOnArticle_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Thread" ADD CONSTRAINT "Thread_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ArticleReaction" ADD CONSTRAINT "ArticleReaction_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ArticleReaction" ADD CONSTRAINT "ArticleReaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Article" ADD CONSTRAINT "Article_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ModelRank" ADD CONSTRAINT "ModelRank_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "Model"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ModelVersionRank" ADD CONSTRAINT "ModelVersionRank_modelVersionId_fkey" FOREIGN KEY ("modelVersionId") REFERENCES "ModelVersion"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserRank" ADD CONSTRAINT "UserRank_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagRank" ADD CONSTRAINT "TagRank_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ImageRank" ADD CONSTRAINT "ImageRank_imageId_fkey" FOREIGN KEY ("imageId") REFERENCES "Image"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
DELETE FROM "PostRank" pr WHERE NOT EXISTS (SELECT 1 FROM "Post" p WHERE pr."postId" = p."id");
ALTER TABLE "PostRank" ADD CONSTRAINT "PostRank_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE NO ACTION ON UPDATE CASCADE;
