import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * F-E E5 autogen — coverage for the autogenerated marketplace screenshot
 * fallback service. Pins the load-bearing behaviour:
 *   - the no-dev-screenshots gate (skip when a publisher screenshot exists, or
 *     when an autogenerated one already exists);
 *   - the happy path (POST verify-runner → store → set app_blocks.screenshots
 *     with autogenerated: true);
 *   - failures are swallowed (runner unreachable / non-200 / non-PNG / no
 *     config) and never throw / never write;
 *   - backfill selection (only approved + screenshot-less apps, limit respected,
 *     blockId used as slug).
 *
 * env + Prisma + the storeScreenshots/detectImageType helpers are mocked at the
 * module boundary so this runs offline.
 */

const { mockDbRead, mockDbWrite, mockStore, mockDetect } = vi.hoisted(() => ({
  mockDbRead: {
    appBlock: { findUnique: vi.fn(), findMany: vi.fn() },
  },
  mockDbWrite: {
    appBlock: { update: vi.fn() },
  },
  mockStore: vi.fn(),
  mockDetect: vi.fn(),
}));

vi.mock('~/server/db/client', () => ({ dbRead: mockDbRead, dbWrite: mockDbWrite }));

vi.mock('~/env/server', () => ({
  env: { APPS_DOMAIN: 'civit.ai', BLOCK_SCREENSHOT_RUNNER_URL: 'http://verify-runner:8080' },
}));

vi.mock('~/server/services/blocks/publish-request.service', () => ({
  storeScreenshots: mockStore,
  detectImageType: mockDetect,
}));

import {
  autogenerateScreenshot,
  autogenerateScreenshotIfMissing,
  backfillMissingScreenshots,
  blockPublicUrl,
  hasDevScreenshots,
} from '../autogenerate-screenshot.service';

const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00]);

function mockFetchPng(buf: Buffer = PNG, status = 200) {
  return vi.fn().mockResolvedValue({
    ok: status >= 200 && status < 300,
    status,
    arrayBuffer: async () => buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  mockDetect.mockReturnValue('png'); // default: bytes are a valid PNG
  mockStore.mockResolvedValue([
    { key: 'screenshots/ab1/0.png', index: 0, ext: 'png', contentType: 'image/png' },
  ]);
});

afterEach(() => {
  vi.unstubAllGlobals();
});

// --- pure helpers -----------------------------------------------------------

describe('blockPublicUrl', () => {
  it('builds the per-app subdomain URL', () => {
    expect(blockPublicUrl('my-app', 'civit.ai')).toBe('https://my-app.civit.ai/');
  });
});

describe('hasDevScreenshots', () => {
  it('false for null / empty / non-array', () => {
    expect(hasDevScreenshots(null)).toBe(false);
    expect(hasDevScreenshots([])).toBe(false);
    expect(hasDevScreenshots('nope')).toBe(false);
  });
  it('true when a non-autogenerated record exists', () => {
    expect(hasDevScreenshots([{ key: 'k', index: 0, ext: 'png', contentType: 'image/png' }])).toBe(
      true
    );
  });
  it('false when the only record is autogenerated', () => {
    expect(
      hasDevScreenshots([
        { key: 'k', index: 0, ext: 'png', contentType: 'image/png', autogenerated: true },
      ])
    ).toBe(false);
  });
  it('true when a dev record sits alongside an autogenerated one', () => {
    expect(
      hasDevScreenshots([
        { key: 'a', index: 0, ext: 'png', contentType: 'image/png', autogenerated: true },
        { key: 'b', index: 1, ext: 'png', contentType: 'image/png' },
      ])
    ).toBe(true);
  });
});

// --- autogenerateScreenshot (happy path + failures swallowed) ---------------

describe('autogenerateScreenshot', () => {
  it('captures, stores, and sets app_blocks.screenshots with autogenerated:true', async () => {
    vi.stubGlobal('fetch', mockFetchPng());
    const out = await autogenerateScreenshot('ab1', 'my-app');
    expect(out).toMatchObject({ key: 'screenshots/ab1/0.png', autogenerated: true });
    expect(mockStore).toHaveBeenCalledOnce();
    expect(mockDbWrite.appBlock.update).toHaveBeenCalledOnce();
    const writeArg = mockDbWrite.appBlock.update.mock.calls[0][0];
    expect(writeArg.where).toEqual({ id: 'ab1' });
    expect(writeArg.data.screenshots[0].autogenerated).toBe(true);
  });

  it('POSTs the per-app URL to the runner /screenshot endpoint', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    await autogenerateScreenshot('ab1', 'my-app');
    expect(f).toHaveBeenCalledOnce();
    const [url, opts] = f.mock.calls[0];
    expect(url).toBe('http://verify-runner:8080/screenshot');
    expect(JSON.parse(opts.body).url).toBe('https://my-app.civit.ai/');
  });

  it('returns null + does NOT write when the runner returns non-200', async () => {
    vi.stubGlobal('fetch', mockFetchPng(PNG, 504));
    const out = await autogenerateScreenshot('ab1', 'my-app');
    expect(out).toBeNull();
    expect(mockStore).not.toHaveBeenCalled();
    expect(mockDbWrite.appBlock.update).not.toHaveBeenCalled();
  });

  it('returns null when the runner returns non-PNG bytes', async () => {
    mockDetect.mockReturnValue(null);
    vi.stubGlobal('fetch', mockFetchPng(Buffer.from('not a png')));
    const out = await autogenerateScreenshot('ab1', 'my-app');
    expect(out).toBeNull();
    expect(mockStore).not.toHaveBeenCalled();
  });

  it('swallows a thrown fetch error (never throws, never writes)', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockRejectedValue(new Error('ECONNREFUSED'))
    );
    const out = await autogenerateScreenshot('ab1', 'my-app');
    expect(out).toBeNull();
    expect(mockDbWrite.appBlock.update).not.toHaveBeenCalled();
  });

  it('swallows a store error (never throws)', async () => {
    vi.stubGlobal('fetch', mockFetchPng());
    mockStore.mockRejectedValue(new Error('s3 down'));
    const out = await autogenerateScreenshot('ab1', 'my-app');
    expect(out).toBeNull();
    expect(mockDbWrite.appBlock.update).not.toHaveBeenCalled();
  });
});

// --- autogenerateScreenshotIfMissing (the deploy-success gate) --------------

describe('autogenerateScreenshotIfMissing', () => {
  it('skips (no fetch) when the app already has a dev screenshot', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    mockDbRead.appBlock.findUnique.mockResolvedValue({
      status: 'approved',
      screenshots: [{ key: 'k', index: 0, ext: 'png', contentType: 'image/png' }],
    });
    await autogenerateScreenshotIfMissing('ab1', 'my-app');
    expect(f).not.toHaveBeenCalled();
    expect(mockDbWrite.appBlock.update).not.toHaveBeenCalled();
  });

  it('skips when an autogenerated screenshot already exists', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    mockDbRead.appBlock.findUnique.mockResolvedValue({
      status: 'approved',
      screenshots: [
        { key: 'k', index: 0, ext: 'png', contentType: 'image/png', autogenerated: true },
      ],
    });
    await autogenerateScreenshotIfMissing('ab1', 'my-app');
    expect(f).not.toHaveBeenCalled();
  });

  it('skips a non-approved app', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    mockDbRead.appBlock.findUnique.mockResolvedValue({ status: 'pending', screenshots: null });
    await autogenerateScreenshotIfMissing('ab1', 'my-app');
    expect(f).not.toHaveBeenCalled();
  });

  it('fires autogen when approved with no screenshots', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    mockDbRead.appBlock.findUnique.mockResolvedValue({ status: 'approved', screenshots: null });
    await autogenerateScreenshotIfMissing('ab1', 'my-app');
    expect(f).toHaveBeenCalledOnce();
    expect(mockDbWrite.appBlock.update).toHaveBeenCalledOnce();
  });
});

// --- backfillMissingScreenshots --------------------------------------------

describe('backfillMissingScreenshots', () => {
  it('only attempts approved apps lacking screenshots, uses blockId as slug, respects limit', async () => {
    vi.stubGlobal('fetch', mockFetchPng());
    mockDbRead.appBlock.findMany.mockResolvedValue([
      { id: 'a', blockId: 'slug-a', screenshots: null }, // missing → attempt
      {
        id: 'b',
        blockId: 'slug-b',
        screenshots: [{ key: 'k', index: 0, ext: 'png', contentType: 'image/png' }],
      }, // dev shot → skip
      {
        id: 'c',
        blockId: 'slug-c',
        screenshots: [
          { key: 'k', index: 0, ext: 'png', contentType: 'image/png', autogenerated: true },
        ],
      }, // already autogenerated → skip
      { id: 'd', blockId: 'slug-d', screenshots: [] }, // empty → attempt
    ]);

    const res = await backfillMissingScreenshots({ limit: 1 });
    expect(res.attempted).toBe(1); // limit honoured
    expect(res.succeeded).toBe(1);
    expect(res.results[0]).toEqual({ appBlockId: 'a', slug: 'slug-a', ok: true });
    // findMany filters status='approved' at the DB layer
    expect(mockDbRead.appBlock.findMany.mock.calls[0][0].where).toEqual({ status: 'approved' });
  });

  it('counts a per-app capture failure as failed, does not throw', async () => {
    vi.stubGlobal('fetch', mockFetchPng(PNG, 500));
    mockDbRead.appBlock.findMany.mockResolvedValue([
      { id: 'a', blockId: 'slug-a', screenshots: null },
    ]);
    const res = await backfillMissingScreenshots();
    expect(res.attempted).toBe(1);
    expect(res.succeeded).toBe(0);
    expect(res.failed).toBe(1);
    expect(res.results[0].ok).toBe(false);
  });
});
