import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * F-E E5 autogen — coverage for the (now DISABLED) autogenerated marketplace
 * screenshot service. The standalone `<slug>.<APPS_DOMAIN>` URL only renders a
 * waiting-for-host skeleton, so `BLOCK_SCREENSHOT_AUTOGEN_ENABLED` is false and
 * every entry point is a no-op. These tests pin:
 *   - the pure helpers (`blockPublicUrl`, `hasDevScreenshots`) still work
 *     (retained for a future in-host capture rework);
 *   - `autogenerateScreenshot` returns null and NEVER reaches verify-runner /
 *     store / DB, even when a capture WOULD succeed;
 *   - `autogenerateScreenshotIfMissing` is a no-op (no DB read, no fetch, no
 *     write) even for an approved app with no screenshots;
 *   - `backfillMissingScreenshots` returns an empty result and never queries /
 *     fetches.
 *
 * env + Prisma + the storeScreenshots/detectImageType helpers are mocked at the
 * module boundary so this runs offline.
 */

const { mockDbRead, mockDbWrite, mockStore, mockDetect } = vi.hoisted(() => ({
  mockDbRead: {
    appBlock: { findUnique: vi.fn(), findMany: vi.fn() },
  },
  mockDbWrite: {
    appBlock: { update: vi.fn() },
  },
  mockStore: vi.fn(),
  mockDetect: vi.fn(),
}));

vi.mock('~/server/db/client', () => ({ dbRead: mockDbRead, dbWrite: mockDbWrite }));

vi.mock('~/env/server', () => ({
  env: { APPS_DOMAIN: 'civit.ai', BLOCK_SCREENSHOT_RUNNER_URL: 'http://verify-runner:8080' },
}));

vi.mock('~/server/services/blocks/publish-request.service', () => ({
  storeScreenshots: mockStore,
  detectImageType: mockDetect,
}));

import {
  autogenerateScreenshot,
  autogenerateScreenshotIfMissing,
  backfillMissingScreenshots,
  blockPublicUrl,
  hasDevScreenshots,
  BLOCK_SCREENSHOT_AUTOGEN_ENABLED,
} from '../autogenerate-screenshot.service';

const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00]);

function mockFetchPng(buf: Buffer = PNG, status = 200) {
  return vi.fn().mockResolvedValue({
    ok: status >= 200 && status < 300,
    status,
    arrayBuffer: async () => buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  mockDetect.mockReturnValue('png'); // default: bytes are a valid PNG
  mockStore.mockResolvedValue([
    { key: 'screenshots/ab1/0.png', index: 0, ext: 'png', contentType: 'image/png' },
  ]);
});

afterEach(() => {
  vi.unstubAllGlobals();
});

// --- pure helpers -----------------------------------------------------------

describe('blockPublicUrl', () => {
  it('builds the per-app subdomain URL', () => {
    expect(blockPublicUrl('my-app', 'civit.ai')).toBe('https://my-app.civit.ai/');
  });
});

describe('hasDevScreenshots', () => {
  it('false for null / empty / non-array', () => {
    expect(hasDevScreenshots(null)).toBe(false);
    expect(hasDevScreenshots([])).toBe(false);
    expect(hasDevScreenshots('nope')).toBe(false);
  });
  it('true when a non-autogenerated record exists', () => {
    expect(hasDevScreenshots([{ key: 'k', index: 0, ext: 'png', contentType: 'image/png' }])).toBe(
      true
    );
  });
  it('false when the only record is autogenerated', () => {
    expect(
      hasDevScreenshots([
        { key: 'k', index: 0, ext: 'png', contentType: 'image/png', autogenerated: true },
      ])
    ).toBe(false);
  });
  it('true when a dev record sits alongside an autogenerated one', () => {
    expect(
      hasDevScreenshots([
        { key: 'a', index: 0, ext: 'png', contentType: 'image/png', autogenerated: true },
        { key: 'b', index: 1, ext: 'png', contentType: 'image/png' },
      ])
    ).toBe(true);
  });
});

// --- disabled kill-switch ---------------------------------------------------

describe('BLOCK_SCREENSHOT_AUTOGEN_ENABLED', () => {
  it('is disabled (false) — standalone-URL autogen only ever captures skeletons', () => {
    expect(BLOCK_SCREENSHOT_AUTOGEN_ENABLED).toBe(false);
  });
});

// --- autogenerateScreenshot (DISABLED: no-op, never reaches the runner) ------

describe('autogenerateScreenshot (disabled)', () => {
  it('returns null and NEVER fetches / stores / writes, even when a capture would succeed', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    const out = await autogenerateScreenshot('ab1', 'my-app');
    expect(out).toBeNull();
    expect(f).not.toHaveBeenCalled();
    expect(mockStore).not.toHaveBeenCalled();
    expect(mockDbWrite.appBlock.update).not.toHaveBeenCalled();
  });
});

// --- autogenerateScreenshotIfMissing (DISABLED: pure no-op) ------------------

describe('autogenerateScreenshotIfMissing (disabled)', () => {
  it('is a no-op even for an approved app with no screenshots (no DB read, no fetch, no write)', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    // Would previously fire autogen — now must not even read the row.
    mockDbRead.appBlock.findUnique.mockResolvedValue({ status: 'approved', screenshots: null });
    await autogenerateScreenshotIfMissing('ab1', 'my-app');
    expect(mockDbRead.appBlock.findUnique).not.toHaveBeenCalled();
    expect(f).not.toHaveBeenCalled();
    expect(mockDbWrite.appBlock.update).not.toHaveBeenCalled();
  });
});

// --- backfillMissingScreenshots (DISABLED: empty result, no queries) --------

describe('backfillMissingScreenshots (disabled)', () => {
  it('returns an empty result without querying candidates or fetching', async () => {
    const f = mockFetchPng();
    vi.stubGlobal('fetch', f);
    const res = await backfillMissingScreenshots({ limit: 10 });
    expect(res).toEqual({ attempted: 0, succeeded: 0, failed: 0, results: [] });
    expect(mockDbRead.appBlock.findMany).not.toHaveBeenCalled();
    expect(f).not.toHaveBeenCalled();
  });
});
