import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

// This file guards a DELIBERATE DIVERGENCE FROM UPSTREAM shadcn, living in a tree the package
// README says is regenerated by `--overwrite` and must not be hand-edited. That rule exists
// because a regen silently reverts local edits -- so the point of this test is to make that
// revert LOUD. `npx shadcn-svelte add tabs --overwrite`, or
// `packages/civitai-ui/scripts/add-components.mjs --force`, restores upstream's
// `inline-flex h-9 w-fit` and deletes the comment explaining why it must not come back; without
// this test that lands with a green suite and reintroduces page-level horizontal scroll in
// apps/moderator, where all 11 <TabsList> call sites pass no classes of their own.
//
// It asserts the SOURCE rather than rendered output on purpose: a regen overwrites the file, so
// the file is the surface the hazard acts on. (The package's vitest env is `node` with no DOM,
// so rendering is not available here anyway.)

const source = readFileSync(fileURLToPath(new URL('./tabs-list.svelte', import.meta.url)), 'utf8');

/** The literal base class string: the first argument to `cn(` in the component. */
function baseClassString(): string {
  const match = source.match(/cn\(\s*(["'])([\s\S]*?)\1/);
  if (!match) throw new Error('could not find the cn(...) base class string in tabs-list.svelte');
  return match[2];
}

/** A class present as its own whitespace-delimited token, or under a variant prefix (`sm:`). */
function hasClass(token: string): RegExp {
  return new RegExp(`(^|\\s)([a-z0-9-]+:)*${token}(\\s|$)`);
}

describe('TabsList base classes', () => {
  // Positive control: if the read or the extraction silently returned nothing, every
  // `not.toMatch` below would pass vacuously and this guard would be wired to nothing.
  // Pins `inline-flex` rather than a palette token, so a theme change does not fail a test
  // named "reads a non-empty base class string" and read as a broken test.
  it('reads a non-empty base class string out of the real component', () => {
    expect(source).toContain('data-slot="tabs-list"');
    expect(baseClassString().length).toBeGreaterThan(40);
    expect(baseClassString()).toMatch(hasClass('inline-flex'));
  });

  it('allows the row to wrap, so w-fit can clamp to the container', () => {
    // Without this the nowrap triggers make min-content == max-content, w-fit cannot clamp, and
    // the list spills out of every overflow:visible ancestor as page-level horizontal scroll.
    expect(baseClassString()).toMatch(hasClass('flex-wrap'));
    // `flex-wrap flex-nowrap` keeps both tokens, and tailwind-merge lets the LATER one win --
    // so asserting flex-wrap's presence alone is satisfied while wrapping is off.
    expect(baseClassString()).not.toMatch(hasClass('flex-nowrap'));
  });

  it('keeps w-fit, the width rule the clamp actually depends on', () => {
    // Swapping w-fit for w-max restores the defect exactly: max-content does not clamp, so the
    // list returns to its full intrinsic width no matter how the height behaves.
    expect(baseClassString()).toMatch(hasClass('w-fit'));
  });

  it('carries no fixed or capped height, which a wrapped row would overflow', () => {
    // Structural, not spelled: ANY numeric or arbitrary height -- `h-9`, `h-[36px]`, `max-h-9`,
    // bare or variant-prefixed -- pins the box while the rows keep growing. `h-auto` must also
    // still be present, because tailwind-merge resolves a later height against it.
    expect(baseClassString()).toMatch(hasClass('h-auto'));
    expect(baseClassString()).not.toMatch(/(^|\s)([a-z0-9-]+:)*(max-)?h-(\d|\[)/);
  });
});
