import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

// This file guards a DELIBERATE DIVERGENCE FROM UPSTREAM shadcn, living in a tree the package
// README says is regenerated by `--overwrite` and must not be hand-edited. That rule exists
// because a regen silently reverts local edits -- so the point of this test is to make that
// revert LOUD. `npx shadcn-svelte add tabs --overwrite`, or
// `packages/civitai-ui/scripts/add-components.mjs --force`, restores upstream's
// `inline-flex h-9 w-fit` and deletes the comment explaining why it must not come back; without
// this test that lands with a green suite and reintroduces page-level horizontal scroll in
// apps/moderator, where all 11 <TabsList> call sites pass no classes of their own.
//
// It asserts the SOURCE rather than rendered output on purpose: a regen overwrites the file, so
// the file is the surface the hazard acts on. (The package's vitest env is `node` with no DOM,
// so rendering is not available here anyway.)

const source = readFileSync(fileURLToPath(new URL('./tabs-list.svelte', import.meta.url)), 'utf8');

/** The literal base class string: the first argument to `cn(` in the component. */
function baseClassString(): string {
  const match = source.match(/cn\(\s*(["'])([\s\S]*?)\1/);
  if (!match) throw new Error('could not find the cn(...) base class string in tabs-list.svelte');
  return match[2];
}

/**
 * A class present as its own whitespace-delimited token, under any variant prefix.
 * `\S+:` rather than `([a-z0-9-]+:)*` because Tailwind v4 variants are not alphanumeric --
 * `data-[state=active]:`, `@md:`, `[&>*]:`, `max-[600px]:` all appear in this component set.
 * The token is escaped: an unescaped `p-[3px]` becomes a character class and silently matches
 * `p-3` while NOT matching the real token.
 */
function hasClass(token: string): RegExp {
  const escaped = token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(^|\\s)(\\S+:)?${escaped}(\\s|$)`);
}

/**
 * Any height that PINS the box while wrapped rows keep growing: numeric or arbitrary, bare or
 * under any variant prefix, `max-` or not -- and `size-*`, which sets height AND width at once.
 * Deliberately does NOT match `h-auto`, `h-full`, `max-h-none` or `min-h-*` (a minimum does not
 * pin growth).
 */
const PINS_HEIGHT = /(^|\s)(\S+:)?(max-)?(h|size)-(\d|\[)/;

describe('TabsList base classes', () => {
  // Positive control: if the read or the extraction silently returned nothing, every
  // `not.toMatch` below would pass vacuously and this guard would be wired to nothing.
  // Pins `inline-flex` rather than a palette token, so a theme change does not fail a test
  // named "reads a non-empty base class string" and read as a broken test.
  it('reads a non-empty base class string out of the real component', () => {
    expect(source).toContain('data-slot="tabs-list"');
    expect(baseClassString().length).toBeGreaterThan(40);
    expect(baseClassString()).toMatch(hasClass('inline-flex'));
  });

  it('allows the row to wrap, so w-fit can clamp to the container', () => {
    // Without this the nowrap triggers make min-content == max-content, w-fit cannot clamp, and
    // the list spills out of every overflow:visible ancestor as page-level horizontal scroll.
    expect(baseClassString()).toMatch(hasClass('flex-wrap'));
    // `flex-wrap flex-nowrap` keeps both tokens, and tailwind-merge lets the LATER one win --
    // so asserting flex-wrap's presence alone is satisfied while wrapping is off.
    expect(baseClassString()).not.toMatch(hasClass('flex-nowrap'));
  });

  it('keeps w-fit, the width rule the clamp actually depends on', () => {
    // Swapping w-fit for w-max restores the defect exactly: max-content does not clamp, so the
    // list returns to its full intrinsic width no matter how the height behaves.
    // A `size-*` token also drops w-fit under tailwind-merge; PINS_HEIGHT below is what catches
    // that, since this assertion reads the source token and `w-fit` is still spelled there.
    expect(baseClassString()).toMatch(hasClass('w-fit'));
  });

  it('carries no fixed or capped height, which a wrapped row would overflow', () => {
    // Both assertions are load-bearing and neither implies the other. `h-auto` being present is
    // NOT protective -- tailwind-merge resolving a later height against it is exactly what
    // REMOVES it -- so the negative assertion below is required, not redundant with this one.
    expect(baseClassString()).toMatch(hasClass('h-auto'));
    expect(baseClassString()).not.toMatch(PINS_HEIGHT);
  });
});
