import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import {
  recordImpression,
  flushImpressions,
  getImpressionSurface,
  __impressionBufferTestHooks as hooks,
} from '~/components/TrackView/impressionBuffer';
import { __trackBufferTestHooks as trackHooks } from '~/components/TrackView/trackEventBuffer';
import { IMPRESSION_ENTITIES_MAX } from '~/server/schema/track.schema';

/**
 * Coverage for the impression coalescing layer.
 *
 * The whole feature's load profile lives here: impressions are generated by
 * scrolling, and the only thing standing between that and the request rate is
 * this buffer's set semantics and array batching. Every assertion below is about
 * a property that, if it regressed, would show up as a traffic incident rather
 * than as a wrong number — so they are written to fail loudly on the specific
 * mutation that would cause it (one event per entity, a repeat re-sent, a fast
 * timer armed).
 *
 * Runs in the node env with a hand-rolled fake DOM, mirroring the sibling
 * trackEventBuffer suite, so the flush triggers are deterministic.
 */

const { FLUSH_INTERVAL_MS, FLUSH_AT_SIZE, SEEN_CAP } = hooks.constants;

function makeFakeDom(pathname = '/images') {
  const listeners: Record<string, Array<(e?: unknown) => void>> = {};
  const add = (type: string, cb: (e?: unknown) => void) => {
    (listeners[type] ??= []).push(cb);
  };
  const doc = {
    visibilityState: 'visible' as 'visible' | 'hidden',
    addEventListener: add,
  };
  const win = { addEventListener: add, location: { pathname } };
  const fire = (type: string) => (listeners[type] ?? []).forEach((cb) => cb());
  return { doc, win, fire };
}

let sendBeacon: ReturnType<typeof vi.fn>;
let fetchMock: ReturnType<typeof vi.fn>;
let dom: ReturnType<typeof makeFakeDom>;

beforeEach(() => {
  hooks.reset();
  trackHooks.reset();
  vi.useFakeTimers();

  dom = makeFakeDom();
  sendBeacon = vi.fn(() => true);
  fetchMock = vi.fn(() => Promise.resolve({ ok: true }));

  vi.stubGlobal('window', dom.win);
  vi.stubGlobal('document', dom.doc);
  vi.stubGlobal('navigator', { sendBeacon });
  vi.stubGlobal('fetch', fetchMock);
});

afterEach(() => {
  hooks.reset();
  trackHooks.reset();
  vi.useRealTimers();
  vi.unstubAllGlobals();
});

function sentEvents() {
  // The impression buffer hands events to the shared buffer; forcing that
  // buffer's own flush is what puts them on the wire.
  trackHooks.flush();
  const bodies = fetchMock.mock.calls.map(([, init]) => JSON.parse((init as any).body));
  return bodies.flat();
}

describe('impression buffer', () => {
  it('collapses many entities into ONE event, not one event per entity', () => {
    for (let i = 1; i <= 40; i++) recordImpression('Image', i);
    flushImpressions();

    const events = sentEvents();
    expect(events).toHaveLength(1);
    expect(events[0].kind).toBe('impression');
    expect(events[0].data.entities).toHaveLength(40);
  });

  it('records a repeated entity once per session', () => {
    recordImpression('Image', 1);
    recordImpression('Image', 1);
    recordImpression('Image', 1);
    expect(hooks.pendingCount()).toBe(1);

    flushImpressions();
    // Seen again AFTER the flush — the dedupe is session-scoped, not
    // flush-scoped, so scrolling back up over a feed must add nothing.
    recordImpression('Image', 1);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('distinguishes entities of the same id but different type', () => {
    recordImpression('Image', 7);
    recordImpression('Model', 7);
    flushImpressions();

    const [event] = sentEvents();
    expect(event.data.entities).toEqual([
      { entityType: 'Image', entityId: 7 },
      { entityType: 'Model', entityId: 7 },
    ]);
  });

  it('does not flush on a short timer — the interval is the load ceiling', () => {
    recordImpression('Image', 1);

    // The shared telemetry buffer's own interval is 3s. An impression that armed
    // THAT timer would put the impression rate back on the wire at 20x this one's
    // cadence, which is the exact failure this interval exists to prevent.
    vi.advanceTimersByTime(FLUSH_INTERVAL_MS - 1);
    expect(hooks.pendingCount()).toBe(1);
    expect(fetchMock).not.toHaveBeenCalled();

    vi.advanceTimersByTime(1);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('flushes early at the size cap', () => {
    for (let i = 1; i <= FLUSH_AT_SIZE; i++) recordImpression('Image', i);
    expect(hooks.pendingCount()).toBe(0);

    const events = sentEvents();
    expect(events).toHaveLength(1);
    expect(events[0].data.entities).toHaveLength(FLUSH_AT_SIZE);
  });

  it('splits a surface larger than the per-event cap into multiple events', () => {
    // Reaching past the cap without tripping the size flush: record under the cap,
    // flush manually, then verify a single oversized surface would still split.
    const oversized = IMPRESSION_ENTITIES_MAX + 10;
    for (let i = 1; i <= oversized; i++) recordImpression('Image', i);
    // The size cap already flushed the first full event; drain the remainder.
    flushImpressions();

    const events = sentEvents();
    const total = events.reduce((sum, e) => sum + e.data.entities.length, 0);
    expect(total).toBe(oversized);
    for (const event of events) {
      expect(event.data.entities.length).toBeLessThanOrEqual(IMPRESSION_ENTITIES_MAX);
    }
  });

  it('keys every entity in a batch to the same session token', () => {
    recordImpression('Image', 1);
    recordImpression('Model', 2);
    flushImpressions();
    const [first] = sentEvents();

    fetchMock.mockClear();
    recordImpression('Image', 3);
    flushImpressions();
    const [second] = sentEvents();

    expect(first.data.sessionKey).toBeTruthy();
    // Stable for the life of the tab — that stability is what lets a redelivered
    // batch be recognised as a duplicate at read time.
    expect(second.data.sessionKey).toBe(first.data.sessionKey);
  });

  it('flushes via sendBeacon when the tab is hidden', () => {
    recordImpression('Image', 1);
    dom.doc.visibilityState = 'hidden';
    dom.fire('visibilitychange');

    expect(sendBeacon).toHaveBeenCalledTimes(1);
    const [, blob] = sendBeacon.mock.calls[0];
    expect(blob).toBeInstanceOf(Blob);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('flushes via sendBeacon on pagehide', () => {
    recordImpression('Image', 1);
    dom.fire('pagehide');

    expect(sendBeacon).toHaveBeenCalledTimes(1);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('bounds the session dedupe set rather than growing it forever', () => {
    for (let i = 1; i <= SEEN_CAP + 1; i++) recordImpression('Image', i);
    expect(hooks.seenCount()).toBeLessThanOrEqual(SEEN_CAP);
  });

  it('groups by surface when the tab moves between feeds', () => {
    recordImpression('Image', 1);
    dom.win.location.pathname = '/models';
    recordImpression('Model', 2);
    flushImpressions();

    const events = sentEvents();
    const bySurface = Object.fromEntries(events.map((e) => [e.data.surface, e.data.entities]));
    expect(bySurface.images).toEqual([{ entityType: 'Image', entityId: 1 }]);
    expect(bySurface.models).toEqual([{ entityType: 'Model', entityId: 2 }]);
  });
});

describe('getImpressionSurface', () => {
  it.each([
    ['/', 'home'],
    ['/images', 'images'],
    ['/videos', 'videos'],
    ['/models/123/some-model', 'models'],
    ['/search/images', 'search'],
    ['/user/someone', 'user'],
  ])('maps %s to %s', (pathname, expected) => {
    expect(getImpressionSurface(pathname)).toBe(expected);
  });

  it('collapses anything unrecognised to "other" so the column cannot widen', () => {
    expect(getImpressionSurface('/some-new-page')).toBe('other');
    expect(getImpressionSurface('/' + 'x'.repeat(200))).toBe('other');
  });
});
