import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import {
  recordImpression,
  flushImpressions,
  getImpressionSurface,
  __impressionBufferTestHooks as hooks,
} from '~/components/TrackView/impressionBuffer';
import { __trackBufferTestHooks as trackHooks } from '~/components/TrackView/trackEventBuffer';
import { __trackImpressionTestHooks as dwellHooks } from '~/components/TrackView/useTrackImpression';
import { IMPRESSION_ENTITIES_MAX, IMPRESSION_SURFACES } from '~/server/schema/track.schema';

/**
 * Coverage for the impression coalescing layer.
 *
 * The whole feature's load profile lives here: impressions are generated by
 * scrolling, and the only thing standing between that and the request rate is
 * this buffer's set semantics and array batching. Every assertion below is about
 * a property that, if it regressed, would show up as a traffic incident rather
 * than as a wrong number — so they are written to fail loudly on the specific
 * mutation that would cause it (one event per entity, a repeat re-sent, a fast
 * timer armed).
 *
 * Runs in the node env with a hand-rolled fake DOM, mirroring the sibling
 * trackEventBuffer suite, so the flush triggers are deterministic.
 */

// 🔴 Read the module's constants, then pin them against LITERALS below.
//
// A test that only reads `hooks.constants` and asserts relative to it moves its
// own goalposts: change FLUSH_INTERVAL_MS to 3000 and "does not flush before the
// interval" still passes, having tested nothing. These three numbers ARE the
// feature's load profile, so the literal is the assertion.
const { FLUSH_INTERVAL_MS, FLUSH_AT_SIZE, SEEN_CAP } = hooks.constants;

describe('load-critical constants', () => {
  it('pins the flush interval — this number is the steady-state request rate', () => {
    // N actively scrolling tabs cost N/90 requests per second. Dropping this to
    // the shared buffer's 3s multiplies the site's telemetry request rate by 30
    // for identical information. Change it only with a sizing number to match.
    expect(FLUSH_INTERVAL_MS).toBe(90_000);
  });

  it('pins the per-event entity cap', () => {
    expect(FLUSH_AT_SIZE).toBe(250);
  });

  it('pins the session dedupe ceiling', () => {
    expect(SEEN_CAP).toBe(20_000);
  });
});

function makeFakeDom(pathname = '/images') {
  const listeners: Record<string, Array<(e?: unknown) => void>> = {};
  const add = (type: string, cb: (e?: unknown) => void) => {
    (listeners[type] ??= []).push(cb);
  };
  const doc = {
    visibilityState: 'visible' as 'visible' | 'hidden',
    addEventListener: add,
  };
  const win = { addEventListener: add, location: { pathname } };
  const fire = (type: string) => (listeners[type] ?? []).forEach((cb) => cb());
  return { doc, win, fire };
}

let sendBeacon: ReturnType<typeof vi.fn>;
let fetchMock: ReturnType<typeof vi.fn>;
let dom: ReturnType<typeof makeFakeDom>;

beforeEach(() => {
  hooks.reset();
  trackHooks.reset();
  vi.useFakeTimers();

  dom = makeFakeDom();
  sendBeacon = vi.fn(() => true);
  fetchMock = vi.fn(() => Promise.resolve({ ok: true }));

  vi.stubGlobal('window', dom.win);
  vi.stubGlobal('document', dom.doc);
  vi.stubGlobal('navigator', { sendBeacon });
  vi.stubGlobal('fetch', fetchMock);
});

afterEach(() => {
  hooks.reset();
  trackHooks.reset();
  vi.useRealTimers();
  vi.unstubAllGlobals();
});

function sentEvents() {
  // The impression buffer hands events to the shared buffer; forcing that
  // buffer's own flush is what puts them on the wire.
  trackHooks.flush();
  const bodies = fetchMock.mock.calls.map(([, init]) => JSON.parse((init as any).body));
  return bodies.flat();
}

describe('impression buffer', () => {
  it('collapses many entities into ONE event, not one event per entity', () => {
    for (let i = 1; i <= 40; i++) recordImpression('Image', i);
    flushImpressions();

    const events = sentEvents();
    expect(events).toHaveLength(1);
    expect(events[0].kind).toBe('impression');
    expect(events[0].data.entities).toHaveLength(40);
  });

  it('records a repeated entity once per session', () => {
    recordImpression('Image', 1);
    recordImpression('Image', 1);
    recordImpression('Image', 1);
    expect(hooks.pendingCount()).toBe(1);

    flushImpressions();
    // Seen again AFTER the flush — the dedupe is session-scoped, not
    // flush-scoped, so scrolling back up over a feed must add nothing.
    recordImpression('Image', 1);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('distinguishes entities of the same id but different type', () => {
    recordImpression('Image', 7);
    recordImpression('Model', 7);
    flushImpressions();

    const [event] = sentEvents();
    expect(event.data.entities).toEqual([
      { entityType: 'Image', entityId: 7 },
      { entityType: 'Model', entityId: 7 },
    ]);
  });

  it('does not flush on a short timer — the interval is the load ceiling', () => {
    recordImpression('Image', 1);

    // The shared telemetry buffer's own interval is 3s. An impression that armed
    // THAT timer would put the impression rate back on the wire at 20x this one's
    // cadence, which is the exact failure this interval exists to prevent.
    vi.advanceTimersByTime(FLUSH_INTERVAL_MS - 1);
    expect(hooks.pendingCount()).toBe(1);
    expect(fetchMock).not.toHaveBeenCalled();

    vi.advanceTimersByTime(1);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('flushes early at the size cap', () => {
    for (let i = 1; i <= FLUSH_AT_SIZE; i++) recordImpression('Image', i);
    expect(hooks.pendingCount()).toBe(0);

    const events = sentEvents();
    expect(events).toHaveLength(1);
    expect(events[0].data.entities).toHaveLength(FLUSH_AT_SIZE);
  });

  it('splits a surface larger than the per-event cap into multiple events', () => {
    // Reaching past the cap without tripping the size flush: record under the cap,
    // flush manually, then verify a single oversized surface would still split.
    const oversized = IMPRESSION_ENTITIES_MAX + 10;
    for (let i = 1; i <= oversized; i++) recordImpression('Image', i);
    // The size cap already flushed the first full event; drain the remainder.
    flushImpressions();

    const events = sentEvents();
    const total = events.reduce((sum, e) => sum + e.data.entities.length, 0);
    expect(total).toBe(oversized);
    for (const event of events) {
      expect(event.data.entities.length).toBeLessThanOrEqual(IMPRESSION_ENTITIES_MAX);
    }
  });

  it('keys every entity in a batch to the same session token', () => {
    recordImpression('Image', 1);
    recordImpression('Model', 2);
    flushImpressions();
    const [first] = sentEvents();

    fetchMock.mockClear();
    recordImpression('Image', 3);
    flushImpressions();
    const [second] = sentEvents();

    expect(first.data.sessionKey).toBeTruthy();
    // Stable for the life of the tab — that stability is what lets a redelivered
    // batch be recognised as a duplicate at read time.
    expect(second.data.sessionKey).toBe(first.data.sessionKey);
  });

  it('flushes via sendBeacon when the tab is hidden', () => {
    recordImpression('Image', 1);
    dom.doc.visibilityState = 'hidden';
    dom.fire('visibilitychange');

    expect(sendBeacon).toHaveBeenCalledTimes(1);
    const [, blob] = sendBeacon.mock.calls[0];
    expect(blob).toBeInstanceOf(Blob);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('flushes via sendBeacon on pagehide', () => {
    recordImpression('Image', 1);
    dom.fire('pagehide');

    expect(sendBeacon).toHaveBeenCalledTimes(1);
    expect(hooks.pendingCount()).toBe(0);
  });

  it('bounds the session dedupe set rather than growing it forever', () => {
    for (let i = 1; i <= SEEN_CAP + 1; i++) recordImpression('Image', i);
    expect(hooks.seenCount()).toBeLessThanOrEqual(SEEN_CAP);
  });

  it('groups by surface when the tab moves between feeds', () => {
    recordImpression('Image', 1);
    dom.win.location.pathname = '/models';
    recordImpression('Model', 2);
    flushImpressions();

    const events = sentEvents();
    const bySurface = Object.fromEntries(events.map((e) => [e.data.surface, e.data.entities]));
    expect(bySurface.images).toEqual([{ entityType: 'Image', entityId: 1 }]);
    expect(bySurface.models).toEqual([{ entityType: 'Model', entityId: 2 }]);
  });
});

describe('getImpressionSurface', () => {
  it.each([
    ['/', 'home'],
    ['/images', 'images'],
    ['/videos', 'videos'],
    ['/models/123/some-model', 'models'],
    ['/search/images', 'search'],
    ['/user/someone', 'user'],
    ['/hubs/12/some-hub', 'hubs'],
    ['/challenges/5', 'challenges'],
  ])('maps %s to %s', (pathname, expected) => {
    expect(getImpressionSurface(pathname)).toBe(expected);
  });

  it('pins the surface list, so a page never falls to "other" unnoticed', () => {
    // Removing a value is silent: its pages relabel to 'other' and every test
    // derived from the list follows along. The literal is the assertion.
    expect(IMPRESSION_SURFACES).toEqual([
      'home',
      'images',
      'videos',
      'posts',
      'models',
      'articles',
      'collections',
      'bounties',
      'search',
      'user',
      'hubs',
      'challenges',
      '3d-models',
      'ecosystems',
      'tag',
      'tools',
      'comics',
      'crucibles',
      'events',
      'other',
    ]);
  });

  it.each(IMPRESSION_SURFACES.filter((s) => s !== 'home' && s !== 'other'))(
    'maps /%s/123 to its own surface',
    (surface) => {
      expect(getImpressionSurface(`/${surface}/123`)).toBe(surface);
    }
  );

  it('collapses anything unrecognised to "other" so the column cannot widen', () => {
    expect(getImpressionSurface('/some-new-page')).toBe('other');
    expect(getImpressionSurface('/' + 'x'.repeat(200))).toBe('other');
  });
});

describe('dwell timer surface', () => {
  type State = Parameters<typeof dwellHooks.armDwell>[2];
  const newState = (): State => ({ targets: [{ entityType: 'Image', entityId: 9 }], timer: null });
  const registryFor = (element: Element, state: State) => ({
    observer: { unobserve: () => undefined } as unknown as IntersectionObserver,
    elements: new Map([[element, state]]),
    intersecting: new Set([element]),
  });

  it('labels an impression with the page the dwell STARTED on, not the one it ends on', () => {
    // Opening the image-detail dialog rewrites the URL to /images/<id> while the
    // feed underneath stays mounted and intersecting. A surface read when the
    // timer fires would credit a hub's cards to the /images feed.
    dom.win.location.pathname = '/hubs/12';
    const element = {} as Element;
    const state = newState();
    const registry = registryFor(element, state);

    dwellHooks.armDwell(registry, element, state);
    dom.win.location.pathname = '/images/9';
    vi.advanceTimersByTime(dwellHooks.DWELL_MS);
    flushImpressions();

    const [event] = sentEvents();
    expect(event.data.surface).toBe('hubs');
    expect(event.data.entities).toEqual([{ entityType: 'Image', entityId: 9 }]);
  });

  it('keeps the first surface when a tab switch re-arms the dwell under the dialog', () => {
    // Hidden tabs drop the timer and re-arm it on return. With the image-detail
    // dialog open by then, a fresh read would say 'images'.
    dom.win.location.pathname = '/hubs/12';
    const element = {} as Element;
    const state = newState();
    const registry = registryFor(element, state);

    dwellHooks.armDwell(registry, element, state);
    dom.win.location.pathname = '/images/9';
    dwellHooks.disarmDwell(state);
    dwellHooks.armDwell(registry, element, state);
    vi.advanceTimersByTime(dwellHooks.DWELL_MS);
    flushImpressions();

    expect(sentEvents()[0].data.surface).toBe('hubs');
  });
});
