#!/usr/bin/env node
/**
 * Shared yardstick for test-suite perf work.
 *
 * A full unit run costs ~3.5 minutes and has to be serialised against every other agent on the
 * box, which makes it useless as an edit->measure loop. This runs a FIXED subset instead, at a
 * fixed worker count, so two measurements taken hours apart by different people are comparable.
 *
 *   node scripts/test-perf/bench.mjs --label before
 *   node scripts/test-perf/bench.mjs --label after --no-isolate
 *
 * The subset is `.test-perf/subset.txt`, generated by `--make-subset` from the static inventory:
 * a stratified sample across closure sizes, so slimming one fat chain shows up rather than being
 * averaged away.
 *
 * Everything after `--` is passed to vitest untouched.
 */
import { spawnSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const SUBSET = path.join(repoRoot, '.test-perf/subset.txt');

const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = argv.indexOf(`--${name}`);
  return i === -1 ? fallback : argv[i + 1];
};

if (argv.includes('--make-subset')) {
  const inv = JSON.parse(readFileSync(path.join(repoRoot, '.test-perf/inventory.json'), 'utf8'));
  // Stratified by closure size: the heavy tail is where the import cost lives, but a subset that
  // is ONLY heavy files would report a win from slimming that the full suite never sees.
  const sorted = [...inv.files].sort((a, b) => b.graphModules - a.graphModules);
  const take = (arr, n) => arr.filter((_, i) => i % Math.max(1, Math.floor(arr.length / n)) === 0).slice(0, n);
  const heavy = take(sorted.slice(0, 150), 30);
  const mid = take(sorted.slice(150, 500), 30);
  const light = take(sorted.slice(500), 30);
  const files = [...heavy, ...mid, ...light].map((f) => f.file);
  mkdirSync(path.dirname(SUBSET), { recursive: true });
  writeFileSync(SUBSET, files.join('\n') + '\n');
  console.log(`wrote ${files.length} files to .test-perf/subset.txt`);
  console.log(
    `closure modules: heavy ${heavy[0].graphModules}..${heavy.at(-1).graphModules}, ` +
      `mid ${mid[0].graphModules}..${mid.at(-1).graphModules}, light ${light[0].graphModules}..${light.at(-1).graphModules}`
  );
  process.exit(0);
}

if (!existsSync(SUBSET)) {
  console.error('No .test-perf/subset.txt — run: node scripts/test-perf/bench.mjs --make-subset');
  process.exit(2);
}

const label = flag('label', 'bench');
const workers = flag('workers', '4');
const passthrough = argv.includes('--') ? argv.slice(argv.indexOf('--') + 1) : [];
const extra = argv.filter((a) => a === '--no-isolate' || a.startsWith('--pool='));

const files = readFileSync(SUBSET, 'utf8').split('\n').map((s) => s.trim()).filter(Boolean);

const bin = path.join(repoRoot, 'node_modules/.bin', process.platform === 'win32' ? 'vitest.cmd' : 'vitest');
const args = [
  'run',
  '--project',
  'unit*',
  `--max-workers=${workers}`,
  '--reporter=default',
  `--reporter=${path.join(repoRoot, 'scripts/test-perf/reporter.mjs').replace(/\\/g, '/')}`,
  ...extra,
  ...passthrough,
  ...files,
];

const started = Date.now();
const res = spawnSync(bin, args, {
  cwd: repoRoot,
  stdio: ['ignore', 'inherit', 'inherit'],
  shell: process.platform === 'win32',
  env: { ...process.env, TESTPERF_LABEL: label },
});
console.log(`\n[bench] ${label} exited ${res.status} in ${((Date.now() - started) / 1000).toFixed(1)}s`);
process.exit(res.status ?? 1);
