-- One row per Blocklist type, enforced by the database.
--
-- Nothing prevented a second row before this: `upsertBlocklist` takes a row lock, but `FOR UPDATE`
-- locks nothing when it matches nothing, so two concurrent first-inserts for a type with no row
-- both reach the create branch. That is not hypothetical for `EmailDomainSuffix`, which ships with
-- zero rows and whose first entry is added by hand.
--
-- It matters because the readers disagree about which row wins: the main app pins
-- `orderBy: { id: 'asc' }`, while the auth hub reads with `executeTakeFirst()` and no ordering. A
-- duplicate would let the hub enforce a different list than the main app on the signup path.
--
-- Verified on production 2026-09-09 before writing this: every existing type has exactly one row
-- (EmailDomain, Link, LinkDomain, MessagePattern, UsernamePartial, NegativeBenignPhrase,
-- PromptBenignPhrase, ProfanityBenignWord), so the index can be created without a merge first.
--
-- CONCURRENTLY so the create does not hold a write lock on a table the signup path reads. It
-- therefore cannot run inside a transaction block; apply it as its own statement. If it reports
-- INVALID, a duplicate appeared between the check and the run -- drop the index, merge the rows,
-- and re-run.
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "Blocklist_type_key" ON "Blocklist"("type");
