/**
 * App Blocks F-E E5 — autogenerated marketplace screenshot fallback.
 *
 * ⚠️ DISABLED (see `BLOCK_SCREENSHOT_AUTOGEN_ENABLED` below). The capture target
 * is the STANDALONE per-app URL `https://<slug>.<APPS_DOMAIN>/`, but App Blocks
 * only render when EMBEDDED in the civitai host (they wait for a `BLOCK_INIT`
 * postMessage that never arrives standalone), so every autogen capture is an
 * identical 1280×720 "waiting for host" loading skeleton — useless as a
 * marketplace screenshot. Real screenshots come from creator/dev upload (the
 * existing dev-upload + asset-management path), or a future in-host
 * `/apps/run/<slug>` capture rework. The service + tests are RETAINED (not
 * deleted) so that rework can re-wire them; today every entry point is a no-op.
 *
 * When ENABLED (historical behaviour): for an APPROVED App Block that ships NO
 * publisher screenshots, we render the running block at
 * `https://<slug>.<APPS_DOMAIN>` via the verify-runner screenshot service (a
 * warm headless Chromium in devpod-devops) and store the PNG through the
 * EXISTING screenshots path (`storeScreenshots` → bundle MinIO →
 * `app_blocks.screenshots`). The marketplace card + detail page then render it
 * identically to a dev-uploaded image (served by the gated
 * `/api/blocks/screenshot/<appBlockId>/<index>.png` route).
 *
 * Design notes / invariants:
 *   - BEST-EFFORT: every entry point swallows its own errors. A screenshot
 *     failure must NEVER break the deploy pipeline (it's fire-and-forget from
 *     the build-callback deploy-success path).
 *   - GATED: only fires when the app has NO screenshots at all. A dev upload
 *     (or a prior autogen) means we skip — dev screenshots are always preferred.
 *   - MARKER: the stored record carries `autogenerated: true`. A later publisher
 *     upload at re-approve overwrites the whole `screenshots` array (dropping the
 *     marker), so dev content naturally wins.
 *   - SLUG: `AppBlock.blockId` IS the app slug (the approve path upserts with
 *     `blockId: request.slug` and builds `https://<slug>.<APPS_DOMAIN>` origins),
 *     so the backfill can derive the URL from the row alone.
 */
import {
  detectImageType,
  storeScreenshots,
  type ExtractedScreenshot,
  type StoredScreenshot,
} from '~/server/services/blocks/publish-request.service';

// `env` (and the Prisma client) are dynamically imported inside the functions
// that need them so the pure helpers (hasDevScreenshots / blockPublicUrl with an
// explicit domain) stay unit-testable without booting the env-coupled config.

/**
 * Master kill-switch for the standalone-URL screenshot autogen. `false` because
 * the standalone `<slug>.<APPS_DOMAIN>` URL renders only a waiting-for-host
 * skeleton (blocks require the host `BLOCK_INIT` postMessage), so every capture
 * is a useless loading skeleton. Real screenshots come from creator/dev upload
 * (or a future in-host `/apps/run/<slug>` capture). Flip to `true` ONLY once a
 * capture target that actually renders the block exists. Every public entry
 * point below short-circuits to a no-op while this is `false`.
 */
export const BLOCK_SCREENSHOT_AUTOGEN_ENABLED: boolean = false;

/** Default viewport for the autogenerated marketplace screenshot. */
const SCREENSHOT_WIDTH = 1280;
const SCREENSHOT_HEIGHT = 720;
/** Hard ceiling on the verify-runner round trip (nav + capture + our fetch). */
const RUNNER_FETCH_TIMEOUT_MS = 45_000;

/** Build the public per-app subdomain URL for a slug. Pure (domain injected). */
export function blockPublicUrl(slug: string, appsDomain: string): string {
  return `https://${slug}.${appsDomain}/`;
}

/**
 * Does this `app_blocks.screenshots` value already contain at least one
 * publisher-supplied (NON-autogenerated) screenshot? If so, autogen is skipped
 * — dev screenshots are always preferred.
 */
export function hasDevScreenshots(screenshots: unknown): boolean {
  if (!Array.isArray(screenshots)) return false;
  return screenshots.some(
    (s) =>
      s != null &&
      typeof s === 'object' &&
      typeof (s as { key?: unknown }).key === 'string' &&
      (s as { autogenerated?: unknown }).autogenerated !== true
  );
}

/**
 * POST the block URL to verify-runner and return the captured PNG bytes, or
 * `null` on any failure (timeout, non-200, empty body, not configured). Never
 * throws — the caller is best-effort.
 */
async function fetchScreenshotPng(slug: string): Promise<Buffer | null> {
  const { env } = await import('~/env/server');
  const base = env.BLOCK_SCREENSHOT_RUNNER_URL;
  if (!base) {
    // Not configured — silently skip (e.g. PR previews without the runner).
    return null;
  }
  const url = blockPublicUrl(slug, env.APPS_DOMAIN);
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), RUNNER_FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(`${base.replace(/\/$/, '')}/screenshot`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        url,
        width: SCREENSHOT_WIDTH,
        height: SCREENSHOT_HEIGHT,
        wait_until: 'networkidle',
      }),
      signal: controller.signal,
    });
    if (!res.ok) {
      // eslint-disable-next-line no-console
      console.warn(
        `[autogen-screenshot] verify-runner returned ${res.status} for ${url}; skipping`
      );
      return null;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length === 0) return null;
    // Verify the bytes are actually a PNG — same magic-byte gate the publisher
    // path uses, so the served content-type is always correct.
    if (!detectImageType(buf, 'png')) {
      // eslint-disable-next-line no-console
      console.warn(`[autogen-screenshot] verify-runner returned non-PNG bytes for ${url}; skipping`);
      return null;
    }
    return buf;
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(
      `[autogen-screenshot] verify-runner fetch failed for ${url}: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
    return null;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Autogenerate + store a single marketplace screenshot for an approved app
 * block that has no publisher screenshots.
 *
 * Best-effort: returns the stored record on success, or `null` if it skipped /
 * failed (already has screenshots, runner unconfigured/unreachable, capture
 * failed). NEVER throws.
 *
 * Note: the dev-screenshot gate is re-checked here (defence in depth) but the
 * authoritative gate lives at the call site, which already has the row.
 */
export async function autogenerateScreenshot(
  appBlockId: string,
  slug: string
): Promise<StoredScreenshot | null> {
  // Disabled — the standalone `<slug>.<APPS_DOMAIN>` URL renders only a
  // waiting-for-host skeleton; real screenshots come from creator/dev upload (or
  // a future in-host `/apps/run/<slug>` capture). Belt-and-suspenders gate so no
  // caller can reach verify-runner while the feature is off.
  if (!BLOCK_SCREENSHOT_AUTOGEN_ENABLED) return null;
  try {
    const png = await fetchScreenshotPng(slug);
    if (!png) return null;

    const screenshot: ExtractedScreenshot = {
      index: 0,
      ext: 'png',
      contentType: 'image/png',
      content: png,
    };
    const [stored] = await storeScreenshots(appBlockId, [screenshot]);
    if (!stored) return null;

    const record: StoredScreenshot = { ...stored, autogenerated: true };
    const { dbWrite } = await import('~/server/db/client');
    await dbWrite.appBlock.update({
      where: { id: appBlockId },
      // Single autogenerated record. A later publisher upload at re-approve
      // overwrites this whole array (dropping the marker) — dev content wins.
      data: { screenshots: [record] as object },
    });
    // eslint-disable-next-line no-console
    console.info(`[autogen-screenshot] stored autogenerated screenshot for ${slug} (${appBlockId})`);
    return record;
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(
      `[autogen-screenshot] failed for ${slug} (${appBlockId}): ${
        err instanceof Error ? err.message : String(err)
      }`
    );
    return null;
  }
}

/**
 * Fire autogeneration ONLY when the app has no dev screenshots. Used by the
 * deploy-success hook (build-callback): it already has the appBlockId + slug and
 * has just confirmed the new version is live. Best-effort + fire-and-forget.
 *
 * Re-reads the row's `screenshots` here so the gate reflects the latest state
 * (a publisher upload may have landed between deploy start and success).
 */
export async function autogenerateScreenshotIfMissing(
  appBlockId: string,
  slug: string
): Promise<void> {
  // Disabled — the standalone `<slug>.<APPS_DOMAIN>` URL renders only a
  // waiting-for-host skeleton; real screenshots come from creator/dev upload (or
  // a future in-host `/apps/run/<slug>` capture). No-op on the deploy-success
  // hook so we stop stamping skeleton screenshots on every deploy.
  if (!BLOCK_SCREENSHOT_AUTOGEN_ENABLED) return;
  try {
    const { dbRead } = await import('~/server/db/client');
    const row = await dbRead.appBlock.findUnique({
      where: { id: appBlockId },
      select: { status: true, screenshots: true },
    });
    if (!row || row.status !== 'approved') return;
    if (hasDevScreenshots(row.screenshots)) return; // dev screenshots win
    // Skip if it already has an autogenerated shot (no churn on every deploy).
    if (Array.isArray(row.screenshots) && row.screenshots.length > 0) return;
    await autogenerateScreenshot(appBlockId, slug);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(
      `[autogen-screenshot] gate check failed for ${slug} (${appBlockId}): ${
        err instanceof Error ? err.message : String(err)
      }`
    );
  }
}

export type BackfillResult = {
  /** Approved apps with no screenshots that we attempted. */
  attempted: number;
  /** Apps for which a screenshot was successfully stored. */
  succeeded: number;
  /** Apps that failed (runner unreachable, capture failed). */
  failed: number;
  /** Per-app outcomes (slug → ok|fail) for the caller to surface. */
  results: Array<{ appBlockId: string; slug: string; ok: boolean }>;
};

/**
 * Backfill autogenerated screenshots for EXISTING approved apps that lack any.
 * Runnable for the current catalog without waiting for a redeploy (wire to a
 * moderator-only trigger / one-off). Serialised (verify-runner is single-replica
 * with one warm browser) and best-effort per app.
 *
 * Selection: `status='approved'` AND no NON-autogenerated screenshot AND no
 * existing screenshot record at all (so we don't re-shoot apps that already have
 * an autogenerated one). `limit` bounds a single run.
 */
export async function backfillMissingScreenshots(
  opts: { limit?: number } = {}
): Promise<BackfillResult> {
  const result: BackfillResult = { attempted: 0, succeeded: 0, failed: 0, results: [] };
  // Disabled — the standalone `<slug>.<APPS_DOMAIN>` URL renders only a
  // waiting-for-host skeleton; real screenshots come from creator/dev upload (or
  // a future in-host `/apps/run/<slug>` capture). Return an empty result so the
  // mod backfill proc is a safe no-op rather than shooting skeletons at the
  // whole catalog.
  if (!BLOCK_SCREENSHOT_AUTOGEN_ENABLED) return result;

  const limit = opts.limit ?? 50;
  const { dbRead } = await import('~/server/db/client');

  // Pull approved apps and filter for "no screenshots" in app code — the column
  // is a JSON blob (NULL or an array); a NULL/empty-array check is the gate.
  const candidates = await dbRead.appBlock.findMany({
    where: { status: 'approved' },
    select: { id: true, blockId: true, screenshots: true },
    orderBy: { createdAt: 'asc' },
  });

  const missing = candidates.filter((c) => {
    if (hasDevScreenshots(c.screenshots)) return false;
    return !Array.isArray(c.screenshots) || c.screenshots.length === 0;
  });

  for (const c of missing) {
    if (result.attempted >= limit) break;
    result.attempted += 1;
    // blockId IS the slug.
    const stored = await autogenerateScreenshot(c.id, c.blockId);
    const ok = stored != null;
    if (ok) result.succeeded += 1;
    else result.failed += 1;
    result.results.push({ appBlockId: c.id, slug: c.blockId, ok });
  }
  return result;
}
