
-- AlterTable
ALTER TABLE "Article" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Article" ADD COLUMN IF NOT EXISTS     "userNsfwLevel" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Bounty" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "BountyEntry" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Collection" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Image" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Image" ADD COLUMN IF NOT EXISTS     "nsfwLevelLocked" BOOLEAN NOT NULL DEFAULT FALSE;

-- AlterTable
ALTER TABLE "ModelVersion" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Model" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS     "nsfwLevel" INTEGER NOT NULL DEFAULT 0;



-- AlterTable
ALTER TABLE "Article" ADD COLUMN IF NOT EXISTS     "lockedProperties" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "Bounty" ADD COLUMN IF NOT EXISTS    "lockedProperties" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "Model" ADD COLUMN IF NOT EXISTS    "lockedProperties" TEXT[] DEFAULT ARRAY[]::TEXT[];
