import pg from 'pg';
import { Kysely, PostgresDialect } from 'kysely';
import { dev } from '$app/environment';
import { env } from '$env/dynamic/private';
import type { DB } from '@civitai/db-schema/kysely';
import { logAxiomError } from '../axiom';

// Direct pg Pool + Kysely, mirroring civitai-advertising's src/lib/server/db/db.ts, rather than
// @civitai/db's createKyselyClients. Switching is not a drop-in: the factory also registers a UTC
// parser for `timestamp without time zone` (changes how VerificationToken.expires round-trips off-UTC)
// and does not pass Kysely's `log` option through.
//
// `DB` is the full schema generated by prisma-kysely in @civitai/db-schema (the `kysely`
// generator). The hub only queries a handful of tables (User/Account/VerificationToken/Blocklist),
// but typing against the real schema keeps it honest as columns change.
const { Pool, types } = pg;

// Numeric/bigint come back as JS numbers (Kysely-friendly)
types.setTypeParser(types.builtins.NUMERIC, (val) => parseFloat(val));
types.setTypeParser(types.builtins.INT8, (val) => parseFloat(val));

// The cnpg pooler presents a self-signed cert. node-postgres maps the URL's `sslmode=require` to
// FULL chain verification (unlike libpq), which rejects it — and a separate `ssl` option gets
// overridden by the URL's sslmode. So force `sslmode=no-verify`: keep SSL on, skip verification.
// Mirrors the main app's db-helpers. (Advertising's URL simply has no sslmode, so it never hits
// this; ours does.)
function buildConnectionString(): string {
  if (!env.DATABASE_URL) throw new Error('DATABASE_URL is not configured');
  const url = new URL(env.DATABASE_URL);
  url.searchParams.set('sslmode', 'no-verify');
  return url.toString();
}

// Explicit pool sizing, matching what `@civitai/db`'s createKyselyClients applies for the apps that
// use the shared factory. `connectionTimeoutMillis` is the important one: pg defaults it to 0, i.e.
// "wait forever", so an exhausted pool silently queues every caller instead of failing fast.
const pool = new Pool({
  connectionString: buildConnectionString(),
  max: 20,
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 5_000,
});

// An unhandled pg 'error' exits the process. pg-pool detaches its own client listener while a client is
// checked out, so a connection dropped mid-query needs this one; it logs here, so the pool re-emit is a no-op.
pool.on('connect', (client) => {
  client.on('error', (err) => {
    void logAxiomError(err, { event: 'db client connection error' });
  });
});
pool.on('error', () => {});

export const db = new Kysely<DB>({
  dialect: new PostgresDialect({ pool }),
  log: (event) => {
    if (dev && event.level === 'error') {
      console.error('[db] query failed:', event.error, '\nsql:', event.query.sql);
    }
  },
});
