/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface FactoryInterface extends utils.Interface {
  functions: {
    "deployNewERC20Token(string,string,uint8,uint256)": FunctionFragment;
    "deployNewERC721Token(string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deployNewERC20Token" | "deployNewERC721Token"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployNewERC20Token",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployNewERC721Token",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployNewERC20Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployNewERC721Token",
    data: BytesLike
  ): Result;

  events: {
    "ERC20TokenCreated(address)": EventFragment;
    "ERC721TokenCreated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ERC20TokenCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ERC721TokenCreated"): EventFragment;
}

export interface ERC20TokenCreatedEventObject {
  tokenAddress: string;
}
export type ERC20TokenCreatedEvent = TypedEvent<
  [string],
  ERC20TokenCreatedEventObject
>;

export type ERC20TokenCreatedEventFilter =
  TypedEventFilter<ERC20TokenCreatedEvent>;

export interface ERC721TokenCreatedEventObject {
  tokenAddress: string;
}
export type ERC721TokenCreatedEvent = TypedEvent<
  [string],
  ERC721TokenCreatedEventObject
>;

export type ERC721TokenCreatedEventFilter =
  TypedEventFilter<ERC721TokenCreatedEvent>;

export interface Factory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployNewERC20Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      initialSupply: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployNewERC721Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deployNewERC20Token(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    decimals: PromiseOrValue<BigNumberish>,
    initialSupply: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployNewERC721Token(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployNewERC20Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      initialSupply: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployNewERC721Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ERC20TokenCreated(address)"(
      tokenAddress?: null
    ): ERC20TokenCreatedEventFilter;
    ERC20TokenCreated(tokenAddress?: null): ERC20TokenCreatedEventFilter;

    "ERC721TokenCreated(address)"(
      tokenAddress?: null
    ): ERC721TokenCreatedEventFilter;
    ERC721TokenCreated(tokenAddress?: null): ERC721TokenCreatedEventFilter;
  };

  estimateGas: {
    deployNewERC20Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      initialSupply: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployNewERC721Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployNewERC20Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      initialSupply: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployNewERC721Token(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
