apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: metric-watcher
  labels:
    strimzi.io/cluster: metric-watcher-cluster
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: metric-watcher
  labels:
    strimzi.io/cluster: metric-watcher-cluster
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 20Gi
    deleteClaim: false