BEGIN;
-- AlterTable
ALTER TABLE "ClubTier" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "memberLimit" INTEGER,
ADD COLUMN     "updatedAt" TIMESTAMP(3);
COMMIT;