// Ambient declarations for CSS Modules (Turbopack / Next 16).
//
// Previously this project committed per-file `*.module.scss.d.ts` declarations
// generated by `typed-scss-modules` (the `generate-types` script). Turbopack's
// TypeScript-aware resolver bundles those adjacent declaration files as runtime
// modules and then fails to parse their `declare const` syntax as JavaScript
// ("Expected ';', '}' or <eof>"), panicking the build. Replacing the per-file
// declarations with these ambient module declarations lets Turbopack resolve the
// real `.scss`/`.css` files for CSS processing.
//
// Trade-off: this is loose typing (any class name resolves to `string`) rather
// than the per-class typing typed-scss-modules provided. All CSS-module imports
// in the codebase are default imports, so nothing relies on named class exports.
declare module '*.module.scss' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module '*.module.css' {
  const classes: { readonly [key: string]: string };
  export default classes;
}
