import { createStyles, Group, Title } from '@mantine/core';
import Head from 'next/head';
import { AppLayout } from '~/components/AppLayout/AppLayout';
import { ModelCard } from '~/components/ModelCard/ModelCard';
import { trpc } from '~/utils/trpc';

function Home() {
  const { data } = trpc.example.hello.useQuery({ text: 'from tRPC' });
  const { classes, cx } = useStyles();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <AppLayout>
        <Group p="md">
          <Title>This is the home page</Title>
        </Group>
        <div className={classes.gridLayout}>
          <ModelCard id={1} name="bob" />
          <ModelCard id={1} name="bob" />
          <ModelCard id={1} name="bob" />
          <ModelCard id={1} name="bob" />
          <ModelCard id={1} name="bob" />
          <ModelCard id={1} name="bob" />
        </div>
      </AppLayout>
    </>
  );
}

export default Home;

const useStyles = createStyles((theme) => ({
  gridLayout: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, 300px)',
    gap: '16px',
    justifyContent: 'center',
  },
}));
