// TODO type this with QueryGeneratedImages

export const queryGeneratedImagesReturn = {
  result: {
    data: {
      json: {
        items: [
          {
            id: '0-20250204210845449',
            status: 'failed',
            createdAt: '2025-02-04T21:08:45.451Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 4,
                steps: 0.8333333333333334,
                scheduler: 1.2,
                batchSize: 1,
                quantity: 1,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['gen', 'txt2img', 'img', 'civitai'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt:
                    'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 1,
                  engine: null,
                  width: 1024,
                  height: 1024,
                  seed: 947961051,
                  draft: false,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'DPM++ 2M Karras',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250204210845449',
                    stepName: '$0',
                    jobId: '47f7567e-23ba-458c-8b7a-488977bceddc',
                    id: 'SDA6NA62G1J7PJQ78QW4QSR060.jpeg',
                    status: 'failed',
                    seed: 947961051,
                    completed: '2025-02-04T21:08:51.242Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/SDA6NA62G1J7PJQ78QW4QSR060.jpeg',
                    width: 1024,
                    height: 1024,
                  },
                ],
                status: 'failed',
                metadata: {
                  resources: [
                    {
                      id: 889818,
                      strength: 1,
                    },
                    {
                      id: 1368383,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt:
                      'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'DPM++ 2M Karras',
                    seed: 2040477799,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 1,
                    nsfw: false,
                    draft: false,
                    baseModel: 'Illustrious',
                    width: 1024,
                    height: 1024,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250204204817607',
            status: 'failed',
            createdAt: '2025-02-04T20:48:17.607Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 4,
                steps: 0.8333333333333334,
                scheduler: 1.2,
                batchSize: 1,
                quantity: 1,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['gen', 'txt2img', 'img', 'civitai'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt:
                    'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 1,
                  engine: null,
                  width: 1024,
                  height: 1024,
                  seed: 1487064427,
                  draft: false,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'DPM++ 2M Karras',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250204204817607',
                    stepName: '$0',
                    jobId: 'ed4d238a-e671-452d-9c87-9885324b9862',
                    id: 'S2TAC5RY54C742D31ZQCXSNVX0.jpeg',
                    status: 'failed',
                    seed: 1487064427,
                    completed: '2025-02-04T20:48:26.161Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/S2TAC5RY54C742D31ZQCXSNVX0.jpeg',
                    width: 1024,
                    height: 1024,
                  },
                ],
                status: 'failed',
                metadata: {
                  resources: [
                    {
                      id: 889818,
                      strength: 1,
                    },
                    {
                      id: 1368383,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt:
                      'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'DPM++ 2M Karras',
                    seed: 383053602,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 1,
                    nsfw: false,
                    draft: false,
                    baseModel: 'Illustrious',
                    width: 1024,
                    height: 1024,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250204202347174',
            status: 'failed',
            createdAt: '2025-02-04T20:23:47.175Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 4,
                steps: 0.8333333333333334,
                scheduler: 1.2,
                batchSize: 1,
                quantity: 1,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['gen', 'txt2img', 'img', 'civitai'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt:
                    'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 1,
                  engine: null,
                  width: 1024,
                  height: 1024,
                  seed: 228810617,
                  draft: false,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'DPM++ 2M Karras',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250204202347174',
                    stepName: '$0',
                    jobId: '2226ab4a-d7ac-4abc-b403-becb4b4c631a',
                    id: 'NSPD7QRY8C94HQT06JX4GR0DB0.jpeg',
                    status: 'failed',
                    seed: 228810617,
                    completed: '2025-02-04T20:25:15.970Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/NSPD7QRY8C94HQT06JX4GR0DB0.jpeg',
                    width: 1024,
                    height: 1024,
                  },
                ],
                status: 'failed',
                metadata: {
                  resources: [
                    {
                      id: 889818,
                      strength: 1,
                    },
                    {
                      id: 1368383,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt:
                      'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'DPM++ 2M Karras',
                    seed: 644927730,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 1,
                    nsfw: false,
                    draft: false,
                    baseModel: 'Illustrious',
                    width: 1024,
                    height: 1024,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250204181927068',
            status: 'expired',
            createdAt: '2025-02-04T18:19:27.068Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 4,
                steps: 0.8333333333333334,
                scheduler: 1.2,
                batchSize: 1,
                quantity: 1,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['gen', 'txt2img', 'img', 'civitai'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt:
                    'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 1,
                  engine: null,
                  width: 1024,
                  height: 1024,
                  seed: 1000492083,
                  draft: false,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'DPM++ 2M Karras',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250204181927068',
                    stepName: '$0',
                    jobId: 'f57c8583-b778-4c0c-99be-b8e8ba2ffc44',
                    id: 'TZME4SPEJ0C5GY3CJBM7EAG7S0.jpeg',
                    status: 'expired',
                    seed: 1000492083,
                    completed: '2025-02-04T18:30:27.113Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/TZME4SPEJ0C5GY3CJBM7EAG7S0.jpeg',
                    width: 1024,
                    height: 1024,
                  },
                ],
                status: 'expired',
                metadata: {
                  resources: [
                    {
                      id: 889818,
                      strength: 1,
                    },
                    {
                      id: 1368383,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt:
                      'floating above a miniature mountain landscape. The image, creating a charming and electrifying visual experience. (Masterpiece:1.2), perfect composition, pinkfluxproultrafantasia, visually stunning, floating above a miniature Kame house landscape. The image, a digital Chibi Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, a digital Base Goku materializes in a tilt-shift photograph. The main subject is a translucent chibi Goku with glitching pixels, full view, best artist, sharp edges, perfect symmetry, 8K, detailed textures, captures Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, In a whimsically vibrant scene, best quality, trending on behance, UHD, best details, atmospheric lighting',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'DPM++ 2M Karras',
                    seed: 2017147015,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 1,
                    nsfw: false,
                    draft: false,
                    baseModel: 'Illustrious',
                    width: 1024,
                    height: 1024,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250203215059471',
            status: 'succeeded',
            createdAt: '2025-02-03T21:50:59.471Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                base: 32.5,
                batchSize: 1,
                quantity: 0,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['gen', 'txt2img', 'img', 'civitai'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt:
                    ' Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, UHD, captures Goku in dazzling detail—its Black hair and black eyes glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, perfect symmetry, floating above a miniature Mushroom Kingdom. ',
                  negativePrompt: '',
                  quantity: 1,
                  engine: null,
                  width: 1024,
                  height: 1024,
                  seed: 433507678,
                  draft: false,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'DPM++ 2M Karras',
                  fluxMode: 'urn:air:flux1:checkpoint:civitai:618692@691639',
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250203215059471',
                    stepName: '$0',
                    jobId: '884c16be-e534-4021-928c-13f46f182b30',
                    id: 'SJX4A38JM37X8120FV2GC7DST0.jpeg',
                    status: 'succeeded',
                    seed: 433507678,
                    completed: '2025-02-03T21:51:03.139Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/SJX4A38JM37X8120FV2GC7DST0.jpeg',
                    width: 1024,
                    height: 1024,
                  },
                ],
                status: 'succeeded',
                metadata: {
                  resources: [
                    {
                      id: 691639,
                      strength: 1,
                    },
                    {
                      id: 1351585,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt:
                      ' Goku in dazzling detail—its Black hair and black eyes and body glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, UHD, captures Goku in dazzling detail—its Black hair and black eyes glowing with swirling ethereal wisps of code. The high quality of the image reveals intricate details of Goku’s pixelated essence, perfect symmetry, floating above a miniature Mushroom Kingdom. ',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'DPM++ 2M Karras',
                    seed: 1407917325,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 1,
                    nsfw: false,
                    draft: false,
                    fluxUltraAspectRatio: '4',
                    baseModel: 'Flux1',
                    width: 1024,
                    height: 1024,
                    workflow: 'txt2img',
                    fluxMode: 'urn:air:flux1:checkpoint:civitai:618692@691639',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250203214857886',
            status: 'succeeded',
            createdAt: '2025-02-03T21:48:57.886Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                base: 32.5,
                batchSize: 1,
                quantity: 0,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['gen', 'txt2img', 'img', 'civitai'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt:
                    'A photograph capturing a miniature storm swirling inside a delicate porcelain teacup. The teacup is placed on a saucer, resting on a rustic wooden table. Inside the cup, tiny clouds churn, and lightning bolts flicker, creating a chaotic yet contained scene. The surrounding area is serene, with soft morning light filtering through sheer curtains, illuminating the teacup and its dramatic contents. Steam rises from the tea, blending with the stormy clouds, while tiny droplets of water scatter across the saucer. The contrast between the calm exterior and the tumultuous interior highlights the whimsical nature of this "storm in a teacup."',
                  negativePrompt: '',
                  quantity: 2,
                  engine: null,
                  width: 1024,
                  height: 1024,
                  seed: 537434840,
                  draft: false,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'DPM++ 2M Karras',
                  fluxMode: 'urn:air:flux1:checkpoint:civitai:618692@691639',
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250203214857886',
                    stepName: '$0',
                    jobId: '1c5bbe34-0101-4853-9faf-aa07d584e0d4',
                    id: '46X6BNE5040MZZ7AKMQCCV8TF0.jpeg',
                    status: 'succeeded',
                    seed: 537434840,
                    completed: '2025-02-03T21:49:02.029Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/46X6BNE5040MZZ7AKMQCCV8TF0.jpeg',
                    width: 1024,
                    height: 1024,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250203214857886',
                    stepName: '$0',
                    jobId: '2c4c075b-34e2-4d8c-acf2-e1e53c4c6640',
                    id: 'Y9CFX2Z10TXCPVC1VNEXB9NRF0.jpeg',
                    status: 'succeeded',
                    seed: 537434841,
                    completed: '2025-02-03T21:49:02.029Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/Y9CFX2Z10TXCPVC1VNEXB9NRF0.jpeg',
                    width: 1024,
                    height: 1024,
                  },
                ],
                status: 'succeeded',
                metadata: {
                  resources: [
                    {
                      id: 691639,
                      strength: 1,
                    },
                    {
                      id: 1351585,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt:
                      'A photograph capturing a miniature storm swirling inside a delicate porcelain teacup. The teacup is placed on a saucer, resting on a rustic wooden table. Inside the cup, tiny clouds churn, and lightning bolts flicker, creating a chaotic yet contained scene. The surrounding area is serene, with soft morning light filtering through sheer curtains, illuminating the teacup and its dramatic contents. Steam rises from the tea, blending with the stormy clouds, while tiny droplets of water scatter across the saucer. The contrast between the calm exterior and the tumultuous interior highlights the whimsical nature of this "storm in a teacup."',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'DPM++ 2M Karras',
                    seed: 1402123823,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 2,
                    nsfw: false,
                    draft: false,
                    fluxUltraAspectRatio: '4',
                    baseModel: 'Flux1',
                    width: 1024,
                    height: 1024,
                    workflow: 'txt2img',
                    fluxMode: 'urn:air:flux1:checkpoint:civitai:618692@691639',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250201025116259',
            status: 'succeeded',
            createdAt: '2025-02-01T02:51:16.260Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 1,
                steps: 0.8333333333333334,
                scheduler: 0.8,
                batchSize: 1,
                quantity: 0,
              },
              fixed: {
                additionalNetworks: 0,
                priority: 0,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['img', 'txt2img', 'civitai', 'gen'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt: 'test',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 4,
                  engine: null,
                  width: 512,
                  height: 512,
                  seed: 1560693729,
                  draft: false,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'Euler a',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250201025116259',
                    stepName: '$0',
                    jobId: '2b5d945b-fde3-4932-9a20-b9b8c53968a4',
                    id: '7HSJ9ZFSF500WNBCGWN0QB6A50.jpeg',
                    status: 'succeeded',
                    seed: 1560693729,
                    completed: '2025-02-01T02:51:19.384Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/7HSJ9ZFSF500WNBCGWN0QB6A50.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201025116259',
                    stepName: '$0',
                    jobId: 'fa639946-93c4-43f4-8122-c87a93997249',
                    id: 'J9DACMCRF9HTRGX1453DQAVAQ0.jpeg',
                    status: 'succeeded',
                    seed: 1560693730,
                    completed: '2025-02-01T02:51:22.122Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/J9DACMCRF9HTRGX1453DQAVAQ0.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201025116259',
                    stepName: '$0',
                    jobId: '4db98a35-1942-41ce-98dd-0f4e6cd6967e',
                    id: 'DT9K7945FXRT191TGV1MEGDGX0.jpeg',
                    status: 'succeeded',
                    seed: 1560693731,
                    completed: '2025-02-01T02:51:24.850Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/DT9K7945FXRT191TGV1MEGDGX0.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201025116259',
                    stepName: '$0',
                    jobId: 'b56070b5-9557-47c9-b1af-0d5907a5be75',
                    id: 'W89BEXNJ7GC93KQF2B7TYRF8N0.jpeg',
                    status: 'succeeded',
                    seed: 1560693732,
                    completed: '2025-02-01T02:51:27.479Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/W89BEXNJ7GC93KQF2B7TYRF8N0.jpeg',
                    width: 512,
                    height: 512,
                  },
                ],
                status: 'succeeded',
                metadata: {
                  resources: [
                    {
                      id: 637156,
                      strength: 1,
                    },
                    {
                      id: 11523,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt: 'test',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'Euler a',
                    seed: 1690123623,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 4,
                    nsfw: false,
                    draft: false,
                    baseModel: 'SD1',
                    width: 512,
                    height: 512,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250201024852978',
            status: 'succeeded',
            createdAt: '2025-02-01T02:48:52.978Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 1,
                steps: 0.2,
                scheduler: 0.5,
                batchSize: 4,
                quantity: 0,
              },
              fixed: {
                additionalNetworks: 0,
                priority: 0,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['img', 'txt2img', 'civitai', 'gen'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:11:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt: 'test',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 4,
                  engine: null,
                  width: 512,
                  height: 512,
                  seed: 189937593,
                  draft: true,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'Euler a',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250201024852978',
                    stepName: '$0',
                    jobId: '64afd8a4-e8b2-4260-ad6c-f7766d08f24c',
                    id: 'MR1GHYT7XH7RVMMCCR8X7568D0.jpeg',
                    status: 'succeeded',
                    seed: 189937593,
                    completed: '2025-02-01T02:49:36.609Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/MR1GHYT7XH7RVMMCCR8X7568D0.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201024852978',
                    stepName: '$0',
                    jobId: '64afd8a4-e8b2-4260-ad6c-f7766d08f24c',
                    id: '1GR2SC63DZ6H7P8PFHQ2V3GE70.jpeg',
                    status: 'succeeded',
                    seed: 189937593,
                    completed: '2025-02-01T02:49:36.609Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/1GR2SC63DZ6H7P8PFHQ2V3GE70.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201024852978',
                    stepName: '$0',
                    jobId: '64afd8a4-e8b2-4260-ad6c-f7766d08f24c',
                    id: 'D0Q7FEBN12YZJJV0G90PR12CT0.jpeg',
                    status: 'succeeded',
                    seed: 189937593,
                    completed: '2025-02-01T02:49:36.609Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/D0Q7FEBN12YZJJV0G90PR12CT0.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201024852978',
                    stepName: '$0',
                    jobId: '64afd8a4-e8b2-4260-ad6c-f7766d08f24c',
                    id: '4FY9B3Z9T13M7VRVJDE2BWJNB0.jpeg',
                    status: 'succeeded',
                    seed: 189937593,
                    completed: '2025-02-01T02:49:36.609Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/4FY9B3Z9T13M7VRVJDE2BWJNB0.jpeg',
                    width: 512,
                    height: 512,
                  },
                ],
                status: 'succeeded',
                metadata: {
                  resources: [
                    {
                      id: 637156,
                      strength: 1,
                    },
                    {
                      id: 11523,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt: 'test',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'Euler a',
                    seed: 1795330677,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 4,
                    nsfw: false,
                    draft: true,
                    baseModel: 'SD1',
                    width: 512,
                    height: 512,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250201022029366',
            status: 'succeeded',
            createdAt: '2025-02-01T02:20:29.366Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 1,
                steps: 0.2,
                scheduler: 0.5,
                batchSize: 4,
                quantity: 0,
              },
              fixed: {
                additionalNetworks: 0,
                priority: 0,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['img', 'txt2img', 'civitai', 'gen'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:10:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt: 'test',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 4,
                  engine: null,
                  width: 512,
                  height: 512,
                  seed: 1372592749,
                  draft: true,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 3,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'Euler a',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250201022029366',
                    stepName: '$0',
                    jobId: '76d9ca5f-0836-4e2e-bd61-b4e9326ea43f',
                    id: 'QG0CWJ9MB8Y8P7FXNPDV34RY10.jpeg',
                    status: 'succeeded',
                    seed: 1372592749,
                    completed: '2025-02-01T02:21:38.095Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/QG0CWJ9MB8Y8P7FXNPDV34RY10.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201022029366',
                    stepName: '$0',
                    jobId: '76d9ca5f-0836-4e2e-bd61-b4e9326ea43f',
                    id: 'CRKFRJ7YPZPSVMH9WJD1R5XNW0.jpeg',
                    status: 'succeeded',
                    seed: 1372592749,
                    completed: '2025-02-01T02:21:38.095Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/CRKFRJ7YPZPSVMH9WJD1R5XNW0.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201022029366',
                    stepName: '$0',
                    jobId: '76d9ca5f-0836-4e2e-bd61-b4e9326ea43f',
                    id: '5A9XS4QRNX5RG6Z3Y8J4VHGA80.jpeg',
                    status: 'succeeded',
                    seed: 1372592749,
                    completed: '2025-02-01T02:21:38.095Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/5A9XS4QRNX5RG6Z3Y8J4VHGA80.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201022029366',
                    stepName: '$0',
                    jobId: '76d9ca5f-0836-4e2e-bd61-b4e9326ea43f',
                    id: 'H1X8JANWKQVHMGGTDMJNN4C130.jpeg',
                    status: 'succeeded',
                    seed: 1372592749,
                    completed: '2025-02-01T02:21:38.095Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/H1X8JANWKQVHMGGTDMJNN4C130.jpeg',
                    width: 512,
                    height: 512,
                  },
                ],
                status: 'succeeded',
                metadata: {
                  resources: [
                    {
                      id: 57618,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt: 'test',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'Euler a',
                    seed: 1497112795,
                    clipSkip: 3,
                    steps: 25,
                    quantity: 4,
                    nsfw: false,
                    draft: true,
                    baseModel: 'SD1',
                    width: 512,
                    height: 512,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
          {
            id: '0-20250201021434336',
            status: 'succeeded',
            createdAt: '2025-02-01T02:14:34.337Z',
            totalCost: 0,
            cost: {
              base: 0,
              factors: {
                size: 1,
                steps: 0.2,
                scheduler: 0.5,
                batchSize: 4,
                quantity: 0,
              },
              fixed: {
                additionalNetworks: 0,
                priority: 0,
              },
              tips: {
                civitai: 0,
                creators: 0,
              },
              total: 0,
            },
            tags: ['img', 'txt2img', 'civitai', 'gen'],
            steps: [
              {
                $type: 'textToImage',
                timeout: '00:10:00',
                name: '$0',
                params: {
                  baseModel: 'SD1',
                  prompt: 'test',
                  negativePrompt: 'civit_nsfw, ',
                  quantity: 4,
                  engine: null,
                  width: 512,
                  height: 512,
                  seed: 271414583,
                  draft: true,
                  nsfw: false,
                  workflow: 'txt2img',
                  clipSkip: 2,
                  steps: 25,
                  cfgScale: 3.5,
                  sampler: 'Euler a',
                  fluxMode: null,
                  fluxUltraRaw: null,
                },
                images: [
                  {
                    type: 'image',
                    workflowId: '0-20250201021434336',
                    stepName: '$0',
                    jobId: '50d68df4-0fa2-483c-902e-e9ced64b636f',
                    id: 'CQW4MKM51BSX2Z9B4Y46QNXQ50.jpeg',
                    status: 'succeeded',
                    seed: 271414583,
                    completed: '2025-02-01T02:15:14.795Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/CQW4MKM51BSX2Z9B4Y46QNXQ50.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201021434336',
                    stepName: '$0',
                    jobId: '50d68df4-0fa2-483c-902e-e9ced64b636f',
                    id: 'FN1DRV1A7R140MVX0BP82XHT20.jpeg',
                    status: 'succeeded',
                    seed: 271414583,
                    completed: '2025-02-01T02:15:14.795Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/FN1DRV1A7R140MVX0BP82XHT20.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201021434336',
                    stepName: '$0',
                    jobId: '50d68df4-0fa2-483c-902e-e9ced64b636f',
                    id: '4KW2692M67M9409ZWDWYSX83J0.jpeg',
                    status: 'succeeded',
                    seed: 271414583,
                    completed: '2025-02-01T02:15:14.795Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/4KW2692M67M9409ZWDWYSX83J0.jpeg',
                    width: 512,
                    height: 512,
                  },
                  {
                    type: 'image',
                    workflowId: '0-20250201021434336',
                    stepName: '$0',
                    jobId: '50d68df4-0fa2-483c-902e-e9ced64b636f',
                    id: 'VG8BQS0MDR5MN5Z2E34ZRER2B0.jpeg',
                    status: 'succeeded',
                    seed: 271414583,
                    completed: '2025-02-01T02:15:14.795Z',
                    url: 'https://orchestration-dev.civitai.com/v2/consumer/blobs/VG8BQS0MDR5MN5Z2E34ZRER2B0.jpeg',
                    width: 512,
                    height: 512,
                  },
                ],
                status: 'succeeded',
                metadata: {
                  resources: [
                    {
                      id: 128713,
                      strength: 1,
                    },
                  ],
                  params: {
                    prompt: 'test',
                    negativePrompt: '',
                    cfgScale: 3.5,
                    sampler: 'Euler a',
                    seed: 1044358015,
                    clipSkip: 2,
                    steps: 25,
                    quantity: 4,
                    nsfw: false,
                    draft: true,
                    baseModel: 'SD1',
                    width: 512,
                    height: 512,
                    workflow: 'txt2img',
                    experimental: false,
                  },
                },
                resources: [],
              },
            ],
          },
        ],
        nextCursor: null,
      },
      meta: {
        values: {
          'items.0.createdAt': ['Date'],
          'items.0.steps.0.params.engine': ['undefined'],
          'items.0.steps.0.params.fluxMode': ['undefined'],
          'items.0.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.0.steps.0.images.0.completed': ['Date'],
          'items.1.createdAt': ['Date'],
          'items.1.steps.0.params.engine': ['undefined'],
          'items.1.steps.0.params.fluxMode': ['undefined'],
          'items.1.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.1.steps.0.images.0.completed': ['Date'],
          'items.2.createdAt': ['Date'],
          'items.2.steps.0.params.engine': ['undefined'],
          'items.2.steps.0.params.fluxMode': ['undefined'],
          'items.2.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.2.steps.0.images.0.completed': ['Date'],
          'items.3.createdAt': ['Date'],
          'items.3.steps.0.params.engine': ['undefined'],
          'items.3.steps.0.params.fluxMode': ['undefined'],
          'items.3.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.3.steps.0.images.0.completed': ['Date'],
          'items.4.createdAt': ['Date'],
          'items.4.steps.0.params.engine': ['undefined'],
          'items.4.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.4.steps.0.images.0.completed': ['Date'],
          'items.5.createdAt': ['Date'],
          'items.5.steps.0.params.engine': ['undefined'],
          'items.5.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.5.steps.0.images.0.completed': ['Date'],
          'items.5.steps.0.images.1.completed': ['Date'],
          'items.6.createdAt': ['Date'],
          'items.6.steps.0.params.engine': ['undefined'],
          'items.6.steps.0.params.fluxMode': ['undefined'],
          'items.6.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.6.steps.0.images.0.completed': ['Date'],
          'items.6.steps.0.images.1.completed': ['Date'],
          'items.6.steps.0.images.2.completed': ['Date'],
          'items.6.steps.0.images.3.completed': ['Date'],
          'items.7.createdAt': ['Date'],
          'items.7.steps.0.params.engine': ['undefined'],
          'items.7.steps.0.params.fluxMode': ['undefined'],
          'items.7.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.7.steps.0.images.0.completed': ['Date'],
          'items.7.steps.0.images.1.completed': ['Date'],
          'items.7.steps.0.images.2.completed': ['Date'],
          'items.7.steps.0.images.3.completed': ['Date'],
          'items.8.createdAt': ['Date'],
          'items.8.steps.0.params.engine': ['undefined'],
          'items.8.steps.0.params.fluxMode': ['undefined'],
          'items.8.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.8.steps.0.images.0.completed': ['Date'],
          'items.8.steps.0.images.1.completed': ['Date'],
          'items.8.steps.0.images.2.completed': ['Date'],
          'items.8.steps.0.images.3.completed': ['Date'],
          'items.9.createdAt': ['Date'],
          'items.9.steps.0.params.engine': ['undefined'],
          'items.9.steps.0.params.fluxMode': ['undefined'],
          'items.9.steps.0.params.fluxUltraRaw': ['undefined'],
          'items.9.steps.0.images.0.completed': ['Date'],
          'items.9.steps.0.images.1.completed': ['Date'],
          'items.9.steps.0.images.2.completed': ['Date'],
          'items.9.steps.0.images.3.completed': ['Date'],
        },
      },
    },
  },
};
