import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { CommercialUse } from '~/shared/utils/prisma/enums';

/**
 * The licence's commercial restrictions are emitted by ABSENCE: a clause appears for every
 * CommercialUse value the creator did NOT grant. So a permission with no clause silently
 * imposes no restriction, and asserting the clause map has a key proves nothing about the
 * document a buyer reads. These assert on the returned document.
 *
 * The disapplying sentence in "Sale of the Model" is what makes the split real. Attachment B's
 * preamble extends a restriction that references the Model to "the Model and Derivatives of the
 * Model" except where that restriction states otherwise, and defines Derivatives to include
 * Merges — TWO arms. So the sentence has to disapply the Permission, not
 * narrow what "the Model" means: narrowing the noun leaves the Derivatives arm still catching
 * merges, and the creator gets a green tick over a licence that forbids the thing. Delete or
 * reword that sentence and `withholds Sell, grants SellMerge` must fail — if you are removing it
 * as redundant next to a clause already headed "Sale of the Model", that is the case telling you
 * why it is not.
 *
 * It is asserted INSIDE the Sale of the Model clause rather than anywhere in the document,
 * because moving it into the preamble would disapply it from every other clause and a
 * document-wide `toContain` would stay green through that.
 */

const { addAdditionalLicensePermissions } = await import('~/server/services/model-version.service');

const MODEL_CLAUSE = 'Sale of the Model:';
const MERGE_CLAUSE = 'Sale of Merges:';
const DISAPPLIES_TO_MERGES = 'This restriction does not apply to a Merge.';
const EXPANDS_CONDITIONALLY =
  'A restriction below that references the Model applies to the Model and Derivatives of the Model, except to the extent that restriction expressly states otherwise.';
const CARVE_OUT_GRANTS_NOTHING =
  'A statement that a restriction does not apply to something limits only that restriction and does not permit that thing.';
const MERGE_LINEAGE_SENTENCE =
  'A Derivative of the Model will be understood to include Merges, and a Merge will be understood to include Derivatives of a Merge.';
const MERGE_DEFINED =
  '“Merge” means, with respect to the Model, combining the Model or a Derivative of the Model with one or more other models to produce a single model.';
const PERMISSION_LIST_OPENS =
  'You agree to the following with respect to the Model (each a “Permission”):';
const SHARING_CLAUSE = 'Do not Share or make available a Merge';
/** `<b>`-prefixed: 'Generation Services:' is a substring of 'Civitai Generation Services:', so a
 * bare heading anchors on whichever the map happens to emit first. */
const IMAGE_SALES_CLAUSE = '<b>Image Sales:';
const RENT_CLAUSE = '<b>Generation Services:';
const RENT_CIVIT_CLAUSE = '<b>Civitai Generation Services:';
const CHANGING_PERMISSIONS_CLAUSE = '<b>Changing Permissions:';
const CHANGING_PERMISSIONS =
  'Changing Permissions: modify or eliminate any of the applicable Permissions when sharing or making available a Derivative of the Model.';
const CREATOR_CREDIT_CLAUSE = '<b>Creator Credit:';
const FORBIDS_MODEL_SALE = 'Do not sell or license the Model';
const FORBIDS_MERGE_SALE = 'Do not sell or license a Merge';
const FORBIDS_IMAGE_SALE = 'Do not sell or license images generated by the Model';
const FORBIDS_RENT = 'Do not use the Model on any service that monetizes image generation';
const FORBIDS_RENT_CIVIT = 'Do not run the Model on the Civitai platform for generation';

/**
 * Everything before the Permission list, so a preamble sentence cannot be satisfied from a clause.
 * Throws rather than slicing on -1: `slice(0, -1)` is the whole document minus one character, which
 * silently widens every positional assertion below into a document-wide toContain.
 */
const preamble = (license: string) => {
  const end = license.indexOf(PERMISSION_LIST_OPENS);
  if (end === -1) throw new Error(`preamble anchor not found: ${PERMISSION_LIST_OPENS}`);
  return license.slice(0, end);
};

/**
 * One clause body, so an assertion about scope cannot be satisfied from a different clause.
 * Ends at the next `\n<b>` rather than at the closing `</b>`, so a suffix appended after the tag --
 * where an "every clause says this" refactor lands -- stays inside the region instead of falling
 * between two clauses where no negative could see it.
 *
 * The region then has to prove its own size, because both ends are literals a clause is free to
 * contain. Exactly one `</b>` means it did not truncate early -- a bolded line inside the clause
 * would end the slice there and make every negative below vacuous. Nothing but whitespace after
 * that `</b>` means it did not swallow loose text: the last clause's region runs to the end of the
 * document, so without this a positive could be satisfied by a sentence sitting outside every
 * Permission the buyer agreed to. The window is not self-evident; it has to be measured.
 *
 * It still cannot see a sentence emitted ONCE for the whole document rather than per clause --
 * nothing between the Permission list opening and the first clause is in any region. That shape is
 * pinned by occurrence count instead; see `countOf`.
 */
const clauseBody = (license: string, anchor: string) => {
  const start = license.indexOf(anchor);
  if (start === -1) throw new Error(`clause not found: ${anchor}`);
  const next = license.indexOf('\n<b>', start + 1);
  const region = license.slice(start, next === -1 ? undefined : next);
  const closes = region.split('</b>').length - 1;
  if (closes !== 1) throw new Error(`clause region for ${anchor} holds ${closes} closing tags`);
  const trailing = region.slice(region.indexOf('</b>') + '</b>'.length);
  if (trailing.trim() !== '')
    throw new Error(`text after the close of ${anchor}, in no clause: ${JSON.stringify(trailing)}`);
  return region;
};

/**
 * Whole-document occurrence count. The region assertions say a sentence is in the right clause;
 * this says it is nowhere else -- which is the only form that survives a refactor moving it
 * somewhere no region covers.
 */
const countOf = (license: string, needle: string) => license.split(needle).length - 1;

const buildLicense = (
  allowCommercialUse: CommercialUse[],
  allowDerivatives = true,
  allowDifferentLicense = false,
  allowNoCredit = true
) =>
  addAdditionalLicensePermissions('', {
    modelId: 1,
    modelName: 'Test Model',
    versionId: 2,
    username: 'tester',
    allowNoCredit,
    allowDerivatives,
    allowDifferentLicense,
    allowCommercialUse,
  });

const OTHERS = [CommercialUse.Image, CommercialUse.RentCivit, CommercialUse.Rent];

/**
 * Every member a creator can be granted, derived from the enum rather than listed so a new one is
 * covered by the contract case without anyone remembering to add it here. `None` is excluded: it
 * is the marker for granting nothing, not a permission.
 */
const GRANTABLE = Object.values(CommercialUse).filter((v) => v !== CommercialUse.None);

describe('sell / sell-merge split in the generated licence', () => {
  it('grants both: neither restriction appears', () => {
    const license = buildLicense([...OTHERS, CommercialUse.Sell, CommercialUse.SellMerge]);

    // Nothing is emitted in this case, so the preamble is the only available positive control.
    expect(license).toContain(PERMISSION_LIST_OPENS);
    expect(license).not.toContain(MODEL_CLAUSE);
    expect(license).not.toContain(MERGE_CLAUSE);
    expect(license).not.toContain(SHARING_CLAUSE);
    expect(countOf(license, DISAPPLIES_TO_MERGES)).toBe(0);
  });

  it('grants Sell, withholds SellMerge: only the merge restriction appears', () => {
    const license = buildLicense([...OTHERS, CommercialUse.Sell]);

    expect(clauseBody(license, MERGE_CLAUSE)).toContain(FORBIDS_MERGE_SALE);
    expect(license).not.toContain(MODEL_CLAUSE);
    // The clause that picks merges back up must carry no carve-out, here or anywhere.
    expect(countOf(license, DISAPPLIES_TO_MERGES)).toBe(0);
  });

  it('withholds Sell, grants SellMerge: the model restriction appears AND excludes merges', () => {
    const license = buildLicense([...OTHERS, CommercialUse.SellMerge]);

    expect(clauseBody(license, MODEL_CLAUSE)).toContain(FORBIDS_MODEL_SALE);
    expect(clauseBody(license, MODEL_CLAUSE)).toContain(DISAPPLIES_TO_MERGES);
    expect(license).not.toContain(MERGE_CLAUSE);
    // ONCE, and inside that clause. Hoisted to document level -- the other way to write "every
    // clause says this" -- it lands between the Permission list and the first clause, which no
    // region covers, and disapplies every commercial restriction to any Merge.
    expect(countOf(license, DISAPPLIES_TO_MERGES)).toBe(1);
  });

  /**
   * The merge-sharing restriction comes from a different flag (allowDerivatives), so it and the
   * carve-out never render together anywhere else. The assertion that matters
   * is the NEGATIVE one: co-occurrence proves nothing, and a carve-out copied into the sharing
   * clause would say "do not share a Merge, except this does not apply to a Merge" -- which is
   * self-nullifying and which presence checks cannot see.
   */
  it('withholding derivatives does not let the sale carve-out reach the sharing clause', () => {
    const license = buildLicense(OTHERS, false);

    expect(license).toContain(SHARING_CLAUSE);
    expect(clauseBody(license, MODEL_CLAUSE)).toContain(DISAPPLIES_TO_MERGES);
    // Positive control on the sliced region: without it the negative below cannot distinguish the
    // sharing clause from whatever region an earlier occurrence of the anchor would land in.
    expect(clauseBody(license, SHARING_CLAUSE)).toContain(
      'Making a Merge available for deployment by another person'
    );
    expect(clauseBody(license, SHARING_CLAUSE)).not.toContain(DISAPPLIES_TO_MERGES);
    expect(countOf(license, DISAPPLIES_TO_MERGES)).toBe(1);
  });

  /**
   * The carve-out in Sale of the Model only works because the preamble expands a restriction
   * to Derivatives ONLY where the restriction references the Model, and yields where it states
   * its own scope. Restore the old flat sentence -- "The below restrictions apply to the Model
   * and Derivatives of the Model, even though only the Model is referenced" -- and the carve-out
   * stops working: a Merge is a Derivative, so the restriction reaches it again and the creator
   * gets a green tick over a licence that forbids the sale.
   */
  it('the preamble expands a restriction conditionally, and yields to a stated scope', () => {
    // No permissions: these sentences are unconditional, and passing OTHERS would imply otherwise.
    const license = buildLicense([]);

    // One contiguous literal on purpose: asserted as two fragments, the object of the sentence
    // and the conjunction are both free to change, and rewriting the middle stops every
    // restriction in the document reaching any Derivative while this still passes.
    // Asserted against the preamble region, not the document: these govern every clause, and a
    // sentence relocated into one clause would still satisfy a document-wide toContain while
    // silently ceasing to apply to the others.
    expect(preamble(license)).toContain(EXPANDS_CONDITIONALLY);
    expect(preamble(license)).toContain(MERGE_LINEAGE_SENTENCE);
    expect(preamble(license)).toContain(MERGE_DEFINED);
    expect(license).not.toContain('even though only the Model is referenced');

    // The preamble rewrite governs the other commercial restrictions too, and this is the only
    // case that renders them.
    expect(clauseBody(license, IMAGE_SALES_CLAUSE)).toContain(FORBIDS_IMAGE_SALE);
    expect(clauseBody(license, RENT_CLAUSE)).toContain(FORBIDS_RENT);
    expect(clauseBody(license, RENT_CIVIT_CLAUSE)).toContain(FORBIDS_RENT_CIVIT);

    // The carve-out belongs to the sale clause alone. Lifting it into a shared suffix -- the shape
    // an "every clause says this" refactor takes -- would disapply these three to any Merge, which
    // is a commercial grant the creator withheld, which the three positive assertions cannot see.
    expect(clauseBody(license, IMAGE_SALES_CLAUSE)).not.toContain(DISAPPLIES_TO_MERGES);
    expect(clauseBody(license, RENT_CLAUSE)).not.toContain(DISAPPLIES_TO_MERGES);
    expect(clauseBody(license, RENT_CIVIT_CLAUSE)).not.toContain(DISAPPLIES_TO_MERGES);
    // Three negatives over three regions still cannot see a fourth placement. The count can.
    expect(countOf(license, DISAPPLIES_TO_MERGES)).toBe(1);
  });

  it('withholds both: both restrictions appear', () => {
    const license = buildLicense(OTHERS);

    expect(clauseBody(license, MODEL_CLAUSE)).toContain(FORBIDS_MODEL_SALE);
    expect(clauseBody(license, MERGE_CLAUSE)).toContain(FORBIDS_MERGE_SALE);
    // The carve-out must not reach the clause that picks merges back up, or the pair cancels.
    expect(clauseBody(license, MERGE_CLAUSE)).not.toContain(DISAPPLIES_TO_MERGES);
    // Swap the two clause bodies under their headings and every other assertion here still holds.
    expect(clauseBody(license, MODEL_CLAUSE)).not.toContain(FORBIDS_MERGE_SALE);
    expect(clauseBody(license, MERGE_CLAUSE)).not.toContain(FORBIDS_MODEL_SALE);
    expect(preamble(license)).toContain(CARVE_OUT_GRANTS_NOTHING);
    expect(countOf(license, DISAPPLIES_TO_MERGES)).toBe(1);
  });

  /**
   * Changing Permissions is the one clause emitted by PRESENCE rather than absence, and the one
   * that grants where every other forbids -- so it is the one an absence-driven tidy-up inverts.
   * Both directions are asserted because the gate is what fails: rendering it to a creator who
   * withheld it tells buyers every restriction in the document, including both sale restrictions,
   * can be stripped from a Derivative.
   */
  it('Changing Permissions renders for the creator who granted it, and only them', () => {
    // Sliced, not document-wide: relocated into the preamble it would still satisfy a toContain
    // while becoming a general statement instead of a Permission gated on the creator's choice.
    expect(clauseBody(buildLicense(OTHERS, true, true), CHANGING_PERMISSIONS_CLAUSE)).toContain(
      CHANGING_PERMISSIONS
    );
    expect(buildLicense(OTHERS, true, false)).not.toContain(CHANGING_PERMISSIONS);
  });

  /**
   * Gated on allowNoCredit being false, so the same gate flip applies as to Changing Permissions.
   * All three links are pinned through their markdown TARGET, not just the display text: swapping
   * only the hrefs leaves every assertion on the names passing while the attribution every
   * downstream user is obliged to reproduce points at the wrong page.
   */
  it('Creator Credit renders for the creator who required it, crediting the right URLs', () => {
    const clause = clauseBody(buildLicense(OTHERS, true, false, false), CREATOR_CREDIT_CLAUSE);

    // The host is back-referenced, not matched twice independently: label and target are free to
    // name different origins otherwise, and the obligation is to reproduce the link as given.
    expect(clause).toMatch(
      /- Model: Test Model \[([^\]]*)\/models\/1\?modelVersionId=2\]\(\1\/models\/1\?modelVersionId=2\)/
    );
    expect(clause).toMatch(/- Creator: tester \[([^\]]*)\/user\/tester\]\(\1\/user\/tester\)/);
    expect(clause).toMatch(/- License: \[([^\]]*)\/models\/license\/2\]\(\1\/models\/license\/2\)/);

    expect(buildLicense(OTHERS, true, false, true)).not.toContain(CREATOR_CREDIT_CLAUSE);
  });

  /**
   * The invariant is that the three places agree, NOT that every member is granted by default.
   * Shipping a new member withheld for a deploy is a legitimate and recently-used manoeuvre, and a
   * test demanding every member appear in the defaults would forbid it.
   *
   * What must never diverge: a member in the default sets but absent from the option list is
   * granted to every new model and unrevokable through the product, and the two default sets
   * disagreeing means the form shows a creator something the database will not give them.
   */
  it('the two default sets and the option list agree on which members are granted', () => {
    const members = (capture: string) =>
      capture
        .replace(/\/\/[^\n]*/g, '')
        .split(',')
        .map((s) => s.trim().replace(/^CommercialUse\./, ''))
        .filter(Boolean);

    const schema = readFileSync(
      join(__dirname, '../../../../packages/civitai-db-schema/prisma/schema.full.prisma'),
      'utf8'
    );
    // matchAll with a length check: `.match` pins the FIRST occurrence, so a second model carrying
    // its own default would be invisible to every assertion below.
    const modelDefaults = [
      ...schema.matchAll(/allowCommercialUse\s+CommercialUse\[\]\s+@default\(\[(.*)\]\)/g),
    ];
    expect(modelDefaults).toHaveLength(1);
    const modelDefault = modelDefaults[0];
    // Set rather than exact string: `prisma format` may reorder or respace this line, and a guard
    // that reddens on formatting is one the third person to hit it deletes.
    const schemaMembers = members(modelDefault?.[1] ?? '').sort();
    // A floor, so the three-way comparison below cannot be satisfied by three empty sets.
    expect(schemaMembers.length).toBeGreaterThanOrEqual(4);

    const form = readFileSync(
      join(__dirname, '../../../components/Resource/Forms/ModelUpsertForm.tsx'),
      'utf8'
    );
    // Anchored on the statement's end, not on the first `]`: a capture stopping at the bracket
    // cannot see `?? [...].concat(SellMerge)`, which puts the value back with the literal intact.
    const formDefault = form.match(
      /allowCommercialUse: model\?\.allowCommercialUse \?\? \[([\s\S]*?)\],\n/
    );
    expect(formDefault).not.toBeNull();
    expect(members(formDefault?.[1] ?? '').sort()).toEqual(schemaMembers);

    // The default decides what a creator gets without choosing; the option list decides what they
    // CAN choose. A member present in the default but absent here is grantable only by accident and
    // unrevokable through the product.
    const options = form.match(/const commercialUseOptions[\s\S]*?=\s*\[([\s\S]*?)\n\];/);
    expect(options).not.toBeNull();
    const offered = [...(options?.[1] ?? '').matchAll(/value:\s*CommercialUse\.(\w+)/g)].map(
      (m) => m[1]
    );
    expect(offered.sort()).toEqual(schemaMembers);

    // The literal is not what a creator sees. A `.filter()` at the render site, or the member named
    // in the `disabled` predicate, removes the checkbox while the schema default still grants the
    // permission -- so it is granted by accident and unrevokable through the product, which is the
    // harm the comment above describes. Neither touches the array, so every assertion above stays
    // green -- the array is not what a creator sees. This reaches one step further, to the render
    // site, and pins only that it maps the list whole.
    //
    // 🔴 It does NOT cover the `disabled` predicate, which can render a checkbox nobody can use.
    // A text guard cannot express that without naming members, and naming members reintroduces the
    // policy this case exists to avoid. The honest instrument is a component test mounting the form
    // and asserting one enabled checkbox per granted member; there is none today, for this form or
    // any other. Filed rather than papered over.
    const render = form.slice(form.indexOf('<Checkbox.Group'), form.indexOf('</Checkbox.Group>'));
    expect(render).toContain('commercialUseOptions.map(');
    expect(render).not.toMatch(/commercialUseOptions[\s\S]{0,40}?\.(filter|slice)\(/);

    // A name-pinned guard, not a behavioural one: the refine that withheld a member was called
    // this. The behaviour is covered by the accept-loop in the next case.
    const schemaSrc = readFileSync(join(__dirname, '../../schema/model.schema.ts'), 'utf8');
    expect(schemaSrc).not.toMatch(/WITHHELD_COMMERCIAL_USE/);
  });

  /**
   * The list above is a source-text assertion; this one runs the contract. A text guard cannot tell
   * a member being accepted from a field that stopped validating.
   */
  it('the upsert contract accepts every grantable member, and still rejects a bogus one', async () => {
    const { modelUpsertSchema } = await import('~/server/schema/model.schema');
    const base = { name: 'x', type: 'Checkpoint', status: 'Draft', uploadType: 'Created' };

    // A floor, not a list: an empty GRANTABLE makes the loop below assert nothing at all.
    expect(GRANTABLE.length).toBeGreaterThanOrEqual(5);
    for (const member of GRANTABLE) {
      const parsed = modelUpsertSchema.safeParse({ ...base, allowCommercialUse: [member] });
      expect(parsed.success, `${member} should be writable`).toBe(true);
    }
    expect(modelUpsertSchema.safeParse({ ...base, allowCommercialUse: GRANTABLE }).success).toBe(
      true
    );

    // The negative half, and it is what stops the loop above passing because the field stopped
    // validating at all. A member that is not in the enum must still be refused.
    expect(
      modelUpsertSchema.safeParse({ ...base, allowCommercialUse: ['SellTheMoon'] }).success
    ).toBe(false);
  });

  /**
   * The slicers must fail rather than narrow: `clauseBody` returning '' and `preamble` returning
   * `slice(0, -1)` both leave every negative assertion above passing for free.
   */
  it('the slicers refuse a document they cannot find their anchor in', () => {
    expect(() => clauseBody('nothing here', MODEL_CLAUSE)).toThrow(/clause not found/);
    expect(() => preamble('nothing here')).toThrow(/preamble anchor not found/);
  });
});
