import { FileWithPath } from '@mantine/dropzone';
import exifr from 'exifr';
import { ImageMetaProps, imageMetaSchema } from '~/server/schema/image.schema';

export async function getMetadata(file: FileWithPath) {
  let exif: any; //eslint-disable-line
  try {
    exif = await exifr.parse(file, {
      userComment: true,
    });
  } catch (e: any) { //eslint-disable-line
    return {};
  }
  let generationDetails = null;
  if (exif?.userComment) {
    const p = document.createElement('p');
    generationDetails = decoder.decode(exif.userComment);
    // Any annoying hack to deal with weirdness in the meta
    p.innerHTML = generationDetails;
    p.remove();
    generationDetails = p.innerHTML;
  } else if (exif?.parameters) {
    generationDetails = exif.parameters;
  }

  const metadata = parseMetadata(generationDetails);
  const result = imageMetaSchema.safeParse(metadata);
  return result.success ? result.data : {};
}

// #region [infra]
function parseMetadata(meta: string): Record<string, unknown> {
  if (!meta) return {};
  meta = meta.replace('UNICODE', '');
  const { parse } = parsers.find((x) => x.canHandle(meta)) ?? {};
  if (!parse) return {};

  return parse(meta);
}

type MetadataParser = {
  canHandle: (meta: string) => boolean;
  parse: (meta: string) => ImageMetaProps;
};

function createMetadataParser(
  canHandle: MetadataParser['canHandle'],
  parse: MetadataParser['parse']
): MetadataParser {
  return {
    canHandle,
    parse,
  };
}

const decoder = new TextDecoder('utf-8');
// #endregion

// #region [parsers]
const automaticSDKeyMap = new Map<string, keyof ImageMetaProps>([
  ['Seed', 'seed'],
  ['CFG scale', 'cfgScale'],
  ['Sampler', 'sampler'],
  ['Steps', 'steps'],
]);
const automaticSDParser = createMetadataParser(
  (meta: string) => meta.includes('Steps: '),
  (meta: string) => {
    const metadata: ImageMetaProps = {};
    if (!meta) return metadata;
    const metaLines = meta.split('\n');
    const fineDetails =
      metaLines
        .pop()
        ?.split(',')
        .map((x) => x.split(':')) ?? [];
    for (const [k, v] of fineDetails) {
      if (!v) continue;
      const propKey = automaticSDKeyMap.get(k.trim()) ?? k.trim();
      metadata[propKey] = v.trim();
    }

    const [prompt, negativePrompt] = metaLines
      .join('\n')
      .split('Negative prompt:')
      .map((x) => x.trim());
    metadata.prompt = prompt;
    metadata.negativePrompt = negativePrompt;
    return metadata;
  }
);
const parsers = [automaticSDParser];
// #endregion

// #region [encoders]
export function encodeMetadata(
  metadata: ImageMetaProps,
  encoder: keyof typeof encoders = 'automatic1111'
) {
  return encoders[encoder](metadata);
}

const automaticSDEncodeMap = new Map<keyof ImageMetaProps, string>(
  Array.from(automaticSDKeyMap, (a) => a.reverse()) as Iterable<readonly [string, string]>
);
function automaticEncoder({ prompt, negativePrompt, ...other }: ImageMetaProps) {
  const lines = [prompt];
  if (negativePrompt) lines.push(`Negative prompt: ${negativePrompt}`);
  const fineDetails = [];
  for (const [k, v] of Object.entries(other)) {
    const key = automaticSDEncodeMap.get(k) ?? k;
    fineDetails.push(`${key}: ${v}`);
  }
  if (fineDetails.length > 0) lines.push(fineDetails.join(', '));

  return lines.join('\n');
}

const encoders = {
  automatic1111: automaticEncoder,
};
// #endregion

// #region [audit]
export const auditMetaData = (meta: AsyncReturnType<typeof getMetadata>) => {
  const blockedFor = blocked.filter((item) => meta.prompt?.includes(item));
  return { success: !blockedFor.length };
};

const blocked = [
  '1 y.o.',
  '1 year old',
  '1 yearold',
  '1 years old',
  '1 yearsold',
  '1 yo',
  '1,y,o,',
  '1,year,old',
  '1,yearold',
  '1,years,old',
  '1,yearsold',
  '1,yo',
  '1-y-o-',
  '1-year-old',
  '1-yearold',
  '1-years-old',
  '1-yearsold',
  '1-yo',
  '1.y.o.',
  '1.year.old',
  '1.yearold',
  '1.years.old',
  '1.yearsold',
  '1.yo',
  '10 y.o.',
  '10 year old',
  '10 yearold',
  '10 years old',
  '10 yearsold',
  '10 yo',
  '10,y,o,',
  '10,year,old',
  '10,yearold',
  '10,years,old',
  '10,yearsold',
  '10,yo',
  '10-y-o-',
  '10-year-old',
  '10-yearold',
  '10-years-old',
  '10-yearsold',
  '10-yo',
  '10.y.o.',
  '10.year.old',
  '10.yearold',
  '10.years.old',
  '10.yearsold',
  '10.yo',
  '10_y_o_',
  '10_year_old',
  '10_yearold',
  '10_years_old',
  '10_yearsold',
  '10_yo',
  '10y,o,',
  '10y-o-',
  '10y.o.',
  '10y_o_',
  '10year old',
  '10year,old',
  '10year-old',
  '10year.old',
  '10year_old',
  '10yearold',
  '10years old',
  '10years,old',
  '10years-old',
  '10years.old',
  '10years_old',
  '10yearsold',
  '10yo',
  '11 y.o.',
  '11 year old',
  '11 yearold',
  '11 years old',
  '11 yearsold',
  '11 yo',
  '11,y,o,',
  '11,year,old',
  '11,yearold',
  '11,years,old',
  '11,yearsold',
  '11,yo',
  '11-y-o-',
  '11-year-old',
  '11-yearold',
  '11-years-old',
  '11-yearsold',
  '11-yo',
  '11.y.o.',
  '11.year.old',
  '11.yearold',
  '11.years.old',
  '11.yearsold',
  '11.yo',
  '11_y_o_',
  '11_year_old',
  '11_yearold',
  '11_years_old',
  '11_yearsold',
  '11_yo',
  '11y,o,',
  '11y-o-',
  '11y.o.',
  '11y_o_',
  '11year old',
  '11year,old',
  '11year-old',
  '11year.old',
  '11year_old',
  '11yearold',
  '11years old',
  '11years,old',
  '11years-old',
  '11years.old',
  '11years_old',
  '11yearsold',
  '11yo',
  '12 y.o.',
  '12 year old',
  '12 yearold',
  '12 years old',
  '12 yearsold',
  '12 yo',
  '12,y,o,',
  '12,year,old',
  '12,yearold',
  '12,years,old',
  '12,yearsold',
  '12,yo',
  '12-y-o-',
  '12-year-old',
  '12-yearold',
  '12-years-old',
  '12-yearsold',
  '12-yo',
  '12.y.o.',
  '12.year.old',
  '12.yearold',
  '12.years.old',
  '12.yearsold',
  '12.yo',
  '12_y_o_',
  '12_year_old',
  '12_yearold',
  '12_years_old',
  '12_yearsold',
  '12_yo',
  '12y,o,',
  '12y-o-',
  '12y.o.',
  '12y_o_',
  '12year old',
  '12year,old',
  '12year-old',
  '12year.old',
  '12year_old',
  '12yearold',
  '12years old',
  '12years,old',
  '12years-old',
  '12years.old',
  '12years_old',
  '12yearsold',
  '12yo',
  '13 y.o.',
  '13 year old',
  '13 yearold',
  '13 years old',
  '13 yearsold',
  '13 yo',
  '13,y,o,',
  '13,year,old',
  '13,yearold',
  '13,years,old',
  '13,yearsold',
  '13,yo',
  '13-y-o-',
  '13-year-old',
  '13-yearold',
  '13-years-old',
  '13-yearsold',
  '13-yo',
  '13.y.o.',
  '13.year.old',
  '13.yearold',
  '13.years.old',
  '13.yearsold',
  '13.yo',
  '13_y_o_',
  '13_year_old',
  '13_yearold',
  '13_years_old',
  '13_yearsold',
  '13_yo',
  '13y,o,',
  '13y-o-',
  '13y.o.',
  '13y_o_',
  '13year old',
  '13year,old',
  '13year-old',
  '13year.old',
  '13year_old',
  '13yearold',
  '13years old',
  '13years,old',
  '13years-old',
  '13years.old',
  '13years_old',
  '13yearsold',
  '13yo',
  '14 y.o.',
  '14 year old',
  '14 yearold',
  '14 years old',
  '14 yearsold',
  '14 yo',
  '14,y,o,',
  '14,year,old',
  '14,yearold',
  '14,years,old',
  '14,yearsold',
  '14,yo',
  '14-y-o-',
  '14-year-old',
  '14-yearold',
  '14-years-old',
  '14-yearsold',
  '14-yo',
  '14.y.o.',
  '14.year.old',
  '14.yearold',
  '14.years.old',
  '14.yearsold',
  '14.yo',
  '14_y_o_',
  '14_year_old',
  '14_yearold',
  '14_years_old',
  '14_yearsold',
  '14_yo',
  '14y,o,',
  '14y-o-',
  '14y.o.',
  '14y_o_',
  '14year old',
  '14year,old',
  '14year-old',
  '14year.old',
  '14year_old',
  '14yearold',
  '14years old',
  '14years,old',
  '14years-old',
  '14years.old',
  '14years_old',
  '14yearsold',
  '14yo',
  '15 y.o.',
  '15 year old',
  '15 yearold',
  '15 years old',
  '15 yearsold',
  '15 yo',
  '15,y,o,',
  '15,year,old',
  '15,yearold',
  '15,years,old',
  '15,yearsold',
  '15,yo',
  '15-y-o-',
  '15-year-old',
  '15-yearold',
  '15-years-old',
  '15-yearsold',
  '15-yo',
  '15.y.o.',
  '15.year.old',
  '15.yearold',
  '15.years.old',
  '15.yearsold',
  '15.yo',
  '15_y_o_',
  '15_year_old',
  '15_yearold',
  '15_years_old',
  '15_yearsold',
  '15_yo',
  '15y,o,',
  '15y-o-',
  '15y.o.',
  '15y_o_',
  '15year old',
  '15year,old',
  '15year-old',
  '15year.old',
  '15year_old',
  '15yearold',
  '15years old',
  '15years,old',
  '15years-old',
  '15years.old',
  '15years_old',
  '15yearsold',
  '15yo',
  '16 y.o.',
  '16 year old',
  '16 yearold',
  '16 years old',
  '16 yearsold',
  '16 yo',
  '16,y,o,',
  '16,year,old',
  '16,yearold',
  '16,years,old',
  '16,yearsold',
  '16,yo',
  '16-y-o-',
  '16-year-old',
  '16-yearold',
  '16-years-old',
  '16-yearsold',
  '16-yo',
  '16.y.o.',
  '16.year.old',
  '16.yearold',
  '16.years.old',
  '16.yearsold',
  '16.yo',
  '16_y_o_',
  '16_year_old',
  '16_yearold',
  '16_years_old',
  '16_yearsold',
  '16_yo',
  '16y,o,',
  '16y-o-',
  '16y.o.',
  '16y_o_',
  '16year old',
  '16year,old',
  '16year-old',
  '16year.old',
  '16year_old',
  '16yearold',
  '16years old',
  '16years,old',
  '16years-old',
  '16years.old',
  '16years_old',
  '16yearsold',
  '16yo',
  '17 y.o.',
  '17 year old',
  '17 yearold',
  '17 years old',
  '17 yearsold',
  '17 yo',
  '17,y,o,',
  '17,year,old',
  '17,yearold',
  '17,years,old',
  '17,yearsold',
  '17,yo',
  '17-y-o-',
  '17-year-old',
  '17-yearold',
  '17-years-old',
  '17-yearsold',
  '17-yo',
  '17.y.o.',
  '17.year.old',
  '17.yearold',
  '17.years.old',
  '17.yearsold',
  '17.yo',
  '17_y_o_',
  '17_year_old',
  '17_yearold',
  '17_years_old',
  '17_yearsold',
  '17_yo',
  '17y,o,',
  '17y-o-',
  '17y.o.',
  '17y_o_',
  '17year old',
  '17year,old',
  '17year-old',
  '17year.old',
  '17year_old',
  '17yearold',
  '17years old',
  '17years,old',
  '17years-old',
  '17years.old',
  '17years_old',
  '17yearsold',
  '17yo',
  '18 y.o.',
  '18 year old',
  '18 yearold',
  '18 years old',
  '18 yearsold',
  '18 yo',
  '18,y,o,',
  '18,year,old',
  '18,yearold',
  '18,years,old',
  '18,yearsold',
  '18,yo',
  '18-y-o-',
  '18-year-old',
  '18-yearold',
  '18-years-old',
  '18-yearsold',
  '18-yo',
  '18.y.o.',
  '18.year.old',
  '18.yearold',
  '18.years.old',
  '18.yearsold',
  '18.yo',
  '18_y_o_',
  '18_year_old',
  '18_yearold',
  '18_years_old',
  '18_yearsold',
  '18_yo',
  '18y,o,',
  '18y-o-',
  '18y.o.',
  '18y_o_',
  '18year old',
  '18year,old',
  '18year-old',
  '18year.old',
  '18year_old',
  '18yearold',
  '18years old',
  '18years,old',
  '18years-old',
  '18years.old',
  '18years_old',
  '18yearsold',
  '18yo',
  '1_y_o_',
  '1_year_old',
  '1_yearold',
  '1_years_old',
  '1_yearsold',
  '1_yo',
  '1y,o,',
  '1y-o-',
  '1y.o.',
  '1y_o_',
  '1year old',
  '1year,old',
  '1year-old',
  '1year.old',
  '1year_old',
  '1yearold',
  '1years old',
  '1years,old',
  '1years-old',
  '1years.old',
  '1years_old',
  '1yearsold',
  '1yo',
  '2 y.o.',
  '2 year old',
  '2 yearold',
  '2 years old',
  '2 yearsold',
  '2 yo',
  '2,y,o,',
  '2,year,old',
  '2,yearold',
  '2,years,old',
  '2,yearsold',
  '2,yo',
  '2-y-o-',
  '2-year-old',
  '2-yearold',
  '2-years-old',
  '2-yearsold',
  '2-yo',
  '2.y.o.',
  '2.year.old',
  '2.yearold',
  '2.years.old',
  '2.yearsold',
  '2.yo',
  '2_y_o_',
  '2_year_old',
  '2_yearold',
  '2_years_old',
  '2_yearsold',
  '2_yo',
  '2y,o,',
  '2y-o-',
  '2y.o.',
  '2y_o_',
  '2year old',
  '2year,old',
  '2year-old',
  '2year.old',
  '2year_old',
  '2yearold',
  '2years old',
  '2years,old',
  '2years-old',
  '2years.old',
  '2years_old',
  '2yearsold',
  '2yo',
  '3 y.o.',
  '3 year old',
  '3 yearold',
  '3 years old',
  '3 yearsold',
  '3 yo',
  '3,y,o,',
  '3,year,old',
  '3,yearold',
  '3,years,old',
  '3,yearsold',
  '3,yo',
  '3-y-o-',
  '3-year-old',
  '3-yearold',
  '3-years-old',
  '3-yearsold',
  '3-yo',
  '3.y.o.',
  '3.year.old',
  '3.yearold',
  '3.years.old',
  '3.yearsold',
  '3.yo',
  '3_y_o_',
  '3_year_old',
  '3_yearold',
  '3_years_old',
  '3_yearsold',
  '3_yo',
  '3y,o,',
  '3y-o-',
  '3y.o.',
  '3y_o_',
  '3year old',
  '3year,old',
  '3year-old',
  '3year.old',
  '3year_old',
  '3yearold',
  '3years old',
  '3years,old',
  '3years-old',
  '3years.old',
  '3years_old',
  '3yearsold',
  '3yo',
  '4 y.o.',
  '4 year old',
  '4 yearold',
  '4 years old',
  '4 yearsold',
  '4 yo',
  '4,y,o,',
  '4,year,old',
  '4,yearold',
  '4,years,old',
  '4,yearsold',
  '4,yo',
  '4-y-o-',
  '4-year-old',
  '4-yearold',
  '4-years-old',
  '4-yearsold',
  '4-yo',
  '4.y.o.',
  '4.year.old',
  '4.yearold',
  '4.years.old',
  '4.yearsold',
  '4.yo',
  '4_y_o_',
  '4_year_old',
  '4_yearold',
  '4_years_old',
  '4_yearsold',
  '4_yo',
  '4y,o,',
  '4y-o-',
  '4y.o.',
  '4y_o_',
  '4year old',
  '4year,old',
  '4year-old',
  '4year.old',
  '4year_old',
  '4yearold',
  '4years old',
  '4years,old',
  '4years-old',
  '4years.old',
  '4years_old',
  '4yearsold',
  '4yo',
  '5 y.o.',
  '5 year old',
  '5 yearold',
  '5 years old',
  '5 yearsold',
  '5 yo',
  '5,y,o,',
  '5,year,old',
  '5,yearold',
  '5,years,old',
  '5,yearsold',
  '5,yo',
  '5-y-o-',
  '5-year-old',
  '5-yearold',
  '5-years-old',
  '5-yearsold',
  '5-yo',
  '5.y.o.',
  '5.year.old',
  '5.yearold',
  '5.years.old',
  '5.yearsold',
  '5.yo',
  '5_y_o_',
  '5_year_old',
  '5_yearold',
  '5_years_old',
  '5_yearsold',
  '5_yo',
  '5y,o,',
  '5y-o-',
  '5y.o.',
  '5y_o_',
  '5year old',
  '5year,old',
  '5year-old',
  '5year.old',
  '5year_old',
  '5yearold',
  '5years old',
  '5years,old',
  '5years-old',
  '5years.old',
  '5years_old',
  '5yearsold',
  '5yo',
  '6 y.o.',
  '6 year old',
  '6 yearold',
  '6 years old',
  '6 yearsold',
  '6 yo',
  '6,y,o,',
  '6,year,old',
  '6,yearold',
  '6,years,old',
  '6,yearsold',
  '6,yo',
  '6-y-o-',
  '6-year-old',
  '6-yearold',
  '6-years-old',
  '6-yearsold',
  '6-yo',
  '6.y.o.',
  '6.year.old',
  '6.yearold',
  '6.years.old',
  '6.yearsold',
  '6.yo',
  '6_y_o_',
  '6_year_old',
  '6_yearold',
  '6_years_old',
  '6_yearsold',
  '6_yo',
  '6y,o,',
  '6y-o-',
  '6y.o.',
  '6y_o_',
  '6year old',
  '6year,old',
  '6year-old',
  '6year.old',
  '6year_old',
  '6yearold',
  '6years old',
  '6years,old',
  '6years-old',
  '6years.old',
  '6years_old',
  '6yearsold',
  '6yo',
  '7 y.o.',
  '7 year old',
  '7 yearold',
  '7 years old',
  '7 yearsold',
  '7 yo',
  '7,y,o,',
  '7,year,old',
  '7,yearold',
  '7,years,old',
  '7,yearsold',
  '7,yo',
  '7-y-o-',
  '7-year-old',
  '7-yearold',
  '7-years-old',
  '7-yearsold',
  '7-yo',
  '7.y.o.',
  '7.year.old',
  '7.yearold',
  '7.years.old',
  '7.yearsold',
  '7.yo',
  '7_y_o_',
  '7_year_old',
  '7_yearold',
  '7_years_old',
  '7_yearsold',
  '7_yo',
  '7y,o,',
  '7y-o-',
  '7y.o.',
  '7y_o_',
  '7year old',
  '7year,old',
  '7year-old',
  '7year.old',
  '7year_old',
  '7yearold',
  '7years old',
  '7years,old',
  '7years-old',
  '7years.old',
  '7years_old',
  '7yearsold',
  '7yo',
  '8 y.o.',
  '8 year old',
  '8 yearold',
  '8 years old',
  '8 yearsold',
  '8 yo',
  '8,y,o,',
  '8,year,old',
  '8,yearold',
  '8,years,old',
  '8,yearsold',
  '8,yo',
  '8-y-o-',
  '8-year-old',
  '8-yearold',
  '8-years-old',
  '8-yearsold',
  '8-yo',
  '8.y.o.',
  '8.year.old',
  '8.yearold',
  '8.years.old',
  '8.yearsold',
  '8.yo',
  '8_y_o_',
  '8_year_old',
  '8_yearold',
  '8_years_old',
  '8_yearsold',
  '8_yo',
  '8y,o,',
  '8y-o-',
  '8y.o.',
  '8y_o_',
  '8year old',
  '8year,old',
  '8year-old',
  '8year.old',
  '8year_old',
  '8yearold',
  '8years old',
  '8years,old',
  '8years-old',
  '8years.old',
  '8years_old',
  '8yearsold',
  '8yo',
  '9 y.o.',
  '9 year old',
  '9 yearold',
  '9 years old',
  '9 yearsold',
  '9 yo',
  '9,y,o,',
  '9,year,old',
  '9,yearold',
  '9,years,old',
  '9,yearsold',
  '9,yo',
  '9-y-o-',
  '9-year-old',
  '9-yearold',
  '9-years-old',
  '9-yearsold',
  '9-yo',
  '9.y.o.',
  '9.year.old',
  '9.yearold',
  '9.years.old',
  '9.yearsold',
  '9.yo',
  '9_y_o_',
  '9_year_old',
  '9_yearold',
  '9_years_old',
  '9_yearsold',
  '9_yo',
  '9y,o,',
  '9y-o-',
  '9y.o.',
  '9y_o_',
  '9year old',
  '9year,old',
  '9year-old',
  '9year.old',
  '9year_old',
  '9yearold',
  '9years old',
  '9years,old',
  '9years-old',
  '9years.old',
  '9years_old',
  '9yearsold',
  '9yo',
  'Cave Nigger',
  'adolescent',
  'africoon',
  'africoons',
  'akata',
  'akatas',
  'babies',
  'baby',
  'baby doll',
  'baby-boy',
  'baby-girl',
  'babyboy',
  'babyboys',
  'babydoll',
  'babygirl',
  'babygirls',
  'babyish',
  'babylike',
  'beaner',
  'beaners',
  'beastial',
  'beastiality',
  'bestial',
  'bestiality',
  'boy',
  'boyish',
  'browntown',
  'chibi',
  'chigger',
  'child',
  'childlike',
  'children',
  'chink',
  'chinks',
  'coon',
  'coonass',
  'coonasses',
  'coons',
  'corpse',
  'darkie',
  'darkies',
  'daughter',
  'dead',
  'dike',
  'dog-fucker',
  'doll',
  'dolls',
  'dune coon',
  'dune coons',
  'dyke',
  'eight y.o.',
  'eight year old',
  'eight yearold',
  'eight years old',
  'eight yearsold',
  'eight yo',
  'eight,y,o,',
  'eight,year,old',
  'eight,yearold',
  'eight,years,old',
  'eight,yearsold',
  'eight,yo',
  'eight-y-o-',
  'eight-year-old',
  'eight-yearold',
  'eight-years-old',
  'eight-yearsold',
  'eight-yo',
  'eight.y.o.',
  'eight.year.old',
  'eight.yearold',
  'eight.years.old',
  'eight.yearsold',
  'eight.yo',
  'eight_y_o_',
  'eight_year_old',
  'eight_yearold',
  'eight_years_old',
  'eight_yearsold',
  'eight_yo',
  'eighteen y.o.',
  'eighteen year old',
  'eighteen yearold',
  'eighteen years old',
  'eighteen yearsold',
  'eighteen yo',
  'eighteen,y,o,',
  'eighteen,year,old',
  'eighteen,yearold',
  'eighteen,years,old',
  'eighteen,yearsold',
  'eighteen,yo',
  'eighteen-y-o-',
  'eighteen-year-old',
  'eighteen-yearold',
  'eighteen-years-old',
  'eighteen-yearsold',
  'eighteen-yo',
  'eighteen.y.o.',
  'eighteen.year.old',
  'eighteen.yearold',
  'eighteen.years.old',
  'eighteen.yearsold',
  'eighteen.yo',
  'eighteen_y_o_',
  'eighteen_year_old',
  'eighteen_yearold',
  'eighteen_years_old',
  'eighteen_yearsold',
  'eighteen_yo',
  'eighteeny,o,',
  'eighteeny-o-',
  'eighteeny.o.',
  'eighteeny_o_',
  'eighteenyear old',
  'eighteenyear,old',
  'eighteenyear-old',
  'eighteenyear.old',
  'eighteenyear_old',
  'eighteenyearold',
  'eighteenyears old',
  'eighteenyears,old',
  'eighteenyears-old',
  'eighteenyears.old',
  'eighteenyears_old',
  'eighteenyearsold',
  'eighteenyo',
  'eighty,o,',
  'eighty-o-',
  'eighty.o.',
  'eighty_o_',
  'eightyear old',
  'eightyear,old',
  'eightyear-old',
  'eightyear.old',
  'eightyear_old',
  'eightyearold',
  'eightyears old',
  'eightyears,old',
  'eightyears-old',
  'eightyears.old',
  'eightyears_old',
  'eightyearsold',
  'eightyo',
  'eleven y.o.',
  'eleven year old',
  'eleven yearold',
  'eleven years old',
  'eleven yearsold',
  'eleven yo',
  'eleven,y,o,',
  'eleven,year,old',
  'eleven,yearold',
  'eleven,years,old',
  'eleven,yearsold',
  'eleven,yo',
  'eleven-y-o-',
  'eleven-year-old',
  'eleven-yearold',
  'eleven-years-old',
  'eleven-yearsold',
  'eleven-yo',
  'eleven.y.o.',
  'eleven.year.old',
  'eleven.yearold',
  'eleven.years.old',
  'eleven.yearsold',
  'eleven.yo',
  'eleven_y_o_',
  'eleven_year_old',
  'eleven_yearold',
  'eleven_years_old',
  'eleven_yearsold',
  'eleven_yo',
  'eleveny,o,',
  'eleveny-o-',
  'eleveny.o.',
  'eleveny_o_',
  'elevenyear old',
  'elevenyear,old',
  'elevenyear-old',
  'elevenyear.old',
  'elevenyear_old',
  'elevenyearold',
  'elevenyears old',
  'elevenyears,old',
  'elevenyears-old',
  'elevenyears.old',
  'elevenyears_old',
  'elevenyearsold',
  'elevenyo',
  'fag',
  'fagget',
  'fagging',
  'faggit',
  'faggitt',
  'faggot',
  'faggs',
  'fagot',
  'fagots',
  'fags',
  'fairy',
  'feg',
  'fifteen y.o.',
  'fifteen year old',
  'fifteen yearold',
  'fifteen years old',
  'fifteen yearsold',
  'fifteen yo',
  'fifteen,y,o,',
  'fifteen,year,old',
  'fifteen,yearold',
  'fifteen,years,old',
  'fifteen,yearsold',
  'fifteen,yo',
  'fifteen-y-o-',
  'fifteen-year-old',
  'fifteen-yearold',
  'fifteen-years-old',
  'fifteen-yearsold',
  'fifteen-yo',
  'fifteen.y.o.',
  'fifteen.year.old',
  'fifteen.yearold',
  'fifteen.years.old',
  'fifteen.yearsold',
  'fifteen.yo',
  'fifteen_y_o_',
  'fifteen_year_old',
  'fifteen_yearold',
  'fifteen_years_old',
  'fifteen_yearsold',
  'fifteen_yo',
  'fifteeny,o,',
  'fifteeny-o-',
  'fifteeny.o.',
  'fifteeny_o_',
  'fifteenyear old',
  'fifteenyear,old',
  'fifteenyear-old',
  'fifteenyear.old',
  'fifteenyear_old',
  'fifteenyearold',
  'fifteenyears old',
  'fifteenyears,old',
  'fifteenyears-old',
  'fifteenyears.old',
  'fifteenyears_old',
  'fifteenyearsold',
  'fifteenyo',
  'five y.o.',
  'five year old',
  'five yearold',
  'five years old',
  'five yearsold',
  'five yo',
  'five,y,o,',
  'five,year,old',
  'five,yearold',
  'five,years,old',
  'five,yearsold',
  'five,yo',
  'five-y-o-',
  'five-year-old',
  'five-yearold',
  'five-years-old',
  'five-yearsold',
  'five-yo',
  'five.y.o.',
  'five.year.old',
  'five.yearold',
  'five.years.old',
  'five.yearsold',
  'five.yo',
  'five_y_o_',
  'five_year_old',
  'five_yearold',
  'five_years_old',
  'five_yearsold',
  'five_yo',
  'fivey,o,',
  'fivey-o-',
  'fivey.o.',
  'fivey_o_',
  'fiveyear old',
  'fiveyear,old',
  'fiveyear-old',
  'fiveyear.old',
  'fiveyear_old',
  'fiveyearold',
  'fiveyears old',
  'fiveyears,old',
  'fiveyears-old',
  'fiveyears.old',
  'fiveyears_old',
  'fiveyearsold',
  'fiveyo',
  'flat chest',
  'flat chested',
  'flat-chest',
  'flat-chested',
  'flat.chest',
  'flat.chested',
  'flat_chest',
  'flat_chested',
  'flatchest',
  'flatchested',
  'four y.o.',
  'four year old',
  'four yearold',
  'four years old',
  'four yearsold',
  'four yo',
  'four,y,o,',
  'four,year,old',
  'four,yearold',
  'four,years,old',
  'four,yearsold',
  'four,yo',
  'four-y-o-',
  'four-year-old',
  'four-yearold',
  'four-years-old',
  'four-yearsold',
  'four-yo',
  'four.y.o.',
  'four.year.old',
  'four.yearold',
  'four.years.old',
  'four.yearsold',
  'four.yo',
  'four_y_o_',
  'four_year_old',
  'four_yearold',
  'four_years_old',
  'four_yearsold',
  'four_yo',
  'fourteen y.o.',
  'fourteen year old',
  'fourteen yearold',
  'fourteen years old',
  'fourteen yearsold',
  'fourteen yo',
  'fourteen,y,o,',
  'fourteen,year,old',
  'fourteen,yearold',
  'fourteen,years,old',
  'fourteen,yearsold',
  'fourteen,yo',
  'fourteen-y-o-',
  'fourteen-year-old',
  'fourteen-yearold',
  'fourteen-years-old',
  'fourteen-yearsold',
  'fourteen-yo',
  'fourteen.y.o.',
  'fourteen.year.old',
  'fourteen.yearold',
  'fourteen.years.old',
  'fourteen.yearsold',
  'fourteen.yo',
  'fourteen_y_o_',
  'fourteen_year_old',
  'fourteen_yearold',
  'fourteen_years_old',
  'fourteen_yearsold',
  'fourteen_yo',
  'fourteeny,o,',
  'fourteeny-o-',
  'fourteeny.o.',
  'fourteeny_o_',
  'fourteenyear old',
  'fourteenyear,old',
  'fourteenyear-old',
  'fourteenyear.old',
  'fourteenyear_old',
  'fourteenyearold',
  'fourteenyears old',
  'fourteenyears,old',
  'fourteenyears-old',
  'fourteenyears.old',
  'fourteenyears_old',
  'fourteenyearsold',
  'fourteenyo',
  'foury,o,',
  'foury-o-',
  'foury.o.',
  'foury_o_',
  'fouryear old',
  'fouryear,old',
  'fouryear-old',
  'fouryear.old',
  'fouryear_old',
  'fouryearold',
  'fouryears old',
  'fouryears,old',
  'fouryears-old',
  'fouryears.old',
  'fouryears_old',
  'fouryearsold',
  'fouryo',
  'gas chamber',
  'gas chambers',
  'girlish',
  'gook',
  'gooks',
  'gore',
  'granddaughter',
  'grandson',
  'guinne',
  'honkey',
  'immature',
  'immatured',
  'incest',
  'incestuous',
  'infant',
  'infantile',
  'innocent',
  'jail bait',
  'jail-bait',
  'jail.bait',
  'jail_bait',
  'jailbait',
  'jap',
  'japs',
  'jejune',
  'jew',
  'jews',
  'jigaboo',
  'juvenile',
  'kid',
  'kiddie',
  'kiddo',
  'kiddos',
  'kiddy',
  'kids',
  'kike',
  'kikes',
  'kkk',
  'kraut',
  'lil',
  'little',
  'little girl',
  'loli',
  'loli-con',
  'loli.con',
  'loli_con',
  'lolicon',
  'lolis',
  'lolita',
  'mick',
  'midget',
  'midgets',
  'minor',
  'minors',
  'mongoloid',
  'morbid',
  'n1g',
  'n1gga',
  'n1gger',
  'nazi',
  'nazis',
  'necro',
  'necrophilia',
  'negro',
  'negros',
  'neonazi',
  'neonazis',
  'nig',
  'niga',
  'nigas',
  'nigg3r',
  'nigg4h',
  'nigga',
  'niggah',
  'niggar',
  'niggas',
  'niggaz',
  'nigger',
  'niggers',
  'niglet',
  'niglets',
  'nignog',
  'nignogs',
  'nigs',
  'nine y.o.',
  'nine year old',
  'nine yearold',
  'nine years old',
  'nine yearsold',
  'nine yo',
  'nine,y,o,',
  'nine,year,old',
  'nine,yearold',
  'nine,years,old',
  'nine,yearsold',
  'nine,yo',
  'nine-y-o-',
  'nine-year-old',
  'nine-yearold',
  'nine-years-old',
  'nine-yearsold',
  'nine-yo',
  'nine.y.o.',
  'nine.year.old',
  'nine.yearold',
  'nine.years.old',
  'nine.yearsold',
  'nine.yo',
  'nine_y_o_',
  'nine_year_old',
  'nine_yearold',
  'nine_years_old',
  'nine_yearsold',
  'nine_yo',
  'niney,o,',
  'niney-o-',
  'niney.o.',
  'niney_o_',
  'nineyear old',
  'nineyear,old',
  'nineyear-old',
  'nineyear.old',
  'nineyear_old',
  'nineyearold',
  'nineyears old',
  'nineyears,old',
  'nineyears-old',
  'nineyears.old',
  'nineyears_old',
  'nineyearsold',
  'nineyo',
  'nonconsentual',
  'not mature',
  'not old',
  'nymph',
  'nymphet',
  'nympho',
  'nymphomaniac',
  'one y.o.',
  'one year old',
  'one yearold',
  'one years old',
  'one yearsold',
  'one yo',
  'one,y,o,',
  'one,year,old',
  'one,yearold',
  'one,years,old',
  'one,yearsold',
  'one,yo',
  'one-y-o-',
  'one-year-old',
  'one-yearold',
  'one-years-old',
  'one-yearsold',
  'one-yo',
  'one.y.o.',
  'one.year.old',
  'one.yearold',
  'one.years.old',
  'one.yearsold',
  'one.yo',
  'one_y_o_',
  'one_year_old',
  'one_yearold',
  'one_years_old',
  'one_yearsold',
  'one_yo',
  'oney,o,',
  'oney-o-',
  'oney.o.',
  'oney_o_',
  'oneyear old',
  'oneyear,old',
  'oneyear-old',
  'oneyear.old',
  'oneyear_old',
  'oneyearold',
  'oneyears old',
  'oneyears,old',
  'oneyears-old',
  'oneyears.old',
  'oneyears_old',
  'oneyearsold',
  'oneyo',
  'orphan',
  'orphanage',
  'paedophile',
  'paki',
  'pakis',
  'pedobear',
  'pedophile',
  'petite',
  'poop',
  'pooping',
  'poops',
  'porch monkey',
  'porch monkeys',
  'pre,teen',
  'pre,teenager',
  'pre-pubescent',
  'pre-teen',
  'pre-teenager',
  'pre-teens',
  'pre.teen',
  'pre.teenager',
  'pre.teens',
  'pre_teen',
  'pre_teenager',
  'pre_teens',
  'prepubescent',
  'preteen',
  'preteenager',
  'preteens',
  'princess',
  'princesses',
  'puberty',
  'pubescent',
  'puerile',
  'rag-head',
  'raghead',
  'ragheads',
  'rape',
  'raped',
  'raping',
  'rapist',
  'rapists',
  'retard',
  'retarded',
  'retards',
  'rice nigger',
  'rigor mortis',
  'scat',
  'scrawny',
  'seven y.o.',
  'seven year old',
  'seven yearold',
  'seven years old',
  'seven yearsold',
  'seven yo',
  'seven,y,o,',
  'seven,year,old',
  'seven,yearold',
  'seven,years,old',
  'seven,yearsold',
  'seven,yo',
  'seven-y-o-',
  'seven-year-old',
  'seven-yearold',
  'seven-years-old',
  'seven-yearsold',
  'seven-yo',
  'seven.y.o.',
  'seven.year.old',
  'seven.yearold',
  'seven.years.old',
  'seven.yearsold',
  'seven.yo',
  'seven_y_o_',
  'seven_year_old',
  'seven_yearold',
  'seven_years_old',
  'seven_yearsold',
  'seven_yo',
  'seventeen y.o.',
  'seventeen year old',
  'seventeen yearold',
  'seventeen years old',
  'seventeen yearsold',
  'seventeen yo',
  'seventeen,y,o,',
  'seventeen,year,old',
  'seventeen,yearold',
  'seventeen,years,old',
  'seventeen,yearsold',
  'seventeen,yo',
  'seventeen-y-o-',
  'seventeen-year-old',
  'seventeen-yearold',
  'seventeen-years-old',
  'seventeen-yearsold',
  'seventeen-yo',
  'seventeen.y.o.',
  'seventeen.year.old',
  'seventeen.yearold',
  'seventeen.years.old',
  'seventeen.yearsold',
  'seventeen.yo',
  'seventeen_y_o_',
  'seventeen_year_old',
  'seventeen_yearold',
  'seventeen_years_old',
  'seventeen_yearsold',
  'seventeen_yo',
  'seventeeny,o,',
  'seventeeny-o-',
  'seventeeny.o.',
  'seventeeny_o_',
  'seventeenyear old',
  'seventeenyear,old',
  'seventeenyear-old',
  'seventeenyear.old',
  'seventeenyear_old',
  'seventeenyearold',
  'seventeenyears old',
  'seventeenyears,old',
  'seventeenyears-old',
  'seventeenyears.old',
  'seventeenyears_old',
  'seventeenyearsold',
  'seventeenyo',
  'seveny,o,',
  'seveny-o-',
  'seveny.o.',
  'seveny_o_',
  'sevenyear old',
  'sevenyear,old',
  'sevenyear-old',
  'sevenyear.old',
  'sevenyear_old',
  'sevenyearold',
  'sevenyears old',
  'sevenyears,old',
  'sevenyears-old',
  'sevenyears.old',
  'sevenyears_old',
  'sevenyearsold',
  'sevenyo',
  'shit',
  'shitter',
  'shitting',
  'shota',
  'shota-con',
  'shota.con',
  'shota_con',
  'shotacon',
  'six y.o.',
  'six year old',
  'six yearold',
  'six years old',
  'six yearsold',
  'six yo',
  'six,y,o,',
  'six,year,old',
  'six,yearold',
  'six,years,old',
  'six,yearsold',
  'six,yo',
  'six-y-o-',
  'six-year-old',
  'six-yearold',
  'six-years-old',
  'six-yearsold',
  'six-yo',
  'six.y.o.',
  'six.year.old',
  'six.yearold',
  'six.years.old',
  'six.yearsold',
  'six.yo',
  'six_y_o_',
  'six_year_old',
  'six_yearold',
  'six_years_old',
  'six_yearsold',
  'six_yo',
  'sixteen y.o.',
  'sixteen year old',
  'sixteen yearold',
  'sixteen years old',
  'sixteen yearsold',
  'sixteen yo',
  'sixteen,y,o,',
  'sixteen,year,old',
  'sixteen,yearold',
  'sixteen,years,old',
  'sixteen,yearsold',
  'sixteen,yo',
  'sixteen-y-o-',
  'sixteen-year-old',
  'sixteen-yearold',
  'sixteen-years-old',
  'sixteen-yearsold',
  'sixteen-yo',
  'sixteen.y.o.',
  'sixteen.year.old',
  'sixteen.yearold',
  'sixteen.years.old',
  'sixteen.yearsold',
  'sixteen.yo',
  'sixteen_y_o_',
  'sixteen_year_old',
  'sixteen_yearold',
  'sixteen_years_old',
  'sixteen_yearsold',
  'sixteen_yo',
  'sixteeny,o,',
  'sixteeny-o-',
  'sixteeny.o.',
  'sixteeny_o_',
  'sixteenyear old',
  'sixteenyear,old',
  'sixteenyear-old',
  'sixteenyear.old',
  'sixteenyear_old',
  'sixteenyearold',
  'sixteenyears old',
  'sixteenyears,old',
  'sixteenyears-old',
  'sixteenyears.old',
  'sixteenyears_old',
  'sixteenyearsold',
  'sixteenyo',
  'sixy,o,',
  'sixy-o-',
  'sixy.o.',
  'sixy_o_',
  'sixyear old',
  'sixyear,old',
  'sixyear-old',
  'sixyear.old',
  'sixyear_old',
  'sixyearold',
  'sixyears old',
  'sixyears,old',
  'sixyears-old',
  'sixyears.old',
  'sixyears_old',
  'sixyearsold',
  'sixyo',
  'slave',
  'slaves',
  'small boobs',
  'small breasts',
  'small tits',
  'small-boobs',
  'small.boobs',
  'small_boobs',
  'small_breasts',
  'small_tits',
  'smegma',
  'son',
  'spic',
  'spics',
  'spook',
  'spooks',
  'statutory rape',
  'stripling',
  'striplings',
  'swastika',
  'teen',
  'teen-ager',
  'teenage',
  'teenager',
  'teenagers',
  'teenies',
  'teens',
  'teenybopper',
  'teenyboppers',
  'ten y.o.',
  'ten year old',
  'ten yearold',
  'ten years old',
  'ten yearsold',
  'ten yo',
  'ten,y,o,',
  'ten,year,old',
  'ten,yearold',
  'ten,years,old',
  'ten,yearsold',
  'ten,yo',
  'ten-y-o-',
  'ten-year-old',
  'ten-yearold',
  'ten-years-old',
  'ten-yearsold',
  'ten-yo',
  'ten.y.o.',
  'ten.year.old',
  'ten.yearold',
  'ten.years.old',
  'ten.yearsold',
  'ten.yo',
  'ten_y_o_',
  'ten_year_old',
  'ten_yearold',
  'ten_years_old',
  'ten_yearsold',
  'ten_yo',
  'teny,o,',
  'teny-o-',
  'teny.o.',
  'teny_o_',
  'tenyear old',
  'tenyear,old',
  'tenyear-old',
  'tenyear.old',
  'tenyear_old',
  'tenyearold',
  'tenyears old',
  'tenyears,old',
  'tenyears-old',
  'tenyears.old',
  'tenyears_old',
  'tenyearsold',
  'tenyo',
  'terrorist',
  'third reich',
  'thirteen y.o.',
  'thirteen year old',
  'thirteen yearold',
  'thirteen years old',
  'thirteen yearsold',
  'thirteen yo',
  'thirteen,y,o,',
  'thirteen,year,old',
  'thirteen,yearold',
  'thirteen,years,old',
  'thirteen,yearsold',
  'thirteen,yo',
  'thirteen-y-o-',
  'thirteen-year-old',
  'thirteen-yearold',
  'thirteen-years-old',
  'thirteen-yearsold',
  'thirteen-yo',
  'thirteen.y.o.',
  'thirteen.year.old',
  'thirteen.yearold',
  'thirteen.years.old',
  'thirteen.yearsold',
  'thirteen.yo',
  'thirteen_y_o_',
  'thirteen_year_old',
  'thirteen_yearold',
  'thirteen_years_old',
  'thirteen_yearsold',
  'thirteen_yo',
  'thirteeny,o,',
  'thirteeny-o-',
  'thirteeny.o.',
  'thirteeny_o_',
  'thirteenyear old',
  'thirteenyear,old',
  'thirteenyear-old',
  'thirteenyear.old',
  'thirteenyear_old',
  'thirteenyearold',
  'thirteenyears old',
  'thirteenyears,old',
  'thirteenyears-old',
  'thirteenyears.old',
  'thirteenyears_old',
  'thirteenyearsold',
  'thirteenyo',
  'three y.o.',
  'three year old',
  'three yearold',
  'three years old',
  'three yearsold',
  'three yo',
  'three,y,o,',
  'three,year,old',
  'three,yearold',
  'three,years,old',
  'three,yearsold',
  'three,yo',
  'three-y-o-',
  'three-year-old',
  'three-yearold',
  'three-years-old',
  'three-yearsold',
  'three-yo',
  'three.y.o.',
  'three.year.old',
  'three.yearold',
  'three.years.old',
  'three.yearsold',
  'three.yo',
  'three_y_o_',
  'three_year_old',
  'three_yearold',
  'three_years_old',
  'three_yearsold',
  'three_yo',
  'threey,o,',
  'threey-o-',
  'threey.o.',
  'threey_o_',
  'threeyear old',
  'threeyear,old',
  'threeyear-old',
  'threeyear.old',
  'threeyear_old',
  'threeyearold',
  'threeyears old',
  'threeyears,old',
  'threeyears-old',
  'threeyears.old',
  'threeyears_old',
  'threeyearsold',
  'threeyo',
  'tot',
  'towel head',
  'towel heads',
  'towelhead',
  'towelheads',
  'turk',
  'turks',
  'twelve y.o.',
  'twelve year old',
  'twelve yearold',
  'twelve years old',
  'twelve yearsold',
  'twelve yo',
  'twelve,y,o,',
  'twelve,year,old',
  'twelve,yearold',
  'twelve,years,old',
  'twelve,yearsold',
  'twelve,yo',
  'twelve-y-o-',
  'twelve-year-old',
  'twelve-yearold',
  'twelve-years-old',
  'twelve-yearsold',
  'twelve-yo',
  'twelve.y.o.',
  'twelve.year.old',
  'twelve.yearold',
  'twelve.years.old',
  'twelve.yearsold',
  'twelve.yo',
  'twelve_y_o_',
  'twelve_year_old',
  'twelve_yearold',
  'twelve_years_old',
  'twelve_yearsold',
  'twelve_yo',
  'twelvey,o,',
  'twelvey-o-',
  'twelvey.o.',
  'twelvey_o_',
  'twelveyear old',
  'twelveyear,old',
  'twelveyear-old',
  'twelveyear.old',
  'twelveyear_old',
  'twelveyearold',
  'twelveyears old',
  'twelveyears,old',
  'twelveyears-old',
  'twelveyears.old',
  'twelveyears_old',
  'twelveyearsold',
  'twelveyo',
  'two y.o.',
  'two year old',
  'two yearold',
  'two years old',
  'two yearsold',
  'two yo',
  'two,y,o,',
  'two,year,old',
  'two,yearold',
  'two,years,old',
  'two,yearsold',
  'two,yo',
  'two-y-o-',
  'two-year-old',
  'two-yearold',
  'two-years-old',
  'two-yearsold',
  'two-yo',
  'two.y.o.',
  'two.year.old',
  'two.yearold',
  'two.years.old',
  'two.yearsold',
  'two.yo',
  'two_y_o_',
  'two_year_old',
  'two_yearold',
  'two_years_old',
  'two_yearsold',
  'two_yo',
  'twoy,o,',
  'twoy-o-',
  'twoy.o.',
  'twoy_o_',
  'twoyear old',
  'twoyear,old',
  'twoyear-old',
  'twoyear.old',
  'twoyear_old',
  'twoyearold',
  'twoyears old',
  'twoyears,old',
  'twoyears-old',
  'twoyears.old',
  'twoyears_old',
  'twoyearsold',
  'twoyo',
  'under-age',
  'under-aged',
  'under-ager',
  'under-developed',
  'underage',
  'underaged',
  'underdeveloped',
  'undergrown',
  'ungrown',
  'wetback',
  'wetbacks',
  'wigger',
  'wiggers',
  'wop',
  'yigger',
];
// #endregion
