import { createKyselyClients } from '@civitai/db/kysely';
import { env } from '$env/dynamic/private';
import type { DB } from '@civitai/db-schema/kysely';

// Kysely read/write clients for the moderator app, built with the monorepo's `@civitai/db/kysely`
// factory. The factory owns pool construction, the cnpg SSL workaround (`sslNoVerify`), and the
// NUMERIC/INT8 → number parsers — so this app declares no `pg` dependency. `DB` is the full schema
// generated by prisma-kysely in @civitai/db-schema, keeping queries typed against the real columns.
function required(name: 'DATABASE_URL' | 'DATABASE_REPLICA_URL'): string {
  const value = env[name];
  if (!value) throw new Error(`${name} is not configured`);
  return value;
}

export const { dbRead, dbWrite } = createKyselyClients<DB>({
  connectionString: required('DATABASE_URL'),
  replicaConnectionString: required('DATABASE_REPLICA_URL'),
  sslNoVerify: true,
});
