/* GENERATED FILE
 * This file is automatically generated by the generate-types script.
 * Do not edit it manually.
 * Generated: 2026-08-17T02:44:44.059Z
 *
 * Run 'npm run generate-types' to update this file.
 */

export type ArticleMetrics = {
  Cry: number
  Dislike: number
  Heart: number
  Laugh: number
  Like: number
  collectedCount: number
  commentCount: number
  tippedAmount: number
  tippedCount: number
}

export type BountyMetrics = {
  benefactorCount: number
  commentCount: number
  entryCount: number
  favoriteCount: number
  trackCount: number
  unitAmount: number
}

export type BountyEntryMetrics = {
  Cry: number
  Dislike: number
  Heart: number
  Laugh: number
  Like: number
  unitAmount: number
}

export type CollectionMetrics = {
  contributorCount: number
  followerCount: number
  itemCount: number
}

export type ComicMetrics = {
  chapterReadCount: number
  followerCount: number
  hiddenCount: number
  readerCount: number
  tippedAmount: number
  tippedCount: number
}

export type ImageMetrics = {
  Buzz: number
  Collection: number
  Comment: number
  Cry: number
  Dislike: number
  Heart: number
  Laugh: number
  Like: number
  ReactionCry: number
  ReactionHeart: number
  ReactionLaugh: number
  ReactionLike: number
  commentCount: number
  tippedAmount: number
  tippedCount: number
}

export type ModelMetrics = {
  collectedCount: number
  commentCount: number
  downloadCount: number
  earnedAmount: number
  generationCount: number
  imageCount: number
  ratingCount: number
  thumbsDownCount: number
  thumbsUpCount: number
  tippedAmount: number
  tippedCount: number
}

export type ModelVersionMetrics = {
  downloadCount: number
  earnedAmount: number
  generationCount: number
  imageCount: number
  ratingCount: number
  thumbsDownCount: number
  thumbsUpCount: number
}

export type PostMetrics = {
  Cry: number
  Dislike: number
  Heart: number
  Laugh: number
  Like: number
  collectedCount: number
  commentCount: number
  reactionCount: number
  tippedAmount: number
  tippedCount: number
}

export type TagMetrics = {
  followerCount: number
  hiddenCount: number
}

export type UserMetrics = {
  articleCount: number
  bountyCount: number
  commentCount: number
  followerCount: number
  followingCount: number
  hiddenCount: number
  reactionCount: number
  tippedAmount: number
  tippedCount: number
  tipsGivenAmount: number
  tipsGivenCount: number
}

export type EntityMetrics = 
  { type: 'Article', metrics: ArticleMetrics }
  | { type: 'Bounty', metrics: BountyMetrics }
  | { type: 'BountyEntry', metrics: BountyEntryMetrics }
  | { type: 'Collection', metrics: CollectionMetrics }
  | { type: 'Comic', metrics: ComicMetrics }
  | { type: 'Image', metrics: ImageMetrics }
  | { type: 'Model', metrics: ModelMetrics }
  | { type: 'ModelVersion', metrics: ModelVersionMetrics }
  | { type: 'Post', metrics: PostMetrics }
  | { type: 'Tag', metrics: TagMetrics }
  | { type: 'User', metrics: UserMetrics }

export const ENTITY_METRIC_TYPES = {
  Article: ['Cry', 'Dislike', 'Heart', 'Laugh', 'Like', 'collectedCount', 'commentCount', 'tippedAmount', 'tippedCount'],
  Bounty: ['benefactorCount', 'commentCount', 'entryCount', 'favoriteCount', 'trackCount', 'unitAmount'],
  BountyEntry: ['Cry', 'Dislike', 'Heart', 'Laugh', 'Like', 'unitAmount'],
  Collection: ['contributorCount', 'followerCount', 'itemCount'],
  Comic: ['chapterReadCount', 'followerCount', 'hiddenCount', 'readerCount', 'tippedAmount', 'tippedCount'],
  Image: ['Buzz', 'Collection', 'Comment', 'Cry', 'Dislike', 'Heart', 'Laugh', 'Like', 'ReactionCry', 'ReactionHeart', 'ReactionLaugh', 'ReactionLike', 'commentCount', 'tippedAmount', 'tippedCount'],
  Model: ['collectedCount', 'commentCount', 'downloadCount', 'earnedAmount', 'generationCount', 'imageCount', 'ratingCount', 'thumbsDownCount', 'thumbsUpCount', 'tippedAmount', 'tippedCount'],
  ModelVersion: ['downloadCount', 'earnedAmount', 'generationCount', 'imageCount', 'ratingCount', 'thumbsDownCount', 'thumbsUpCount'],
  Post: ['Cry', 'Dislike', 'Heart', 'Laugh', 'Like', 'collectedCount', 'commentCount', 'reactionCount', 'tippedAmount', 'tippedCount'],
  Tag: ['followerCount', 'hiddenCount'],
  User: ['articleCount', 'bountyCount', 'commentCount', 'followerCount', 'followingCount', 'hiddenCount', 'reactionCount', 'tippedAmount', 'tippedCount', 'tipsGivenAmount', 'tipsGivenCount'],
} as const

export type EntityType = keyof typeof ENTITY_METRIC_TYPES

// Type mapping from entity type to metric type
export type EntityMetricMap = {
  Article: ArticleMetrics
  Bounty: BountyMetrics
  BountyEntry: BountyEntryMetrics
  Collection: CollectionMetrics
  Comic: ComicMetrics
  Image: ImageMetrics
  Model: ModelMetrics
  ModelVersion: ModelVersionMetrics
  Post: PostMetrics
  Tag: TagMetrics
  User: UserMetrics
}

export type EntityMetricTypes = typeof ENTITY_METRIC_TYPES

export type EntityMetricEvent = {
  [K in keyof EntityMetricTypes]: {
    entityType: K;
    entityId: number;
    userId: number;
    metricType: EntityMetricTypes[K][number];
    metricValue: number;
    createdAt: Date;
  }
}[keyof EntityMetricTypes];
