export declare const balanceCard: string;
export declare const bannerCard: string;
export declare const bannerTitle: string;
export declare const benefitsList: string;
export declare const topUpBadge: string;
export declare const topUpButton: string;
export declare const topUpCard: string;
export declare const topUpIcon: string;
export declare const topUpTitle: string;
