export const unpublishReasons = {
  'no-posts': {
    optionLabel: 'Missing images',
    notificationMessage: 'Your model did not include any example images.',
  },
  'no-versions': {
    optionLabel: 'Missing version',
    notificationMessage: 'Your model did not include any published versions.',
  },
  'no-files': {
    optionLabel: 'Missing files',
    notificationMessage: 'Your model did not include any files.',
  },
  'mature-real-person': {
    optionLabel: 'Real person(s) displayed in a mature context',
    notificationMessage:
      'Images of real people in sexual or suggestive situations are not allowed under our content rules.',
  },
  'mature-underage': {
    optionLabel: 'Minors displayed in a mature context',
    notificationMessage:
      'Images of individuals who appear to be underage in sexual or suggestive situations are not allowed under our content rules.',
  },
  'photo-real-underage': {
    optionLabel: 'Photorealistic depiction of a minor',
    notificationMessage:
      'Photorealistic depictions of minors are not allowed under our content rules.',
  },
  'hate-speech': {
    optionLabel: 'Promotion of hate-speech or targeted attack',
    notificationMessage:
      'Content intended to attack, harass, or discreminate against an individual or group based on identity is not allowed under our content rules.',
  },
  scat: {
    optionLabel: 'Depiction of "scat" or fecal matter',
    notificationMessage:
      'Content depicting the excrement of "scat" or fecal matter is not allowed under our content rules.',
  },
  violence: {
    optionLabel: 'Prohibited violent activities',
    notificationMessage: 'Content depicting graphic violence or extreme gore are not allowed.',
  },
  beastiality: {
    optionLabel: 'Depiction of "bestiality"',
    notificationMessage: 'Depictions of bestiality are not allowed.',
  },
  'non-generated-image': {
    optionLabel: 'Images are not generated by the resource',
    notificationMessage:
      'Resources must display images that are either generated by the resource or act as an aide in its use.',
  },
  'unintenteded-use': {
    optionLabel: 'Unintended site use',
    notificationMessage:
      'Civitai is currently only for the hosting and sharing of resources intended to be used with content generation.',
  },
  'insufficient-description': {
    optionLabel: 'Insufficient description',
    notificationMessage:
      'Insufficient description on your resource. Please include information like training steps, recommended weights, or additional information that would help users better utilize your resource.',
  },
  duplicate: {
    optionLabel: 'Duplicate upload',
    notificationMessage:
      'It appears your resource is identical to another resource thats currently live. To ensure Civitai hosts a wide variety of content we only allow one copy of a resource to be available at a time.',
  },
  spam: {
    optionLabel: 'Spam or advertorial content',
    notificationMessage:
      'Spam or advertisements posing as a resource are not allowed under our TOS.',
  },
  other: {
    optionLabel: 'Other',
    notificationMessage: '',
  },
} as const;

export type UnpublishReason = keyof typeof unpublishReasons;
