 SELECT t."answerId",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountDay",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountDayRank",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountWeek",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountWeekRank",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountMonth",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountMonthRank",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountYear",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountYearRank",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountAllTime",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountAllTimeRank",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountDay",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountDayRank",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountWeek",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountWeekRank",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountMonth",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountMonthRank",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountYear",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountYearRank",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountAllTime",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountAllTimeRank",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."checkCount", NULL::integer)) AS "checkCountDay",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."checkCountRank", NULL::bigint)) AS "checkCountDayRank",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."checkCount", NULL::integer)) AS "checkCountWeek",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."checkCountRank", NULL::bigint)) AS "checkCountWeekRank",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."checkCount", NULL::integer)) AS "checkCountMonth",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."checkCountRank", NULL::bigint)) AS "checkCountMonthRank",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."checkCount", NULL::integer)) AS "checkCountYear",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."checkCountRank", NULL::bigint)) AS "checkCountYearRank",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."checkCount", NULL::integer)) AS "checkCountAllTime",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."checkCountRank", NULL::bigint)) AS "checkCountAllTimeRank",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."crossCount", NULL::integer)) AS "crossCountDay",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."crossCountRank", NULL::bigint)) AS "crossCountDayRank",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."crossCount", NULL::integer)) AS "crossCountWeek",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."crossCountRank", NULL::bigint)) AS "crossCountWeekRank",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."crossCount", NULL::integer)) AS "crossCountMonth",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."crossCountRank", NULL::bigint)) AS "crossCountMonthRank",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."crossCount", NULL::integer)) AS "crossCountYear",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."crossCountRank", NULL::bigint)) AS "crossCountYearRank",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."crossCount", NULL::integer)) AS "crossCountAllTime",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."crossCountRank", NULL::bigint)) AS "crossCountAllTimeRank"
   FROM ( SELECT a.id AS "answerId",
            COALESCE(am."heartCount", 0) AS "heartCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(am."heartCount", 0) DESC, COALESCE(am."checkCount", 0) DESC, COALESCE(am."crossCount", 0), COALESCE(am."commentCount", 0) DESC, a.id DESC) AS "heartCountRank",
            COALESCE(am."commentCount", 0) AS "commentCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(am."commentCount", 0) DESC, COALESCE(am."heartCount", 0) DESC, COALESCE(am."checkCount", 0) DESC, a.id DESC) AS "commentCountRank",
            COALESCE(am."checkCount", 0) AS "checkCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(am."checkCount", 0) DESC, COALESCE(am."crossCount", 0), COALESCE(am."heartCount", 0) DESC, COALESCE(am."commentCount", 0) DESC, a.id DESC) AS "checkCountRank",
            COALESCE(am."crossCount", 0) AS "crossCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(am."crossCount", 0) DESC, COALESCE(am."checkCount", 0), COALESCE(am."heartCount", 0) DESC, COALESCE(am."commentCount", 0) DESC, a.id DESC) AS "crossCountRank",
            tf.timeframe
           FROM (("Answer" a
             CROSS JOIN ( SELECT unnest(enum_range(NULL::"MetricTimeframe")) AS timeframe) tf)
             LEFT JOIN "AnswerMetric" am ON (((am."answerId" = a.id) AND (am.timeframe = tf.timeframe))))) t
  GROUP BY t."answerId";