 WITH timeframe_stats AS (
         SELECT m."articleId",
            COALESCE(m."heartCount", 0) AS "heartCount",
            COALESCE(m."likeCount", 0) AS "likeCount",
            COALESCE(m."dislikeCount", 0) AS "dislikeCount",
            COALESCE(m."laughCount", 0) AS "laughCount",
            COALESCE(m."cryCount", 0) AS "cryCount",
            COALESCE(m."commentCount", 0) AS "commentCount",
            COALESCE(m."viewCount", 0) AS "viewCount",
            COALESCE(m."favoriteCount", 0) AS "favoriteCount",
            COALESCE(m."hideCount", 0) AS "hideCount",
            COALESCE(m."tippedCount", 0) AS "tippedCount",
            COALESCE(m."tippedAmountCount", 0) AS "tippedAmountCount",
            COALESCE(m."collectedCount", 0) AS "collectedCount",
            m.timeframe
           FROM "ArticleMetric" m
        )
 SELECT ts."articleId",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."heartCount", NULL::integer)) AS "heartCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."heartCount", NULL::integer)) AS "heartCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."heartCount", NULL::integer)) AS "heartCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."heartCount", NULL::integer)) AS "heartCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."heartCount", NULL::integer)) AS "heartCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."likeCount", NULL::integer)) AS "likeCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."likeCount", NULL::integer)) AS "likeCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."likeCount", NULL::integer)) AS "likeCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."likeCount", NULL::integer)) AS "likeCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."likeCount", NULL::integer)) AS "likeCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."dislikeCount", NULL::integer)) AS "dislikeCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."dislikeCount", NULL::integer)) AS "dislikeCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."dislikeCount", NULL::integer)) AS "dislikeCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."dislikeCount", NULL::integer)) AS "dislikeCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."dislikeCount", NULL::integer)) AS "dislikeCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."laughCount", NULL::integer)) AS "laughCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."laughCount", NULL::integer)) AS "laughCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."laughCount", NULL::integer)) AS "laughCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."laughCount", NULL::integer)) AS "laughCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."laughCount", NULL::integer)) AS "laughCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."cryCount", NULL::integer)) AS "cryCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."cryCount", NULL::integer)) AS "cryCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."cryCount", NULL::integer)) AS "cryCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."cryCount", NULL::integer)) AS "cryCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."cryCount", NULL::integer)) AS "cryCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."commentCount", NULL::integer)) AS "commentCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."commentCount", NULL::integer)) AS "commentCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."commentCount", NULL::integer)) AS "commentCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."commentCount", NULL::integer)) AS "commentCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."commentCount", NULL::integer)) AS "commentCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ((((ts."heartCount" + ts."dislikeCount") + ts."likeCount") + ts."cryCount") + ts."laughCount"), NULL::integer)) AS "reactionCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ((((ts."heartCount" + ts."dislikeCount") + ts."likeCount") + ts."cryCount") + ts."laughCount"), NULL::integer)) AS "reactionCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ((((ts."heartCount" + ts."dislikeCount") + ts."likeCount") + ts."cryCount") + ts."laughCount"), NULL::integer)) AS "reactionCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ((((ts."heartCount" + ts."dislikeCount") + ts."likeCount") + ts."cryCount") + ts."laughCount"), NULL::integer)) AS "reactionCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ((((ts."heartCount" + ts."dislikeCount") + ts."likeCount") + ts."cryCount") + ts."laughCount"), NULL::integer)) AS "reactionCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."viewCount", NULL::integer)) AS "viewCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."viewCount", NULL::integer)) AS "viewCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."viewCount", NULL::integer)) AS "viewCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."viewCount", NULL::integer)) AS "viewCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."viewCount", NULL::integer)) AS "viewCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."favoriteCount", NULL::integer)) AS "favoriteCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."favoriteCount", NULL::integer)) AS "favoriteCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."favoriteCount", NULL::integer)) AS "favoriteCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."favoriteCount", NULL::integer)) AS "favoriteCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."favoriteCount", NULL::integer)) AS "favoriteCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."collectedCount", NULL::integer)) AS "collectedCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."collectedCount", NULL::integer)) AS "collectedCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."collectedCount", NULL::integer)) AS "collectedCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."collectedCount", NULL::integer)) AS "collectedCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."collectedCount", NULL::integer)) AS "collectedCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."hideCount", NULL::integer)) AS "hideCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."hideCount", NULL::integer)) AS "hideCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."hideCount", NULL::integer)) AS "hideCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."hideCount", NULL::integer)) AS "hideCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."hideCount", NULL::integer)) AS "hideCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."tippedCount", NULL::integer)) AS "tippedCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."tippedCount", NULL::integer)) AS "tippedCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."tippedCount", NULL::integer)) AS "tippedCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."tippedCount", NULL::integer)) AS "tippedCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."tippedCount", NULL::integer)) AS "tippedCountAllTime",
    max(iif((ts.timeframe = 'Day'::"MetricTimeframe"), ts."tippedAmountCount", NULL::integer)) AS "tippedAmountCountDay",
    max(iif((ts.timeframe = 'Week'::"MetricTimeframe"), ts."tippedAmountCount", NULL::integer)) AS "tippedAmountCountWeek",
    max(iif((ts.timeframe = 'Month'::"MetricTimeframe"), ts."tippedAmountCount", NULL::integer)) AS "tippedAmountCountMonth",
    max(iif((ts.timeframe = 'Year'::"MetricTimeframe"), ts."tippedAmountCount", NULL::integer)) AS "tippedAmountCountYear",
    max(iif((ts.timeframe = 'AllTime'::"MetricTimeframe"), ts."tippedAmountCount", NULL::integer)) AS "tippedAmountCountAllTime"
   FROM timeframe_stats ts
  GROUP BY ts."articleId";