 WITH stats_timeframe AS (
         SELECT m."bountyEntryId",
            m.timeframe,
            COALESCE(m."heartCount", 0) AS "heartCount",
            COALESCE(m."likeCount", 0) AS "likeCount",
            COALESCE(m."dislikeCount", 0) AS "dislikeCount",
            COALESCE(m."laughCount", 0) AS "laughCount",
            COALESCE(m."cryCount", 0) AS "cryCount",
            ((((COALESCE(m."heartCount", 0) + COALESCE(m."likeCount", 0)) + COALESCE(m."dislikeCount", 0)) + COALESCE(m."laughCount", 0)) + COALESCE(m."cryCount", 0)) AS "reactionCount",
            COALESCE(m."unitAmountCount", 0) AS "unitAmountCount",
            COALESCE(m."tippedCount", 0) AS "tippedCount",
            COALESCE(m."tippedAmountCount", 0) AS "tippedAmountCount"
           FROM "BountyEntryMetric" m
          GROUP BY m."bountyEntryId", m.timeframe
        )
 SELECT stats_timeframe."bountyEntryId",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."heartCount", NULL::integer)) AS "heartCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."heartCount", NULL::integer)) AS "heartCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."heartCount", NULL::integer)) AS "heartCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."heartCount", NULL::integer)) AS "heartCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."heartCount", NULL::integer)) AS "heartCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."likeCount", NULL::integer)) AS "likeCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."likeCount", NULL::integer)) AS "likeCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."likeCount", NULL::integer)) AS "likeCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."likeCount", NULL::integer)) AS "likeCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."likeCount", NULL::integer)) AS "likeCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."dislikeCount", NULL::integer)) AS "dislikeCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."dislikeCount", NULL::integer)) AS "dislikeCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."dislikeCount", NULL::integer)) AS "dislikeCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."dislikeCount", NULL::integer)) AS "dislikeCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."dislikeCount", NULL::integer)) AS "dislikeCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."laughCount", NULL::integer)) AS "laughCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."laughCount", NULL::integer)) AS "laughCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."laughCount", NULL::integer)) AS "laughCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."laughCount", NULL::integer)) AS "laughCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."laughCount", NULL::integer)) AS "laughCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."cryCount", NULL::integer)) AS "cryCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."cryCount", NULL::integer)) AS "cryCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."cryCount", NULL::integer)) AS "cryCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."cryCount", NULL::integer)) AS "cryCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."cryCount", NULL::integer)) AS "cryCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), ((((stats_timeframe."heartCount" + stats_timeframe."dislikeCount") + stats_timeframe."likeCount") + stats_timeframe."cryCount") + stats_timeframe."laughCount"), NULL::integer)) AS "reactionCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), ((((stats_timeframe."heartCount" + stats_timeframe."dislikeCount") + stats_timeframe."likeCount") + stats_timeframe."cryCount") + stats_timeframe."laughCount"), NULL::integer)) AS "reactionCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), ((((stats_timeframe."heartCount" + stats_timeframe."dislikeCount") + stats_timeframe."likeCount") + stats_timeframe."cryCount") + stats_timeframe."laughCount"), NULL::integer)) AS "reactionCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), ((((stats_timeframe."heartCount" + stats_timeframe."dislikeCount") + stats_timeframe."likeCount") + stats_timeframe."cryCount") + stats_timeframe."laughCount"), NULL::integer)) AS "reactionCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), ((((stats_timeframe."heartCount" + stats_timeframe."dislikeCount") + stats_timeframe."likeCount") + stats_timeframe."cryCount") + stats_timeframe."laughCount"), NULL::integer)) AS "reactionCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."unitAmountCount", NULL::integer)) AS "unitAmountCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."unitAmountCount", NULL::integer)) AS "unitAmountCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."unitAmountCount", NULL::integer)) AS "unitAmountCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."unitAmountCount", NULL::integer)) AS "unitAmountCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."unitAmountCount", NULL::integer)) AS "unitAmountCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."tippedCount", NULL::integer)) AS "tippedCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."tippedCount", NULL::integer)) AS "tippedCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."tippedCount", NULL::integer)) AS "tippedCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."tippedCount", NULL::integer)) AS "tippedCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."tippedCount", NULL::integer)) AS "tippedCountAllTime",
    max(iif((stats_timeframe.timeframe = 'Day'::"MetricTimeframe"), stats_timeframe."tippedAmountCount", NULL::integer)) AS "tippedAmountCountDay",
    max(iif((stats_timeframe.timeframe = 'Week'::"MetricTimeframe"), stats_timeframe."tippedAmountCount", NULL::integer)) AS "tippedAmountCountWeek",
    max(iif((stats_timeframe.timeframe = 'Month'::"MetricTimeframe"), stats_timeframe."tippedAmountCount", NULL::integer)) AS "tippedAmountCountMonth",
    max(iif((stats_timeframe.timeframe = 'Year'::"MetricTimeframe"), stats_timeframe."tippedAmountCount", NULL::integer)) AS "tippedAmountCountYear",
    max(iif((stats_timeframe.timeframe = 'AllTime'::"MetricTimeframe"), stats_timeframe."tippedAmountCount", NULL::integer)) AS "tippedAmountCountAllTime"
   FROM stats_timeframe
  GROUP BY stats_timeframe."bountyEntryId";