 WITH timeframe_stats AS (
         SELECT im."imageId",
            COALESCE(im."heartCount", 0) AS "heartCount",
            COALESCE(im."likeCount", 0) AS "likeCount",
            COALESCE(im."dislikeCount", 0) AS "dislikeCount",
            COALESCE(im."laughCount", 0) AS "laughCount",
            COALESCE(im."cryCount", 0) AS "cryCount",
            COALESCE(im."commentCount", 0) AS "commentCount",
            COALESCE(im."collectedCount", 0) AS "collectedCount",
            COALESCE(im."tippedCount", 0) AS "tippedCount",
            COALESCE(im."tippedAmountCount", 0) AS "tippedAmountCount",
            COALESCE(im."viewCount", 0) AS "viewCount",
            im.timeframe
           FROM "ImageMetric" im
        )
 SELECT timeframe_stats."imageId",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."heartCount", NULL::integer)) AS "heartCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."heartCount", NULL::integer)) AS "heartCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."heartCount", NULL::integer)) AS "heartCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."heartCount", NULL::integer)) AS "heartCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."heartCount", NULL::integer)) AS "heartCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."likeCount", NULL::integer)) AS "likeCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."likeCount", NULL::integer)) AS "likeCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."likeCount", NULL::integer)) AS "likeCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."likeCount", NULL::integer)) AS "likeCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."likeCount", NULL::integer)) AS "likeCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."dislikeCount", NULL::integer)) AS "dislikeCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."dislikeCount", NULL::integer)) AS "dislikeCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."dislikeCount", NULL::integer)) AS "dislikeCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."dislikeCount", NULL::integer)) AS "dislikeCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."dislikeCount", NULL::integer)) AS "dislikeCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."laughCount", NULL::integer)) AS "laughCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."laughCount", NULL::integer)) AS "laughCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."laughCount", NULL::integer)) AS "laughCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."laughCount", NULL::integer)) AS "laughCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."laughCount", NULL::integer)) AS "laughCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."cryCount", NULL::integer)) AS "cryCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."cryCount", NULL::integer)) AS "cryCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."cryCount", NULL::integer)) AS "cryCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."cryCount", NULL::integer)) AS "cryCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."cryCount", NULL::integer)) AS "cryCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."commentCount", NULL::integer)) AS "commentCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."commentCount", NULL::integer)) AS "commentCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."commentCount", NULL::integer)) AS "commentCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."commentCount", NULL::integer)) AS "commentCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."commentCount", NULL::integer)) AS "commentCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountAllTime",
    max(iif((timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), timeframe_stats."viewCount", NULL::integer)) AS "viewCountDay",
    max(iif((timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), timeframe_stats."viewCount", NULL::integer)) AS "viewCountWeek",
    max(iif((timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), timeframe_stats."viewCount", NULL::integer)) AS "viewCountMonth",
    max(iif((timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), timeframe_stats."viewCount", NULL::integer)) AS "viewCountYear",
    max(iif((timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), timeframe_stats."viewCount", NULL::integer)) AS "viewCountAllTime"
   FROM timeframe_stats
  GROUP BY timeframe_stats."imageId";