 WITH model_timeframe_stats AS (
         SELECT m.id AS "modelId",
            COALESCE(mm."downloadCount", 0) AS "downloadCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."downloadCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."ratingCount", 0) DESC, m.id DESC) AS "downloadCountRank",
            COALESCE(mm."ratingCount", 0) AS "ratingCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."ratingCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "ratingCountRank",
            COALESCE(mm."favoriteCount", 0) AS "favoriteCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."favoriteCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "favoriteCountRank",
            COALESCE(mm."commentCount", 0) AS "commentCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."commentCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "commentCountRank",
            COALESCE(mm.rating, (0)::double precision) AS rating,
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY (((COALESCE(mm.rating, (0)::double precision) * (COALESCE(mm."ratingCount", 0))::double precision) + ((3.5 * (10)::numeric))::double precision) / ((COALESCE(mm."ratingCount", 0) + 10))::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "ratingRank",
            row_number() OVER (ORDER BY GREATEST(m."lastVersionAt", m."publishedAt") DESC, m.id DESC) AS "newRank",
            COALESCE(date_part('day'::text, (now() - (m."publishedAt")::timestamp with time zone)), (0)::double precision) AS age_days,
            COALESCE(mm."imageCount", 0) AS "imageCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."imageCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "imageCountRank",
            COALESCE(mm."collectedCount", 0) AS "collectedCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."collectedCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "collectedCountRank",
            COALESCE(mm."tippedCount", 0) AS "tippedCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."tippedCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "tippedCountRank",
            COALESCE(mm."tippedAmountCount", 0) AS "tippedAmountCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."tippedAmountCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "tippedAmountCountRank",
            COALESCE(mm."generationCount", 0) AS "generationCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(mm."generationCount", 0) DESC, COALESCE(mm.rating, (0)::double precision) DESC, COALESCE(mm."downloadCount", 0) DESC, m.id DESC) AS "generationCountRank",
            tf.timeframe
           FROM (("Model" m
             CROSS JOIN ( SELECT unnest(enum_range(NULL::"MetricTimeframe")) AS timeframe) tf)
             LEFT JOIN "ModelMetric" mm ON (((mm."modelId" = m.id) AND (mm.timeframe = tf.timeframe))))
        )
 SELECT model_timeframe_stats."modelId",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."downloadCount", NULL::integer)) AS "downloadCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."downloadCount", NULL::integer)) AS "downloadCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."downloadCount", NULL::integer)) AS "downloadCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."downloadCount", NULL::integer)) AS "downloadCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."downloadCount", NULL::integer)) AS "downloadCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."downloadCountRank", NULL::bigint)) AS "downloadCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."downloadCountRank", NULL::bigint)) AS "downloadCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."downloadCountRank", NULL::bigint)) AS "downloadCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."downloadCountRank", NULL::bigint)) AS "downloadCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."downloadCountRank", NULL::bigint)) AS "downloadCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."ratingCount", NULL::integer)) AS "ratingCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."ratingCount", NULL::integer)) AS "ratingCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."ratingCount", NULL::integer)) AS "ratingCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."ratingCount", NULL::integer)) AS "ratingCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."ratingCount", NULL::integer)) AS "ratingCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."ratingCountRank", NULL::bigint)) AS "ratingCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."ratingCountRank", NULL::bigint)) AS "ratingCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."ratingCountRank", NULL::bigint)) AS "ratingCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."ratingCountRank", NULL::bigint)) AS "ratingCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."ratingCountRank", NULL::bigint)) AS "ratingCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats.rating, NULL::double precision)) AS "ratingDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats.rating, NULL::double precision)) AS "ratingWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats.rating, NULL::double precision)) AS "ratingMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats.rating, NULL::double precision)) AS "ratingYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats.rating, NULL::double precision)) AS "ratingAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."ratingRank", NULL::bigint)) AS "ratingDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."ratingRank", NULL::bigint)) AS "ratingWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."ratingRank", NULL::bigint)) AS "ratingMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."ratingRank", NULL::bigint)) AS "ratingYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."ratingRank", NULL::bigint)) AS "ratingAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."favoriteCount", NULL::integer)) AS "favoriteCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."favoriteCount", NULL::integer)) AS "favoriteCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."favoriteCount", NULL::integer)) AS "favoriteCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."favoriteCount", NULL::integer)) AS "favoriteCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."favoriteCount", NULL::integer)) AS "favoriteCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."favoriteCountRank", NULL::bigint)) AS "favoriteCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."favoriteCountRank", NULL::bigint)) AS "favoriteCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."favoriteCountRank", NULL::bigint)) AS "favoriteCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."favoriteCountRank", NULL::bigint)) AS "favoriteCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."favoriteCountRank", NULL::bigint)) AS "favoriteCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."commentCount", NULL::integer)) AS "commentCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."commentCount", NULL::integer)) AS "commentCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."commentCount", NULL::integer)) AS "commentCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."commentCount", NULL::integer)) AS "commentCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."commentCount", NULL::integer)) AS "commentCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."commentCountRank", NULL::bigint)) AS "commentCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."commentCountRank", NULL::bigint)) AS "commentCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."commentCountRank", NULL::bigint)) AS "commentCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."commentCountRank", NULL::bigint)) AS "commentCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."commentCountRank", NULL::bigint)) AS "commentCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."imageCount", NULL::integer)) AS "imageCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."imageCount", NULL::integer)) AS "imageCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."imageCount", NULL::integer)) AS "imageCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."imageCount", NULL::integer)) AS "imageCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."imageCount", NULL::integer)) AS "imageCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."imageCountRank", NULL::bigint)) AS "imageCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."imageCountRank", NULL::bigint)) AS "imageCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."imageCountRank", NULL::bigint)) AS "imageCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."imageCountRank", NULL::bigint)) AS "imageCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."imageCountRank", NULL::bigint)) AS "imageCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."collectedCount", NULL::integer)) AS "collectedCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."collectedCountRank", NULL::bigint)) AS "collectedCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."collectedCountRank", NULL::bigint)) AS "collectedCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."collectedCountRank", NULL::bigint)) AS "collectedCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."collectedCountRank", NULL::bigint)) AS "collectedCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."collectedCountRank", NULL::bigint)) AS "collectedCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."newRank", NULL::bigint)) AS "newRank",
    max(model_timeframe_stats.age_days) AS age_days,
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."tippedCount", NULL::integer)) AS "tippedCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."tippedCountRank", NULL::bigint)) AS "tippedCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."tippedCountRank", NULL::bigint)) AS "tippedCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."tippedCountRank", NULL::bigint)) AS "tippedCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."tippedCountRank", NULL::bigint)) AS "tippedCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."tippedCountRank", NULL::bigint)) AS "tippedCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCount", NULL::integer)) AS "tippedAmountCountAllTime",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCountRank", NULL::bigint)) AS "tippedAmountCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCountRank", NULL::bigint)) AS "tippedAmountCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCountRank", NULL::bigint)) AS "tippedAmountCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCountRank", NULL::bigint)) AS "tippedAmountCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."tippedAmountCountRank", NULL::bigint)) AS "tippedAmountCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."generationCountRank", NULL::bigint)) AS "generationCountDayRank",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."generationCountRank", NULL::bigint)) AS "generationCountWeekRank",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."generationCountRank", NULL::bigint)) AS "generationCountMonthRank",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."generationCountRank", NULL::bigint)) AS "generationCountYearRank",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."generationCountRank", NULL::bigint)) AS "generationCountAllTimeRank",
    max(iif((model_timeframe_stats.timeframe = 'Day'::"MetricTimeframe"), model_timeframe_stats."generationCount", NULL::integer)) AS "generationCountDay",
    max(iif((model_timeframe_stats.timeframe = 'Week'::"MetricTimeframe"), model_timeframe_stats."generationCount", NULL::integer)) AS "generationCountWeek",
    max(iif((model_timeframe_stats.timeframe = 'Month'::"MetricTimeframe"), model_timeframe_stats."generationCount", NULL::integer)) AS "generationCountMonth",
    max(iif((model_timeframe_stats.timeframe = 'Year'::"MetricTimeframe"), model_timeframe_stats."generationCount", NULL::integer)) AS "generationCountYear",
    max(iif((model_timeframe_stats.timeframe = 'AllTime'::"MetricTimeframe"), model_timeframe_stats."generationCount", NULL::integer)) AS "generationCountAllTime"
   FROM model_timeframe_stats
  GROUP BY model_timeframe_stats."modelId";