 SELECT DISTINCT ON ("ImageResourceHelper"."postId", "ImageResourceHelper".name, "ImageResourceHelper"."modelVersionId") "ImageResourceHelper".id,
    "ImageResourceHelper"."imageId",
    "ImageResourceHelper"."reviewId",
    "ImageResourceHelper"."reviewRating",
    "ImageResourceHelper"."reviewRecommended",
    "ImageResourceHelper"."reviewDetails",
    "ImageResourceHelper"."reviewCreatedAt",
    "ImageResourceHelper".name,
    "ImageResourceHelper"."modelVersionId",
    "ImageResourceHelper"."modelVersionName",
    "ImageResourceHelper"."modelVersionCreatedAt",
    "ImageResourceHelper"."modelId",
    "ImageResourceHelper"."modelName",
    "ImageResourceHelper"."modelThumbsUpCount",
    "ImageResourceHelper"."modelThumbsDownCount",
    "ImageResourceHelper"."modelDownloadCount",
    "ImageResourceHelper"."modelCommentCount",
    "ImageResourceHelper"."modelType",
    "ImageResourceHelper"."postId",
    "ImageResourceHelper"."modelRating",
    "ImageResourceHelper"."modelRatingCount",
    "ImageResourceHelper"."modelFavoriteCount"
   FROM "ImageResourceHelper";