 SELECT t."questionId",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountDay",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountDayRank",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountWeek",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountWeekRank",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountMonth",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountMonthRank",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountYear",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountYearRank",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."heartCount", NULL::integer)) AS "heartCountAllTime",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."heartCountRank", NULL::bigint)) AS "heartCountAllTimeRank",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountDay",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountDayRank",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountWeek",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountWeekRank",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountMonth",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountMonthRank",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountYear",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountYearRank",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."commentCount", NULL::integer)) AS "commentCountAllTime",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."commentCountRank", NULL::bigint)) AS "commentCountAllTimeRank",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."answerCount", NULL::integer)) AS "answerCountDay",
    max(iif((t.timeframe = 'Day'::"MetricTimeframe"), t."answerCountRank", NULL::bigint)) AS "answerCountDayRank",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."answerCount", NULL::integer)) AS "answerCountWeek",
    max(iif((t.timeframe = 'Week'::"MetricTimeframe"), t."answerCountRank", NULL::bigint)) AS "answerCountWeekRank",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."answerCount", NULL::integer)) AS "answerCountMonth",
    max(iif((t.timeframe = 'Month'::"MetricTimeframe"), t."answerCountRank", NULL::bigint)) AS "answerCountMonthRank",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."answerCount", NULL::integer)) AS "answerCountYear",
    max(iif((t.timeframe = 'Year'::"MetricTimeframe"), t."answerCountRank", NULL::bigint)) AS "answerCountYearRank",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."answerCount", NULL::integer)) AS "answerCountAllTime",
    max(iif((t.timeframe = 'AllTime'::"MetricTimeframe"), t."answerCountRank", NULL::bigint)) AS "answerCountAllTimeRank"
   FROM ( SELECT q.id AS "questionId",
            COALESCE(qm."heartCount", 0) AS "heartCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(qm."heartCount", 0) DESC, COALESCE(qm."answerCount", 0) DESC, COALESCE(qm."commentCount", 0) DESC, q.id DESC) AS "heartCountRank",
            COALESCE(qm."commentCount", 0) AS "commentCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(qm."commentCount", 0) DESC, COALESCE(qm."heartCount", 0) DESC, COALESCE(qm."answerCount", 0) DESC, q.id DESC) AS "commentCountRank",
            COALESCE(qm."answerCount", 0) AS "answerCount",
            row_number() OVER (PARTITION BY tf.timeframe ORDER BY COALESCE(qm."answerCount", 0) DESC, COALESCE(qm."heartCount", 0) DESC, COALESCE(qm."commentCount", 0) DESC, q.id DESC) AS "answerCountRank",
            tf.timeframe
           FROM (("Question" q
             CROSS JOIN ( SELECT unnest(enum_range(NULL::"MetricTimeframe")) AS timeframe) tf)
             LEFT JOIN "QuestionMetric" qm ON (((qm."questionId" = q.id) AND (qm.timeframe = tf.timeframe))))) t
  GROUP BY t."questionId";