 SELECT "TagMetric"."tagId",
    max(iif(("TagMetric".timeframe = 'Day'::"MetricTimeframe"), "TagMetric"."followerCount", NULL::integer)) AS "followerCountDay",
    max(iif(("TagMetric".timeframe = 'Week'::"MetricTimeframe"), "TagMetric"."followerCount", NULL::integer)) AS "followerCountWeek",
    max(iif(("TagMetric".timeframe = 'Month'::"MetricTimeframe"), "TagMetric"."followerCount", NULL::integer)) AS "followerCountMonth",
    max(iif(("TagMetric".timeframe = 'Year'::"MetricTimeframe"), "TagMetric"."followerCount", NULL::integer)) AS "followerCountYear",
    max(iif(("TagMetric".timeframe = 'AllTime'::"MetricTimeframe"), "TagMetric"."followerCount", NULL::integer)) AS "followerCountAllTime",
    max(iif(("TagMetric".timeframe = 'Day'::"MetricTimeframe"), "TagMetric"."hiddenCount", NULL::integer)) AS "hiddenCountDay",
    max(iif(("TagMetric".timeframe = 'Week'::"MetricTimeframe"), "TagMetric"."hiddenCount", NULL::integer)) AS "hiddenCountWeek",
    max(iif(("TagMetric".timeframe = 'Month'::"MetricTimeframe"), "TagMetric"."hiddenCount", NULL::integer)) AS "hiddenCountMonth",
    max(iif(("TagMetric".timeframe = 'Year'::"MetricTimeframe"), "TagMetric"."hiddenCount", NULL::integer)) AS "hiddenCountYear",
    max(iif(("TagMetric".timeframe = 'AllTime'::"MetricTimeframe"), "TagMetric"."hiddenCount", NULL::integer)) AS "hiddenCountAllTime",
    max(iif(("TagMetric".timeframe = 'Day'::"MetricTimeframe"), "TagMetric"."modelCount", NULL::integer)) AS "modelCountDay",
    max(iif(("TagMetric".timeframe = 'Week'::"MetricTimeframe"), "TagMetric"."modelCount", NULL::integer)) AS "modelCountWeek",
    max(iif(("TagMetric".timeframe = 'Month'::"MetricTimeframe"), "TagMetric"."modelCount", NULL::integer)) AS "modelCountMonth",
    max(iif(("TagMetric".timeframe = 'Year'::"MetricTimeframe"), "TagMetric"."modelCount", NULL::integer)) AS "modelCountYear",
    max(iif(("TagMetric".timeframe = 'AllTime'::"MetricTimeframe"), "TagMetric"."modelCount", NULL::integer)) AS "modelCountAllTime",
    max(iif(("TagMetric".timeframe = 'Day'::"MetricTimeframe"), "TagMetric"."imageCount", NULL::integer)) AS "imageCountDay",
    max(iif(("TagMetric".timeframe = 'Week'::"MetricTimeframe"), "TagMetric"."imageCount", NULL::integer)) AS "imageCountWeek",
    max(iif(("TagMetric".timeframe = 'Month'::"MetricTimeframe"), "TagMetric"."imageCount", NULL::integer)) AS "imageCountMonth",
    max(iif(("TagMetric".timeframe = 'Year'::"MetricTimeframe"), "TagMetric"."imageCount", NULL::integer)) AS "imageCountYear",
    max(iif(("TagMetric".timeframe = 'AllTime'::"MetricTimeframe"), "TagMetric"."imageCount", NULL::integer)) AS "imageCountAllTime",
    max(iif(("TagMetric".timeframe = 'Day'::"MetricTimeframe"), "TagMetric"."postCount", NULL::integer)) AS "postCountDay",
    max(iif(("TagMetric".timeframe = 'Week'::"MetricTimeframe"), "TagMetric"."postCount", NULL::integer)) AS "postCountWeek",
    max(iif(("TagMetric".timeframe = 'Month'::"MetricTimeframe"), "TagMetric"."postCount", NULL::integer)) AS "postCountMonth",
    max(iif(("TagMetric".timeframe = 'Year'::"MetricTimeframe"), "TagMetric"."postCount", NULL::integer)) AS "postCountYear",
    max(iif(("TagMetric".timeframe = 'AllTime'::"MetricTimeframe"), "TagMetric"."postCount", NULL::integer)) AS "postCountAllTime",
    max(iif(("TagMetric".timeframe = 'Day'::"MetricTimeframe"), "TagMetric"."articleCount", NULL::integer)) AS "articleCountDay",
    max(iif(("TagMetric".timeframe = 'Week'::"MetricTimeframe"), "TagMetric"."articleCount", NULL::integer)) AS "articleCountWeek",
    max(iif(("TagMetric".timeframe = 'Month'::"MetricTimeframe"), "TagMetric"."articleCount", NULL::integer)) AS "articleCountMonth",
    max(iif(("TagMetric".timeframe = 'Year'::"MetricTimeframe"), "TagMetric"."articleCount", NULL::integer)) AS "articleCountYear",
    max(iif(("TagMetric".timeframe = 'AllTime'::"MetricTimeframe"), "TagMetric"."articleCount", NULL::integer)) AS "articleCountAllTime"
   FROM "TagMetric"
  GROUP BY "TagMetric"."tagId";